#!/usr/bin/env python3
"""Rich content per gli strumenti standalone ex template compatto:
Adobe Acrobat Pro/Standard, CorelDRAW Graphics Suite 2024, Acronis True Image
Advanced. Il chrome UI condiviso (breadcrumb, eyebrow di sezione, label FAQ...)
riusa product_content_windows.UI: i default step/specs di quel dizionario
(setup.office.com, requisiti Office) non vengono mai letti perché ogni
prodotto qui fornisce sempre `steps` e `specs` propri.
"""

from lang_backfill import backfill_lang
from nl_translations import nl_text

LANGS = ("it", "en", "fr", "de", "es", "pt", "nl")


def L(**kwargs):
    if "pt" not in kwargs:
        kwargs["pt"] = kwargs.get("es") or kwargs.get("en")
    if "nl" not in kwargs:
        kwargs["nl"] = kwargs.get("en")
    return {k: kwargs[k] for k in LANGS}


PRODUCTS = {
    "adobe-acrobat-pro": {
        "seo_title": L(
            it="Adobe Acrobat Pro — 2 dispositivi — Eurolicenze",
            en="Adobe Acrobat Pro — 2 devices — Eurolicenze",
            fr="Adobe Acrobat Pro — 2 appareils — Eurolicenze",
            de="Adobe Acrobat Pro — 2 Geräte — Eurolicenze",
            es="Adobe Acrobat Pro — 2 dispositivos — Eurolicenze",
            pt="Adobe Acrobat Pro — 2 dispositivos — Eurolicenze",
            nl="Adobe Acrobat Pro — 2 apparaten — Eurolicenze",
        ),
        "title_html": L(
            it='Adobe Acrobat <span>Pro</span>',
            en='Adobe Acrobat <span>Pro</span>',
            fr='Adobe Acrobat <span>Pro</span>',
            de='Adobe Acrobat <span>Pro</span>',
            es='Adobe Acrobat <span>Pro</span>',
            pt='Adobe Acrobat <span>Pro</span>',
            nl='Adobe Acrobat <span>Pro</span>',
        ),
        "eyebrow": L(
            it="Abbonamento · editing, firma e conversione PDF",
            en="Subscription · PDF editing, signing and conversion",
            fr="Abonnement · édition, signature et conversion PDF",
            de="Abonnement · PDF bearbeiten, signieren, konvertieren",
            es="Suscripción · edición, firma y conversión de PDF",
            pt="Subscrição · edição, assinatura e conversão de PDF",
            nl="Abonnement · PDF bewerken, ondertekenen en converteren",
        ),
        "desc": L(
            it="Licenza digitale originale di Adobe Acrobat Pro: modifica, converti, firma elettronicamente e proteggi i tuoi PDF da desktop, web e mobile. Codice e istruzioni via email dopo l'acquisto.",
            en="Genuine digital licence for Adobe Acrobat Pro: edit, convert, e-sign and protect your PDFs from desktop, web and mobile. Code and instructions by email after purchase.",
            fr="Licence numérique originale d'Adobe Acrobat Pro : modifiez, convertissez, signez électroniquement et protégez vos PDF depuis le bureau, le web et le mobile. Code et instructions par e-mail après l'achat.",
            de="Originale digitale Lizenz für Adobe Acrobat Pro: PDFs bearbeiten, konvertieren, elektronisch signieren und schützen — am Desktop, im Web und mobil. Code und Anleitung per E-Mail nach dem Kauf.",
            es="Licencia digital original de Adobe Acrobat Pro: edita, convierte, firma electrónicamente y protege tus PDF desde el escritorio, la web y el móvil. Código e instrucciones por email tras la compra.",
            pt="Licença digital original do Adobe Acrobat Pro: edita, converte, assina eletronicamente e protege os teus PDF a partir do computador, da web e do telemóvel. Código e instruções por email após a compra.",
            nl="Originele digitale licentie van Adobe Acrobat Pro: bewerk, converteer, onderteken elektronisch en beveilig uw PDF’s vanaf de computer, het web en de telefoon. Code en instructies per e-mail na aankoop.",
        ),
        "features_title": L(
            it="Tutto il PDF, in un solo strumento",
            en="Everything PDF, in one tool",
            fr="Tout le PDF, dans un seul outil",
            de="Alles rund um PDF in einem Werkzeug",
            es="Todo el PDF, en una sola herramienta",
            pt="Tudo o que precisas em PDF, numa só ferramenta",
            nl="Alles wat u nodig hebt voor PDF, in één tool",
        ),
        "keypoints": L(
            it=["Modifica testo e immagini nel PDF", "Firma elettronica inclusa (Acrobat Sign)", "Converti da/verso Word, Excel, PowerPoint", "Windows, Mac, web e app mobile"],
            en=["Edit text and images in the PDF", "E-signature included (Acrobat Sign)", "Convert to/from Word, Excel, PowerPoint", "Windows, Mac, web and mobile app"],
            fr=["Modifiez texte et images dans le PDF", "Signature électronique incluse (Acrobat Sign)", "Convertissez vers/depuis Word, Excel, PowerPoint", "Windows, Mac, web et app mobile"],
            de=["Text und Bilder im PDF bearbeiten", "E-Signatur inklusive (Acrobat Sign)", "Konvertierung zu/von Word, Excel, PowerPoint", "Windows, Mac, Web und Mobil-App"],
            es=["Edita texto e imágenes en el PDF", "Firma electrónica incluida (Acrobat Sign)", "Convierte desde/hacia Word, Excel, PowerPoint", "Windows, Mac, web y app móvil"],
            pt=["Edita texto e imagens no PDF", "Assinatura eletrónica incluída (Acrobat Sign)", "Converte de/para Word, Excel, PowerPoint", "Windows, Mac, web e app móvel"],
            nl=["Tekst en afbeeldingen in de PDF bewerken", "Elektronische ondertekening inbegrepen (Acrobat Sign)", "Converteren van/naar Word, Excel, PowerPoint", "Windows, Mac, web en mobiele app"],
        ),
        "features": {
            "it": [
                ("c8", "blue", "Editing", "Modifica PDF come un documento", "Cambia testo, immagini e impaginazione direttamente nel file PDF, senza dover ricreare il documento da zero."),
                ("c4", "teal", "Firma", "Firma elettronica inclusa", "Invia, firma e fai firmare documenti con Acrobat Sign, incluso nell'abbonamento."),
                ("c4", "purple", "Conversione", "Da e verso Office", "Converti PDF in Word, Excel o PowerPoint mantenendo l'impaginazione originale, e viceversa."),
                ("c4", None, "OCR", "Testo da scansioni", "Riconoscimento ottico dei caratteri: rendi modificabili e ricercabili anche i PDF scansionati."),
                ("c4", None, "Protezione", "Password e redazione", "Proteggi i file con password e rimuovi in modo permanente le informazioni sensibili prima di condividerli."),
                ("c4", "dark", "Dispositivi", "Ovunque tu lavori", "App desktop Windows/Mac, editor web e app mobile: il documento resta sincronizzato tra i dispositivi."),
            ],
            "en": [
                ("c8", "blue", "Editing", "Edit a PDF like a document", "Change text, images and layout directly in the PDF, without recreating the document from scratch."),
                ("c4", "teal", "Signing", "E-signature included", "Send, sign and collect signatures with Acrobat Sign, included in the subscription."),
                ("c4", "purple", "Conversion", "To and from Office", "Convert PDF to Word, Excel or PowerPoint keeping the original layout, and back again."),
                ("c4", None, "OCR", "Text from scans", "Optical character recognition makes scanned PDFs editable and searchable."),
                ("c4", None, "Protection", "Passwords and redaction", "Protect files with a password and permanently remove sensitive information before sharing."),
                ("c4", "dark", "Devices", "Wherever you work", "Windows/Mac desktop app, web editor and mobile app: your document stays in sync across devices."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Modifiez un PDF comme un document", "Changez texte, images et mise en page directement dans le PDF, sans recréer le document."),
                ("c4", "teal", "Signature", "Signature électronique incluse", "Envoyez, signez et faites signer des documents avec Acrobat Sign, inclus dans l'abonnement."),
                ("c4", "purple", "Conversion", "Vers et depuis Office", "Convertissez un PDF en Word, Excel ou PowerPoint en conservant la mise en page, et inversement."),
                ("c4", None, "OCR", "Texte depuis un scan", "La reconnaissance optique rend les PDF scannés modifiables et consultables."),
                ("c4", None, "Protection", "Mots de passe et caviardage", "Protégez vos fichiers par mot de passe et supprimez définitivement les informations sensibles avant partage."),
                ("c4", "dark", "Appareils", "Partout où vous travaillez", "App bureau Windows/Mac, éditeur web et app mobile : le document reste synchronisé entre appareils."),
            ],
            "de": [
                ("c8", "blue", "Bearbeitung", "PDF wie ein Dokument bearbeiten", "Text, Bilder und Layout direkt im PDF ändern, ohne das Dokument neu zu erstellen."),
                ("c4", "teal", "Signatur", "E-Signatur inklusive", "Dokumente mit Acrobat Sign versenden, signieren und signieren lassen — im Abo enthalten."),
                ("c4", "purple", "Konvertierung", "Zu und von Office", "PDF in Word, Excel oder PowerPoint umwandeln (Layout bleibt erhalten) und umgekehrt."),
                ("c4", None, "OCR", "Text aus Scans", "Texterkennung macht gescannte PDFs bearbeitbar und durchsuchbar."),
                ("c4", None, "Schutz", "Passwort und Schwärzung", "Dateien mit Passwort schützen und sensible Informationen vor dem Teilen dauerhaft entfernen."),
                ("c4", "dark", "Geräte", "Überall weiterarbeiten", "Desktop-App für Windows/Mac, Web-Editor und Mobil-App: das Dokument bleibt geräteübergreifend synchron."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Edita un PDF como un documento", "Cambia texto, imágenes y maquetación directamente en el PDF, sin recrear el documento."),
                ("c4", "teal", "Firma", "Firma electrónica incluida", "Envía, firma y recoge firmas con Acrobat Sign, incluido en la suscripción."),
                ("c4", "purple", "Conversión", "Hacia y desde Office", "Convierte un PDF a Word, Excel o PowerPoint conservando el diseño, y viceversa."),
                ("c4", None, "OCR", "Texto desde escaneos", "El reconocimiento óptico hace que los PDF escaneados sean editables y buscables."),
                ("c4", None, "Protección", "Contraseñas y redacción", "Protege los archivos con contraseña y elimina de forma permanente la información sensible antes de compartir."),
                ("c4", "dark", "Dispositivos", "Trabaja donde quieras", "App de escritorio Windows/Mac, editor web y app móvil: el documento se mantiene sincronizado entre dispositivos."),
            ],
            "pt": [
                ("c8", "blue", "Edição", "Edita o PDF como um documento", "Altera texto, imagens e paginação diretamente no ficheiro PDF, sem teres de recriar o documento do zero."),
                ("c4", "teal", "Assinatura", "Assinatura eletrónica incluída", "Envia, assina e faz assinar documentos com o Acrobat Sign, incluído na subscrição."),
                ("c4", "purple", "Conversão", "De e para o Office", "Converte PDF em Word, Excel ou PowerPoint mantendo a paginação original, e vice-versa."),
                ("c4", None, "OCR", "Texto a partir de digitalizações", "Reconhecimento ótico de caracteres: torna editáveis e pesquisáveis também os PDF digitalizados."),
                ("c4", None, "Proteção", "Palavra-passe e redação", "Protege os ficheiros com palavra-passe e remove de forma permanente informações sensíveis antes de os partilhares."),
                ("c4", "dark", "Dispositivos", "Onde quer que trabalhes", "App de computador Windows/Mac, editor web e app móvel: o documento mantém-se sincronizado entre dispositivos."),
            ],
        },
        "steps": {
            "it": [
                ("Ordine e pagamento", "Aggiungi il prodotto al carrello e completa il pagamento con i metodi disponibili."),
                ("Consegna digitale", "Ricevi via email il codice di attivazione e le istruzioni, di norma entro pochi minuti dal pagamento."),
                ("Attivazione", "Riscatta il codice sul tuo account Adobe e installa Acrobat da adobe.com o direttamente dall'app."),
            ],
            "en": [
                ("Order and payment", "Add the product to your cart and complete checkout with the available methods."),
                ("Digital delivery", "You receive the activation code and instructions by email, usually within minutes of payment."),
                ("Activation", "Redeem the code on your Adobe account and install Acrobat from adobe.com or directly from the app."),
            ],
            "fr": [
                ("Commande et paiement", "Ajoutez le produit au panier et finalisez le paiement avec les méthodes disponibles."),
                ("Livraison numérique", "Vous recevez le code d'activation et les instructions par e-mail, généralement en quelques minutes."),
                ("Activation", "Utilisez le code sur votre compte Adobe et installez Acrobat depuis adobe.com ou l'application."),
            ],
            "de": [
                ("Bestellung und Zahlung", "Produkt in den Warenkorb legen und die Zahlung mit den verfügbaren Methoden abschließen."),
                ("Digitale Lieferung", "Sie erhalten den Aktivierungscode und die Anleitung per E-Mail, meist innerhalb weniger Minuten."),
                ("Aktivierung", "Code im Adobe-Konto einlösen und Acrobat über adobe.com oder direkt aus der App installieren."),
            ],
            "es": [
                ("Pedido y pago", "Añade el producto al carrito y completa el pago con los métodos disponibles."),
                ("Entrega digital", "Recibes el código de activación y las instrucciones por email, normalmente en pocos minutos."),
                ("Activación", "Canjea el código en tu cuenta Adobe e instala Acrobat desde adobe.com o directamente desde la app."),
            ],
            "pt": [
                ("Encomenda e pagamento", "Adiciona o produto ao carrinho e conclui o pagamento com os métodos disponíveis."),
                ("Entrega digital", "Recebes por email o código de ativação e as instruções, normalmente em poucos minutos após o pagamento."),
                ("Ativação", "Resgata o código na tua conta Adobe e instala o Acrobat a partir de adobe.com ou diretamente da app."),
            ],
        },
        "specs": {
            "it": [
                ("Sistema operativo", "Windows 10/11 o macOS in versione supportata da Adobe."),
                ("Connessione", "Internet richiesta per l'attivazione e per le funzioni cloud/firma."),
                ("Account", "Un account Adobe (gratuito) per riscattare il codice e sincronizzare i documenti."),
                ("Compatibilità", "Import/export tra PDF e i formati Word, Excel, PowerPoint e immagine più comuni."),
            ],
            "en": [
                ("Operating system", "Windows 10/11 or a macOS version supported by Adobe."),
                ("Connection", "Internet required for activation and for cloud/signing features."),
                ("Account", "A free Adobe account to redeem the code and sync documents."),
                ("Compatibility", "Import/export between PDF and the most common Word, Excel, PowerPoint and image formats."),
            ],
            "fr": [
                ("Système d'exploitation", "Windows 10/11 ou une version de macOS prise en charge par Adobe."),
                ("Connexion", "Internet requis pour l'activation et les fonctions cloud/signature."),
                ("Compte", "Un compte Adobe gratuit pour utiliser le code et synchroniser les documents."),
                ("Compatibilité", "Import/export entre PDF et les formats Word, Excel, PowerPoint et image les plus courants."),
            ],
            "de": [
                ("Betriebssystem", "Windows 10/11 oder eine von Adobe unterstützte macOS-Version."),
                ("Verbindung", "Internet erforderlich für Aktivierung und Cloud-/Signaturfunktionen."),
                ("Konto", "Ein kostenloses Adobe-Konto zum Einlösen des Codes und Synchronisieren der Dokumente."),
                ("Kompatibilität", "Import/Export zwischen PDF und den gängigsten Word-, Excel-, PowerPoint- und Bildformaten."),
            ],
            "es": [
                ("Sistema operativo", "Windows 10/11 o una versión de macOS compatible con Adobe."),
                ("Conexión", "Internet necesario para la activación y las funciones de nube/firma."),
                ("Cuenta", "Una cuenta Adobe gratuita para canjear el código y sincronizar documentos."),
                ("Compatibilidad", "Importación/exportación entre PDF y los formatos Word, Excel, PowerPoint e imagen más comunes."),
            ],
            "pt": [
                ("Sistema operativo", "Windows 10/11 ou macOS em versão suportada pela Adobe."),
                ("Ligação", "Internet necessária para a ativação e para as funções cloud/assinatura."),
                ("Conta", "Uma conta Adobe (gratuita) para resgatar o código e sincronizar os documentos."),
                ("Compatibilidade", "Importação/exportação entre PDF e os formatos Word, Excel, PowerPoint e imagem mais comuns."),
            ],
        },
        "faq": {
            "it": [
                ("È un abbonamento o una licenza perpetua?", "Adobe Acrobat Pro è distribuito in abbonamento; la durata è indicata nella scheda prodotto."),
                ("Funziona su Mac oltre che su Windows?", "Sì, oltre all'app desktop Windows/Mac puoi lavorare dall'editor web e dall'app mobile."),
                ("La firma elettronica è inclusa nel prezzo?", "Sì, Acrobat Sign per l'invio e la raccolta di firme è incluso nell'abbonamento Pro."),
                ("Come ricevo e attivo la licenza?", "Riceverai via email il codice: lo riscatti sul tuo account Adobe e installi l'app da adobe.com."),
                ("Posso modificare PDF scansionati?", "Sì, il riconoscimento ottico (OCR) converte il testo delle scansioni in testo modificabile e ricercabile."),
            ],
            "en": [
                ("Is it a subscription or a perpetual licence?", "Adobe Acrobat Pro is sold as a subscription; the term is shown on the product page."),
                ("Does it work on Mac as well as Windows?", "Yes — besides the Windows/Mac desktop app you can also work from the web editor and mobile app."),
                ("Is e-signature included in the price?", "Yes, Acrobat Sign for sending and collecting signatures is included in the Pro subscription."),
                ("How do I receive and activate the licence?", "You'll receive the code by email: redeem it on your Adobe account and install the app from adobe.com."),
                ("Can I edit scanned PDFs?", "Yes, optical character recognition (OCR) turns scanned text into editable, searchable text."),
            ],
            "fr": [
                ("Est-ce un abonnement ou une licence perpétuelle ?", "Adobe Acrobat Pro est vendu en abonnement ; la durée est indiquée sur la fiche produit."),
                ("Fonctionne-t-il sur Mac comme sur Windows ?", "Oui, en plus de l'app bureau Windows/Mac vous pouvez travailler depuis l'éditeur web et l'app mobile."),
                ("La signature électronique est-elle incluse ?", "Oui, Acrobat Sign pour l'envoi et la collecte de signatures est inclus dans l'abonnement Pro."),
                ("Comment je reçois et active la licence ?", "Vous recevez le code par e-mail : utilisez-le sur votre compte Adobe et installez l'app depuis adobe.com."),
                ("Puis-je modifier des PDF scannés ?", "Oui, la reconnaissance optique (OCR) transforme le texte scanné en texte modifiable et consultable."),
            ],
            "de": [
                ("Ist das ein Abo oder eine Dauerlizenz?", "Adobe Acrobat Pro wird im Abo verkauft; die Laufzeit steht auf der Produktseite."),
                ("Funktioniert es auf Mac genauso wie auf Windows?", "Ja, neben der Desktop-App für Windows/Mac können Sie auch im Web-Editor und in der Mobil-App arbeiten."),
                ("Ist die E-Signatur im Preis enthalten?", "Ja, Acrobat Sign zum Versenden und Einholen von Signaturen ist im Pro-Abo enthalten."),
                ("Wie erhalte und aktiviere ich die Lizenz?", "Sie erhalten den Code per E-Mail, lösen ihn in Ihrem Adobe-Konto ein und installieren die App über adobe.com."),
                ("Kann ich gescannte PDFs bearbeiten?", "Ja, die Texterkennung (OCR) macht gescannten Text bearbeitbar und durchsuchbar."),
            ],
            "es": [
                ("¿Es una suscripción o una licencia perpetua?", "Adobe Acrobat Pro se vende por suscripción; la duración se indica en la ficha del producto."),
                ("¿Funciona en Mac además de en Windows?", "Sí, además de la app de escritorio Windows/Mac puedes trabajar desde el editor web y la app móvil."),
                ("¿La firma electrónica está incluida en el precio?", "Sí, Acrobat Sign para enviar y recoger firmas está incluido en la suscripción Pro."),
                ("¿Cómo recibo y activo la licencia?", "Recibirás el código por email: lo canjeas en tu cuenta Adobe e instalas la app desde adobe.com."),
                ("¿Puedo editar PDF escaneados?", "Sí, el reconocimiento óptico (OCR) convierte el texto escaneado en texto editable y buscable."),
            ],
            "pt": [
                ("É uma subscrição ou uma licença perpétua?", "O Adobe Acrobat Pro é vendido por subscrição; a duração está indicada na ficha do produto."),
                ("Funciona em Mac além de Windows?", "Sim, além da app de computador Windows/Mac podes trabalhar a partir do editor web e da app móvel."),
                ("A assinatura eletrónica está incluída no preço?", "Sim, o Acrobat Sign para enviar e recolher assinaturas está incluído na subscrição Pro."),
                ("Como recebo e ativo a licença?", "Vais receber o código por email: resgata-o na tua conta Adobe e instala a app a partir de adobe.com."),
                ("Posso editar PDF digitalizados?", "Sim, o reconhecimento ótico de caracteres (OCR) converte o texto digitalizado em texto editável e pesquisável."),
            ],
        },
    },
    "adobe-acrobat-standard": {
        "seo_title": L(
            it="Adobe Acrobat Standard — 2 dispositivi — Eurolicenze",
            en="Adobe Acrobat Standard — 2 devices — Eurolicenze",
            fr="Adobe Acrobat Standard — 2 appareils — Eurolicenze",
            de="Adobe Acrobat Standard — 2 Geräte — Eurolicenze",
            es="Adobe Acrobat Standard — 2 dispositivos — Eurolicenze",
            pt="Adobe Acrobat Standard — 2 dispositivos — Eurolicenze",
            nl="Adobe Acrobat Standard — 2 apparaten — Eurolicenze",
        ),
        "title_html": L(
            it='Adobe Acrobat <span>Standard</span>',
            en='Adobe Acrobat <span>Standard</span>',
            fr='Adobe Acrobat <span>Standard</span>',
            de='Adobe Acrobat <span>Standard</span>',
            es='Adobe Acrobat <span>Standard</span>',
            pt='Adobe Acrobat <span>Standard</span>',
            nl='Adobe Acrobat <span>Standard</span>',
        ),
        "eyebrow": L(
            it="Abbonamento · editing e firma PDF",
            en="Subscription · PDF editing and signing",
            fr="Abonnement · édition et signature PDF",
            de="Abonnement · PDF bearbeiten und signieren",
            es="Suscripción · edición y firma de PDF",
            pt="Subscrição · edição e assinatura de PDF",
            nl="Abonnement · PDF bewerken en ondertekenen",
        ),
        "desc": L(
            it="Licenza digitale originale di Adobe Acrobat Standard: modifica, organizza, converti e firma i tuoi PDF con lo strumento ufficiale Adobe. Codice e istruzioni via email dopo l'acquisto.",
            en="Genuine digital licence for Adobe Acrobat Standard: edit, organise, convert and sign your PDFs with Adobe's official tool. Code and instructions by email after purchase.",
            fr="Licence numérique originale d'Adobe Acrobat Standard : modifiez, organisez, convertissez et signez vos PDF avec l'outil officiel Adobe. Code et instructions par e-mail après l'achat.",
            de="Originale digitale Lizenz für Adobe Acrobat Standard: PDFs mit dem offiziellen Adobe-Tool bearbeiten, organisieren, konvertieren und signieren. Code und Anleitung per E-Mail nach dem Kauf.",
            es="Licencia digital original de Adobe Acrobat Standard: edita, organiza, convierte y firma tus PDF con la herramienta oficial de Adobe. Código e instrucciones por email tras la compra.",
            pt="Licença digital original do Adobe Acrobat Standard: edita, organiza, converte e assina os teus PDF com a ferramenta oficial da Adobe. Código e instruções por email após a compra.",
            nl="Originele digitale licentie van Adobe Acrobat Standard: bewerk, organiseer, converteer en onderteken uw PDF’s met de officiële Adobe-tool. Code en instructies per e-mail na aankoop.",
        ),
        "features_title": L(
            it="Le funzioni PDF essenziali, senza complicazioni",
            en="Essential PDF tools, no complications",
            fr="Les fonctions PDF essentielles, sans complications",
            de="Die wichtigsten PDF-Funktionen, ganz unkompliziert",
            es="Las funciones esenciales de PDF, sin complicaciones",
            pt="As funções essenciais de PDF, sem complicações",
            nl="De essentiële PDF-functies, zonder extra’s",
        ),
        "keypoints": L(
            it=["Modifica testo e organizza le pagine", "Firma elettronica inclusa", "Converti PDF da e verso Office", "Licenza digitale originale Adobe"],
            en=["Edit text and organise pages", "E-signature included", "Convert PDF to and from Office", "Genuine Adobe digital licence"],
            fr=["Modifiez le texte et organisez les pages", "Signature électronique incluse", "Convertissez le PDF vers/depuis Office", "Licence numérique Adobe originale"],
            de=["Text bearbeiten und Seiten organisieren", "E-Signatur inklusive", "PDF zu/von Office konvertieren", "Originale digitale Adobe-Lizenz"],
            es=["Edita texto y organiza páginas", "Firma electrónica incluida", "Convierte PDF hacia y desde Office", "Licencia digital original de Adobe"],
            pt=["Edita texto e organiza páginas", "Assinatura eletrónica incluída", "Converte PDF de e para Office", "Licença digital original Adobe"],
            nl=["Tekst bewerken en pagina’s organiseren", "Elektronische ondertekening inbegrepen", "PDF van en naar Office converteren", "Originele digitale Adobe-licentie"],
        ),
        "features": {
            "it": [
                ("c8", "blue", "Editing", "Modifica e organizza PDF", "Correggi il testo, riordina, ruota ed elimina pagine direttamente nel file PDF."),
                ("c4", "teal", "Firma", "Firma elettronica inclusa", "Invia e firma documenti in pochi clic, senza stampare né scansionare."),
                ("c4", "purple", "Conversione", "Da e verso Office", "Trasforma un PDF in Word o Excel modificabile, e viceversa, mantenendo l'impaginazione."),
                ("c4", None, "Creazione", "Crea PDF da qualsiasi file", "Genera PDF da documenti Office, immagini o pagine web con un clic."),
                ("c4", None, "Moduli", "Compila e firma moduli", "Compila moduli PDF a schermo ed esporta i dati raccolti."),
                ("c4", "dark", "Licenza", "Originale, via account Adobe", "Attivazione ufficiale sul tuo account Adobe, con aggiornamenti inclusi."),
            ],
            "en": [
                ("c8", "blue", "Editing", "Edit and organise PDFs", "Fix text, reorder, rotate and delete pages directly in the PDF file."),
                ("c4", "teal", "Signing", "E-signature included", "Send and sign documents in a few clicks, no printing or scanning."),
                ("c4", "purple", "Conversion", "To and from Office", "Turn a PDF into an editable Word or Excel file and back, keeping the layout."),
                ("c4", None, "Creation", "Create PDFs from any file", "Generate PDFs from Office documents, images or web pages in one click."),
                ("c4", None, "Forms", "Fill and sign forms", "Fill in PDF forms on screen and export the collected data."),
                ("c4", "dark", "Licence", "Genuine, via Adobe account", "Official activation on your Adobe account, updates included."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Modifiez et organisez vos PDF", "Corrigez le texte, réorganisez, pivotez et supprimez des pages directement dans le PDF."),
                ("c4", "teal", "Signature", "Signature électronique incluse", "Envoyez et signez des documents en quelques clics, sans impression ni scan."),
                ("c4", "purple", "Conversion", "Vers et depuis Office", "Transformez un PDF en Word ou Excel modifiable, et inversement, en conservant la mise en page."),
                ("c4", None, "Création", "Créez des PDF depuis tout fichier", "Générez des PDF à partir de documents Office, d'images ou de pages web en un clic."),
                ("c4", None, "Formulaires", "Remplissez et signez", "Remplissez des formulaires PDF à l'écran et exportez les données recueillies."),
                ("c4", "dark", "Licence", "Originale, via compte Adobe", "Activation officielle sur votre compte Adobe, mises à jour incluses."),
            ],
            "de": [
                ("c8", "blue", "Bearbeitung", "PDFs bearbeiten und organisieren", "Text korrigieren, Seiten neu anordnen, drehen und löschen — direkt im PDF."),
                ("c4", "teal", "Signatur", "E-Signatur inklusive", "Dokumente in wenigen Klicks versenden und signieren, ohne Drucken oder Scannen."),
                ("c4", "purple", "Konvertierung", "Zu und von Office", "PDF in ein bearbeitbares Word- oder Excel-Dokument umwandeln und zurück — Layout bleibt erhalten."),
                ("c4", None, "Erstellung", "PDFs aus jeder Datei", "PDFs aus Office-Dokumenten, Bildern oder Webseiten mit einem Klick erstellen."),
                ("c4", None, "Formulare", "Ausfüllen und signieren", "PDF-Formulare am Bildschirm ausfüllen und die erfassten Daten exportieren."),
                ("c4", "dark", "Lizenz", "Original, über Adobe-Konto", "Offizielle Aktivierung im Adobe-Konto, inklusive Updates."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Edita y organiza PDF", "Corrige el texto, reordena, gira y elimina páginas directamente en el PDF."),
                ("c4", "teal", "Firma", "Firma electrónica incluida", "Envía y firma documentos en pocos clics, sin imprimir ni escanear."),
                ("c4", "purple", "Conversión", "Hacia y desde Office", "Convierte un PDF en un Word o Excel editable, y viceversa, conservando el diseño."),
                ("c4", None, "Creación", "Crea PDF desde cualquier archivo", "Genera PDF a partir de documentos Office, imágenes o páginas web con un clic."),
                ("c4", None, "Formularios", "Rellena y firma", "Rellena formularios PDF en pantalla y exporta los datos recogidos."),
                ("c4", "dark", "Licencia", "Original, mediante cuenta Adobe", "Activación oficial en tu cuenta Adobe, con actualizaciones incluidas."),
            ],
            "pt": [
                ("c8", "blue", "Edição", "Edita e organiza PDF", "Corrige o texto, reordena, roda e elimina páginas diretamente no ficheiro PDF."),
                ("c4", "teal", "Assinatura", "Assinatura eletrónica incluída", "Envia e assina documentos em poucos cliques, sem imprimir nem digitalizar."),
                ("c4", "purple", "Conversão", "De e para o Office", "Transforma um PDF num Word ou Excel editável, e vice-versa, mantendo a paginação."),
                ("c4", None, "Criação", "Cria PDF a partir de qualquer ficheiro", "Gera PDF a partir de documentos Office, imagens ou páginas web com um clique."),
                ("c4", None, "Formulários", "Preenche e assina formulários", "Preenche formulários PDF no ecrã e exporta os dados recolhidos."),
                ("c4", "dark", "Licença", "Original, via conta Adobe", "Ativação oficial na tua conta Adobe, com atualizações incluídas."),
            ],
        },
        "steps": {
            "it": [
                ("Ordine e pagamento", "Aggiungi il prodotto al carrello e completa il pagamento con i metodi disponibili."),
                ("Consegna digitale", "Ricevi via email il codice di attivazione e le istruzioni, di norma entro pochi minuti dal pagamento."),
                ("Attivazione", "Riscatta il codice sul tuo account Adobe e installa Acrobat da adobe.com."),
            ],
            "en": [
                ("Order and payment", "Add the product to your cart and complete checkout with the available methods."),
                ("Digital delivery", "You receive the activation code and instructions by email, usually within minutes of payment."),
                ("Activation", "Redeem the code on your Adobe account and install Acrobat from adobe.com."),
            ],
            "fr": [
                ("Commande et paiement", "Ajoutez le produit au panier et finalisez le paiement avec les méthodes disponibles."),
                ("Livraison numérique", "Vous recevez le code d'activation et les instructions par e-mail, généralement en quelques minutes."),
                ("Activation", "Utilisez le code sur votre compte Adobe et installez Acrobat depuis adobe.com."),
            ],
            "de": [
                ("Bestellung und Zahlung", "Produkt in den Warenkorb legen und die Zahlung mit den verfügbaren Methoden abschließen."),
                ("Digitale Lieferung", "Sie erhalten den Aktivierungscode und die Anleitung per E-Mail, meist innerhalb weniger Minuten."),
                ("Aktivierung", "Code im Adobe-Konto einlösen und Acrobat über adobe.com installieren."),
            ],
            "es": [
                ("Pedido y pago", "Añade el producto al carrito y completa el pago con los métodos disponibles."),
                ("Entrega digital", "Recibes el código de activación y las instrucciones por email, normalmente en pocos minutos."),
                ("Activación", "Canjea el código en tu cuenta Adobe e instala Acrobat desde adobe.com."),
            ],
            "pt": [
                ("Encomenda e pagamento", "Adiciona o produto ao carrinho e conclui o pagamento com os métodos disponíveis."),
                ("Entrega digital", "Recebes por email o código de ativação e as instruções, normalmente em poucos minutos após o pagamento."),
                ("Ativação", "Resgata o código na tua conta Adobe e instala o Acrobat a partir de adobe.com."),
            ],
        },
        "specs": {
            "it": [
                ("Sistema operativo", "Windows 10/11 in versione supportata da Adobe."),
                ("Connessione", "Internet richiesta per l'attivazione e per le funzioni cloud/firma."),
                ("Account", "Un account Adobe (gratuito) per riscattare il codice e sincronizzare i documenti."),
                ("Compatibilità", "Import/export tra PDF e i formati Word, Excel, PowerPoint e immagine più comuni."),
            ],
            "en": [
                ("Operating system", "Windows 10/11 in a version supported by Adobe."),
                ("Connection", "Internet required for activation and for cloud/signing features."),
                ("Account", "A free Adobe account to redeem the code and sync documents."),
                ("Compatibility", "Import/export between PDF and the most common Word, Excel, PowerPoint and image formats."),
            ],
            "fr": [
                ("Système d'exploitation", "Windows 10/11 dans une version prise en charge par Adobe."),
                ("Connexion", "Internet requis pour l'activation et les fonctions cloud/signature."),
                ("Compte", "Un compte Adobe gratuit pour utiliser le code et synchroniser les documents."),
                ("Compatibilité", "Import/export entre PDF et les formats Word, Excel, PowerPoint et image les plus courants."),
            ],
            "de": [
                ("Betriebssystem", "Windows 10/11 in einer von Adobe unterstützten Version."),
                ("Verbindung", "Internet erforderlich für Aktivierung und Cloud-/Signaturfunktionen."),
                ("Konto", "Ein kostenloses Adobe-Konto zum Einlösen des Codes und Synchronisieren der Dokumente."),
                ("Kompatibilität", "Import/Export zwischen PDF und den gängigsten Word-, Excel-, PowerPoint- und Bildformaten."),
            ],
            "es": [
                ("Sistema operativo", "Windows 10/11 en una versión compatible con Adobe."),
                ("Conexión", "Internet necesario para la activación y las funciones de nube/firma."),
                ("Cuenta", "Una cuenta Adobe gratuita para canjear el código y sincronizar documentos."),
                ("Compatibilidad", "Importación/exportación entre PDF y los formatos Word, Excel, PowerPoint e imagen más comunes."),
            ],
            "pt": [
                ("Sistema operativo", "Windows 10/11 numa versão suportada pela Adobe."),
                ("Ligação", "Internet necessária para a ativação e para as funções cloud/assinatura."),
                ("Conta", "Uma conta Adobe (gratuita) para resgatar o código e sincronizar os documentos."),
                ("Compatibilidade", "Importação/exportação entre PDF e os formatos Word, Excel, PowerPoint e imagem mais comuns."),
            ],
        },
        "faq": {
            "it": [
                ("Che differenza c'è con Acrobat Pro?", "Standard copre editing, organizzazione, conversione e firma; Pro aggiunge strumenti avanzati come redazione e confronto documenti."),
                ("È un abbonamento?", "Sì, la durata dell'abbonamento è indicata nella scheda prodotto."),
                ("La firma elettronica è inclusa?", "Sì, puoi inviare e firmare documenti direttamente dall'app."),
                ("Come ricevo e attivo la licenza?", "Riceverai via email il codice: lo riscatti sul tuo account Adobe e installi l'app da adobe.com."),
                ("Posso convertire un PDF in Word?", "Sì, la conversione verso Word, Excel e PowerPoint (e viceversa) è inclusa."),
            ],
            "en": [
                ("What's the difference from Acrobat Pro?", "Standard covers editing, organising, converting and signing; Pro adds advanced tools like redaction and document comparison."),
                ("Is it a subscription?", "Yes, the subscription term is shown on the product page."),
                ("Is e-signature included?", "Yes, you can send and sign documents directly from the app."),
                ("How do I receive and activate the licence?", "You'll receive the code by email: redeem it on your Adobe account and install the app from adobe.com."),
                ("Can I convert a PDF to Word?", "Yes, conversion to Word, Excel and PowerPoint (and back) is included."),
            ],
            "fr": [
                ("Quelle différence avec Acrobat Pro ?", "Standard couvre l'édition, l'organisation, la conversion et la signature ; Pro ajoute des outils avancés comme le caviardage et la comparaison de documents."),
                ("Est-ce un abonnement ?", "Oui, la durée de l'abonnement est indiquée sur la fiche produit."),
                ("La signature électronique est-elle incluse ?", "Oui, vous pouvez envoyer et signer des documents directement depuis l'app."),
                ("Comment je reçois et active la licence ?", "Vous recevez le code par e-mail : utilisez-le sur votre compte Adobe et installez l'app depuis adobe.com."),
                ("Puis-je convertir un PDF en Word ?", "Oui, la conversion vers Word, Excel et PowerPoint (et inversement) est incluse."),
            ],
            "de": [
                ("Was ist der Unterschied zu Acrobat Pro?", "Standard deckt Bearbeiten, Organisieren, Konvertieren und Signieren ab; Pro bietet zusätzlich erweiterte Tools wie Schwärzung und Dokumentenvergleich."),
                ("Ist das ein Abo?", "Ja, die Laufzeit des Abos steht auf der Produktseite."),
                ("Ist die E-Signatur enthalten?", "Ja, Sie können Dokumente direkt aus der App versenden und signieren."),
                ("Wie erhalte und aktiviere ich die Lizenz?", "Sie erhalten den Code per E-Mail, lösen ihn in Ihrem Adobe-Konto ein und installieren die App über adobe.com."),
                ("Kann ich ein PDF in Word umwandeln?", "Ja, die Konvertierung zu Word, Excel und PowerPoint (und zurück) ist enthalten."),
            ],
            "es": [
                ("¿Qué diferencia hay con Acrobat Pro?", "Standard cubre edición, organización, conversión y firma; Pro añade herramientas avanzadas como redacción y comparación de documentos."),
                ("¿Es una suscripción?", "Sí, la duración de la suscripción se indica en la ficha del producto."),
                ("¿La firma electrónica está incluida?", "Sí, puedes enviar y firmar documentos directamente desde la app."),
                ("¿Cómo recibo y activo la licencia?", "Recibirás el código por email: lo canjeas en tu cuenta Adobe e instalas la app desde adobe.com."),
                ("¿Puedo convertir un PDF a Word?", "Sí, la conversión a Word, Excel y PowerPoint (y viceversa) está incluida."),
            ],
            "pt": [
                ("Qual é a diferença em relação ao Acrobat Pro?", "O Standard cobre edição, organização, conversão e assinatura; o Pro adiciona ferramentas avançadas como redação e comparação de documentos."),
                ("É uma subscrição?", "Sim, a duração da subscrição está indicada na ficha do produto."),
                ("A assinatura eletrónica está incluída?", "Sim, podes enviar e assinar documentos diretamente pela app."),
                ("Como recebo e ativo a licença?", "Vais receber o código por email: resgata-o na tua conta Adobe e instala a app a partir de adobe.com."),
                ("Posso converter um PDF para Word?", "Sim, a conversão para Word, Excel e PowerPoint (e vice-versa) está incluída."),
            ],
        },
    },
    "coreldraw-2024": {
        "title_html": L(
            it='CorelDRAW <span>Graphics Suite 2024</span>',
            en='CorelDRAW <span>Graphics Suite 2024</span>',
            fr='CorelDRAW <span>Graphics Suite 2024</span>',
            de='CorelDRAW <span>Graphics Suite 2024</span>',
            es='CorelDRAW <span>Graphics Suite 2024</span>',
            pt='CorelDRAW <span>Graphics Suite 2024</span>',
            nl='CorelDRAW <span>Graphics Suite 2024</span>',
        ),
        "eyebrow": L(
            it="Licenza · illustrazione vettoriale e grafica",
            en="Licence · vector illustration and graphic design",
            fr="Licence · illustration vectorielle et design graphique",
            de="Lizenz · Vektorillustration und Grafikdesign",
            es="Licencia · ilustración vectorial y diseño gráfico",
            pt="Licença · ilustração vetorial e design gráfico",
            nl="Licentie · vectorillustratie en grafisch ontwerp",
        ),
        "desc": L(
            it="Licenza digitale originale di CorelDRAW Graphics Suite 2024: illustrazione vettoriale, editing fotografico e impaginazione in un'unica suite per Windows e Mac. Codice e istruzioni via email dopo l'acquisto.",
            en="Genuine digital licence for CorelDRAW Graphics Suite 2024: vector illustration, photo editing and layout in a single suite for Windows and Mac. Code and instructions by email after purchase.",
            fr="Licence numérique originale de CorelDRAW Graphics Suite 2024 : illustration vectorielle, retouche photo et mise en page dans une seule suite pour Windows et Mac. Code et instructions par e-mail après l'achat.",
            de="Originale digitale Lizenz für CorelDRAW Graphics Suite 2024: Vektorillustration, Fotobearbeitung und Layout in einer Suite für Windows und Mac. Code und Anleitung per E-Mail nach dem Kauf.",
            es="Licencia digital original de CorelDRAW Graphics Suite 2024: ilustración vectorial, edición fotográfica y maquetación en una sola suite para Windows y Mac. Código e instrucciones por email tras la compra.",
            pt="Licença digital original do CorelDRAW Graphics Suite 2024: ilustração vetorial, edição fotográfica e paginação numa única suite para Windows e Mac. Código e instruções por email após a compra.",
            nl="Originele digitale licentie van CorelDRAW Graphics Suite 2024: vectorillustratie, fotobewerking en opmaak in één suite voor Windows en Mac. Code en instructies per e-mail na aankoop.",
        ),
        "features_title": L(
            it="Illustrazione, foto e impaginazione insieme",
            en="Illustration, photo and layout together",
            fr="Illustration, photo et mise en page réunies",
            de="Illustration, Foto und Layout in einem",
            es="Ilustración, foto y maquetación juntas",
            pt="Ilustração, foto e paginação juntas",
            nl="Illustratie, foto en opmaak samen",
        ),
        "keypoints": L(
            it=["Illustrazione vettoriale CorelDRAW", "Editing fotografico con Corel PHOTO-PAINT", "Compatibile Windows e Mac", "Import/export AI, PSD, PDF e altri formati"],
            en=["Vector illustration with CorelDRAW", "Photo editing with Corel PHOTO-PAINT", "Windows and Mac compatible", "Import/export AI, PSD, PDF and more"],
            fr=["Illustration vectorielle avec CorelDRAW", "Retouche photo avec Corel PHOTO-PAINT", "Compatible Windows et Mac", "Import/export AI, PSD, PDF et plus"],
            de=["Vektorillustration mit CorelDRAW", "Fotobearbeitung mit Corel PHOTO-PAINT", "Kompatibel mit Windows und Mac", "Import/Export AI, PSD, PDF und mehr"],
            es=["Ilustración vectorial con CorelDRAW", "Edición fotográfica con Corel PHOTO-PAINT", "Compatible con Windows y Mac", "Importa/exporta AI, PSD, PDF y más"],
            pt=["Ilustração vetorial com CorelDRAW", "Edição fotográfica com Corel PHOTO-PAINT", "Compatível com Windows e Mac", "Importa/exporta AI, PSD, PDF e mais"],
            nl=["Vectorillustratie met CorelDRAW", "Fotobewerking met Corel PHOTO-PAINT", "Compatibel met Windows en Mac", "Importeren/exporteren van AI, PSD, PDF en meer"],
        ),
        "features": {
            "it": [
                ("c8", "blue", "Vettoriale", "Illustrazione professionale", "Logo, loghi, icone e illustrazioni con gli strumenti vettoriali di CorelDRAW."),
                ("c4", "teal", "Foto", "Editing con PHOTO-PAINT", "Ritocco e composizione fotografica inclusi nella stessa suite, senza altri programmi."),
                ("c4", "purple", "Impaginazione", "Layout multipagina", "Brochure, volantini e documenti multipagina con controllo tipografico avanzato."),
                ("c4", None, "Formati", "Compatibilità estesa", "Importa ed esporta file AI, PSD, PDF e i formati grafici più diffusi."),
                ("c4", None, "Piattaforma", "Windows e Mac", "La stessa suite, con la stessa interfaccia, su entrambi i sistemi operativi."),
                ("c4", "dark", "Font", "Gestione caratteri inclusa", "Font manager per organizzare, anteprima e attivare i tipi di carattere del progetto."),
            ],
            "en": [
                ("c8", "blue", "Vector", "Professional illustration", "Logos, icons and illustrations with CorelDRAW's vector tools."),
                ("c4", "teal", "Photo", "Editing with PHOTO-PAINT", "Photo retouching and compositing included in the same suite, no extra apps."),
                ("c4", "purple", "Layout", "Multi-page layout", "Brochures, flyers and multi-page documents with advanced typography controls."),
                ("c4", None, "Formats", "Broad compatibility", "Import and export AI, PSD, PDF and the most common graphics formats."),
                ("c4", None, "Platform", "Windows and Mac", "The same suite, same interface, on both operating systems."),
                ("c4", "dark", "Fonts", "Font management included", "A font manager to organise, preview and activate the fonts for your project."),
            ],
            "fr": [
                ("c8", "blue", "Vectoriel", "Illustration professionnelle", "Logos, icônes et illustrations avec les outils vectoriels de CorelDRAW."),
                ("c4", "teal", "Photo", "Retouche avec PHOTO-PAINT", "Retouche et composition photo incluses dans la même suite, sans autre logiciel."),
                ("c4", "purple", "Mise en page", "Mise en page multipage", "Brochures, flyers et documents multipages avec un contrôle typographique avancé."),
                ("c4", None, "Formats", "Large compatibilité", "Importez et exportez des fichiers AI, PSD, PDF et les formats graphiques les plus courants."),
                ("c4", None, "Plateforme", "Windows et Mac", "La même suite, la même interface, sur les deux systèmes."),
                ("c4", "dark", "Polices", "Gestion des polices incluse", "Un gestionnaire de polices pour organiser, prévisualiser et activer les polices du projet."),
            ],
            "de": [
                ("c8", "blue", "Vektor", "Professionelle Illustration", "Logos, Icons und Illustrationen mit den Vektorwerkzeugen von CorelDRAW."),
                ("c4", "teal", "Foto", "Bearbeitung mit PHOTO-PAINT", "Fotoretusche und -komposition in derselben Suite, ohne zusätzliche Software."),
                ("c4", "purple", "Layout", "Mehrseitiges Layout", "Broschüren, Flyer und mehrseitige Dokumente mit erweiterter Typografiesteuerung."),
                ("c4", None, "Formate", "Breite Kompatibilität", "AI-, PSD-, PDF- und die gängigsten Grafikformate importieren und exportieren."),
                ("c4", None, "Plattform", "Windows und Mac", "Dieselbe Suite mit derselben Oberfläche auf beiden Betriebssystemen."),
                ("c4", "dark", "Schriften", "Schriftverwaltung inklusive", "Ein Font-Manager zum Organisieren, Ansehen und Aktivieren der Projektschriften."),
            ],
            "es": [
                ("c8", "blue", "Vectorial", "Ilustración profesional", "Logotipos, iconos e ilustraciones con las herramientas vectoriales de CorelDRAW."),
                ("c4", "teal", "Foto", "Edición con PHOTO-PAINT", "Retoque y composición fotográfica incluidos en la misma suite, sin más programas."),
                ("c4", "purple", "Maquetación", "Diseño multipágina", "Folletos, flyers y documentos multipágina con control tipográfico avanzado."),
                ("c4", None, "Formatos", "Amplia compatibilidad", "Importa y exporta archivos AI, PSD, PDF y los formatos gráficos más comunes."),
                ("c4", None, "Plataforma", "Windows y Mac", "La misma suite, con la misma interfaz, en ambos sistemas operativos."),
                ("c4", "dark", "Tipografía", "Gestión de fuentes incluida", "Un gestor de fuentes para organizar, previsualizar y activar las tipografías del proyecto."),
            ],
            "pt": [
                ("c8", "blue", "Vetorial", "Ilustração profissional", "Logótipos, ícones e ilustrações com as ferramentas vetoriais do CorelDRAW."),
                ("c4", "teal", "Foto", "Edição com PHOTO-PAINT", "Retoque e composição fotográfica incluídos na mesma suite, sem outros programas."),
                ("c4", "purple", "Paginação", "Layout multipágina", "Brochuras, folhetos e documentos multipágina com controlo tipográfico avançado."),
                ("c4", None, "Formatos", "Compatibilidade ampla", "Importa e exporta ficheiros AI, PSD, PDF e os formatos gráficos mais comuns."),
                ("c4", None, "Plataforma", "Windows e Mac", "A mesma suite, com a mesma interface, em ambos os sistemas operativos."),
                ("c4", "dark", "Fontes", "Gestão de fontes incluída", "Gestor de fontes para organizar, pré-visualizar e ativar os tipos de letra do projeto."),
            ],
        },
        "steps": {
            "it": [
                ("Ordine e pagamento", "Aggiungi il prodotto al carrello e completa il pagamento con i metodi disponibili."),
                ("Consegna digitale", "Ricevi via email il codice seriale e le istruzioni, di norma entro pochi minuti dal pagamento."),
                ("Attivazione", "Scarica l'installer dal tuo account Corel e attiva la suite con il codice ricevuto."),
            ],
            "en": [
                ("Order and payment", "Add the product to your cart and complete checkout with the available methods."),
                ("Digital delivery", "You receive the serial code and instructions by email, usually within minutes of payment."),
                ("Activation", "Download the installer from your Corel account and activate the suite with the code received."),
            ],
            "fr": [
                ("Commande et paiement", "Ajoutez le produit au panier et finalisez le paiement avec les méthodes disponibles."),
                ("Livraison numérique", "Vous recevez le numéro de série et les instructions par e-mail, généralement en quelques minutes."),
                ("Activation", "Téléchargez l'installeur depuis votre compte Corel et activez la suite avec le code reçu."),
            ],
            "de": [
                ("Bestellung und Zahlung", "Produkt in den Warenkorb legen und die Zahlung mit den verfügbaren Methoden abschließen."),
                ("Digitale Lieferung", "Sie erhalten den Seriencode und die Anleitung per E-Mail, meist innerhalb weniger Minuten."),
                ("Aktivierung", "Installationsdatei im Corel-Konto herunterladen und die Suite mit dem erhaltenen Code aktivieren."),
            ],
            "es": [
                ("Pedido y pago", "Añade el producto al carrito y completa el pago con los métodos disponibles."),
                ("Entrega digital", "Recibes el código de serie y las instrucciones por email, normalmente en pocos minutos."),
                ("Activación", "Descarga el instalador desde tu cuenta Corel y activa la suite con el código recibido."),
            ],
            "pt": [
                ("Encomenda e pagamento", "Adiciona o produto ao carrinho e conclui o pagamento com os métodos disponíveis."),
                ("Entrega digital", "Recebes por email o código de série e as instruções, normalmente em poucos minutos após o pagamento."),
                ("Ativação", "Descarrega o instalador na tua conta Corel e ativa a suite com o código recebido."),
            ],
        },
        "specs": {
            "it": [
                ("Sistema operativo", "Windows 10/11 (64-bit) o macOS in versione supportata da Corel."),
                ("Memoria (RAM)", "Almeno 4 GB, consigliati 8 GB o più per file complessi."),
                ("Spazio su disco", "Circa 2-3 GB liberi per l'installazione, secondo i componenti scelti."),
                ("Connessione", "Internet richiesta per download, attivazione e aggiornamenti."),
            ],
            "en": [
                ("Operating system", "Windows 10/11 (64-bit) or a macOS version supported by Corel."),
                ("Memory (RAM)", "At least 4 GB, 8 GB or more recommended for complex files."),
                ("Disk space", "About 2-3 GB free for the install, depending on the components chosen."),
                ("Connection", "Internet required for download, activation and updates."),
            ],
            "fr": [
                ("Système d'exploitation", "Windows 10/11 (64 bits) ou une version de macOS prise en charge par Corel."),
                ("Mémoire (RAM)", "Au moins 4 Go, 8 Go ou plus recommandés pour les fichiers complexes."),
                ("Espace disque", "Environ 2 à 3 Go libres pour l'installation, selon les composants choisis."),
                ("Connexion", "Internet requis pour le téléchargement, l'activation et les mises à jour."),
            ],
            "de": [
                ("Betriebssystem", "Windows 10/11 (64-Bit) oder eine von Corel unterstützte macOS-Version."),
                ("Arbeitsspeicher (RAM)", "Mindestens 4 GB, für komplexe Dateien 8 GB oder mehr empfohlen."),
                ("Speicherplatz", "Etwa 2-3 GB frei für die Installation, je nach gewählten Komponenten."),
                ("Verbindung", "Internet erforderlich für Download, Aktivierung und Updates."),
            ],
            "es": [
                ("Sistema operativo", "Windows 10/11 (64 bits) o una versión de macOS compatible con Corel."),
                ("Memoria (RAM)", "Al menos 4 GB, se recomiendan 8 GB o más para archivos complejos."),
                ("Espacio en disco", "Unos 2-3 GB libres para la instalación, según los componentes elegidos."),
                ("Conexión", "Internet necesario para la descarga, la activación y las actualizaciones."),
            ],
            "pt": [
                ("Sistema operativo", "Windows 10/11 (64-bit) ou macOS em versão suportada pela Corel."),
                ("Memória (RAM)", "No mínimo 4 GB, recomendados 8 GB ou mais para ficheiros complexos."),
                ("Espaço em disco", "Cerca de 2-3 GB livres para a instalação, segundo os componentes escolhidos."),
                ("Ligação", "Internet necessária para download, ativação e atualizações."),
            ],
        },
        "faq": {
            "it": [
                ("È una licenza perpetua o un abbonamento?", "La licenza descritta in questa scheda è quella indicata nel titolo e nel prezzo del prodotto."),
                ("Funziona su Mac oltre che su Windows?", "Sì, CorelDRAW Graphics Suite 2024 è disponibile per entrambi i sistemi operativi."),
                ("È inclusa la modifica foto?", "Sì, Corel PHOTO-PAINT per il ritocco fotografico fa parte della stessa suite."),
                ("Con quali formati è compatibile?", "Importa ed esporta AI, PSD, PDF e i principali formati grafici usati in ambito professionale."),
                ("Come ricevo e attivo la licenza?", "Ricevi il codice seriale via email: lo usi per scaricare e attivare la suite dal tuo account Corel."),
            ],
            "en": [
                ("Is it a perpetual licence or a subscription?", "The licence described on this page is the one shown in the product title and price."),
                ("Does it work on Mac as well as Windows?", "Yes, CorelDRAW Graphics Suite 2024 is available for both operating systems."),
                ("Is photo editing included?", "Yes, Corel PHOTO-PAINT for photo retouching is part of the same suite."),
                ("Which formats is it compatible with?", "It imports and exports AI, PSD, PDF and the main graphics formats used professionally."),
                ("How do I receive and activate the licence?", "You receive the serial code by email and use it to download and activate the suite from your Corel account."),
            ],
            "fr": [
                ("Est-ce une licence perpétuelle ou un abonnement ?", "La licence décrite sur cette fiche est celle indiquée dans le titre et le prix du produit."),
                ("Fonctionne-t-il sur Mac comme sur Windows ?", "Oui, CorelDRAW Graphics Suite 2024 est disponible sur les deux systèmes."),
                ("La retouche photo est-elle incluse ?", "Oui, Corel PHOTO-PAINT pour la retouche photo fait partie de la même suite."),
                ("Avec quels formats est-il compatible ?", "Import/export AI, PSD, PDF et les principaux formats graphiques professionnels."),
                ("Comment je reçois et active la licence ?", "Vous recevez le numéro de série par e-mail et l'utilisez pour télécharger et activer la suite depuis votre compte Corel."),
            ],
            "de": [
                ("Ist das eine Dauerlizenz oder ein Abo?", "Die auf dieser Seite beschriebene Lizenz ist die im Produkttitel und -preis angegebene."),
                ("Funktioniert es auf Mac genauso wie auf Windows?", "Ja, CorelDRAW Graphics Suite 2024 ist für beide Betriebssysteme verfügbar."),
                ("Ist die Fotobearbeitung enthalten?", "Ja, Corel PHOTO-PAINT für die Fotoretusche ist Teil derselben Suite."),
                ("Mit welchen Formaten ist es kompatibel?", "Import/Export von AI, PSD, PDF und den wichtigsten professionellen Grafikformaten."),
                ("Wie erhalte und aktiviere ich die Lizenz?", "Sie erhalten den Seriencode per E-Mail und nutzen ihn, um die Suite über Ihr Corel-Konto herunterzuladen und zu aktivieren."),
            ],
            "es": [
                ("¿Es una licencia perpetua o una suscripción?", "La licencia descrita en esta ficha es la indicada en el título y el precio del producto."),
                ("¿Funciona en Mac además de en Windows?", "Sí, CorelDRAW Graphics Suite 2024 está disponible para ambos sistemas operativos."),
                ("¿Incluye edición de fotos?", "Sí, Corel PHOTO-PAINT para el retoque fotográfico forma parte de la misma suite."),
                ("¿Con qué formatos es compatible?", "Importa y exporta AI, PSD, PDF y los principales formatos gráficos profesionales."),
                ("¿Cómo recibo y activo la licencia?", "Recibes el código de serie por email y lo usas para descargar y activar la suite desde tu cuenta Corel."),
            ],
            "pt": [
                ("É uma licença perpétua ou uma subscrição?", "A licença descrita nesta ficha é a indicada no título e no preço do produto."),
                ("Funciona em Mac além de Windows?", "Sim, o CorelDRAW Graphics Suite 2024 está disponível para ambos os sistemas operativos."),
                ("A edição de fotos está incluída?", "Sim, o Corel PHOTO-PAINT para retoque fotográfico faz parte da mesma suite."),
                ("Com que formatos é compatível?", "Importa e exporta AI, PSD, PDF e os principais formatos gráficos usados profissionalmente."),
                ("Como recebo e ativo a licença?", "Recebes o código de série por email e usa-lo para descarregar e ativar a suite a partir da tua conta Corel."),
            ],
        },
    },
    "acronis-true-image-advanced": {
        "seo_title": L(
            it="Acronis True Image Advanced — 1 dispositivo — Eurolicenze",
            en="Acronis True Image Advanced — 1 device — Eurolicenze",
            fr="Acronis True Image Advanced — 1 appareil — Eurolicenze",
            de="Acronis True Image Advanced — 1 Gerät — Eurolicenze",
            es="Acronis True Image Advanced — 1 dispositivo — Eurolicenze",
            pt="Acronis True Image Advanced — 1 dispositivo — Eurolicenze",
            nl="Acronis True Image Advanced — 1 apparaat — Eurolicenze",
        ),
        "title_html": L(
            it='Acronis True Image <span>Advanced</span>',
            en='Acronis True Image <span>Advanced</span>',
            fr='Acronis True Image <span>Advanced</span>',
            de='Acronis True Image <span>Advanced</span>',
            es='Acronis True Image <span>Advanced</span>',
            pt='Acronis True Image <span>Advanced</span>',
            nl='Acronis True Image <span>Advanced</span>',
        ),
        "eyebrow": L(
            it="Abbonamento · backup e protezione anti-ransomware",
            en="Subscription · backup and anti-ransomware protection",
            fr="Abonnement · sauvegarde et protection anti-rançongiciel",
            de="Abonnement · Backup und Ransomware-Schutz",
            es="Suscripción · copia de seguridad y protección antirransomware",
            pt="Subscrição · cópia de segurança e proteção anti-ransomware",
            nl="Abonnement · back-up en bescherming tegen ransomware",
        ),
        "desc": L(
            it="Licenza digitale originale di Acronis True Image Advanced: backup completo del PC con spazio cloud incluso e protezione attiva contro ransomware e malware. Codice e istruzioni via email dopo l'acquisto.",
            en="Genuine digital licence for Acronis True Image Advanced: full PC backup with included cloud storage and active protection against ransomware and malware. Code and instructions by email after purchase.",
            fr="Licence numérique originale d'Acronis True Image Advanced : sauvegarde complète du PC avec espace cloud inclus et protection active contre les rançongiciels et logiciels malveillants. Code et instructions par e-mail après l'achat.",
            de="Originale digitale Lizenz für Acronis True Image Advanced: vollständiges PC-Backup mit inkludiertem Cloud-Speicher und aktivem Schutz vor Ransomware und Malware. Code und Anleitung per E-Mail nach dem Kauf.",
            es="Licencia digital original de Acronis True Image Advanced: copia de seguridad completa del PC con almacenamiento en la nube incluido y protección activa contra ransomware y malware. Código e instrucciones por email tras la compra.",
            pt="Licença digital original do Acronis True Image Advanced: cópia de segurança completa do PC com espaço na nuvem incluído e proteção ativa contra ransomware e malware. Código e instruções por email após a compra.",
            nl="Originele digitale licentie van Acronis True Image Advanced: volledige pc-back-up met inbegrepen cloudopslag en actieve bescherming tegen ransomware en malware. Code en instructies per e-mail na aankoop.",
        ),
        "features_title": L(
            it="I tuoi dati, al sicuro ovunque",
            en="Your data, safe everywhere",
            fr="Vos données, en sécurité partout",
            de="Ihre Daten, überall sicher",
            es="Tus datos, seguros en todas partes",
            pt="Os teus dados, seguros em todo o lado",
            nl="Uw gegevens, overal beveiligd",
        ),
        "keypoints": L(
            it=["Backup completo del disco (immagine)", "Spazio di archiviazione cloud incluso", "Protezione attiva anti-ransomware", "Ripristino rapido su nuovo hardware"],
            en=["Full disk (image) backup", "Cloud storage space included", "Active anti-ransomware protection", "Fast recovery to new hardware"],
            fr=["Sauvegarde complète du disque (image)", "Espace de stockage cloud inclus", "Protection active anti-rançongiciel", "Restauration rapide sur un nouveau matériel"],
            de=["Vollständiges Festplatten-Image-Backup", "Cloud-Speicherplatz inklusive", "Aktiver Ransomware-Schutz", "Schnelle Wiederherstellung auf neuer Hardware"],
            es=["Copia de seguridad completa del disco (imagen)", "Espacio de almacenamiento en la nube incluido", "Protección activa antirransomware", "Recuperación rápida en hardware nuevo"],
            pt=["Cópia de segurança completa do disco (imagem)", "Espaço de armazenamento na cloud incluído", "Proteção ativa anti-ransomware", "Recuperação rápida em hardware novo"],
            nl=["Volledige schijfback-up (image)", "Cloudopslag inbegrepen", "Actieve bescherming tegen ransomware", "Snelle herstel op nieuwe hardware"],
        ),
        "features": {
            "it": [
                ("c8", "blue", "Backup", "Immagine completa del PC", "Copia l'intero disco — sistema, programmi e file — e ripristinalo in caso di guasto o furto."),
                ("c4", "teal", "Cloud", "Spazio di archiviazione incluso", "Backup anche fuori sede, al sicuro anche se il computer viene rubato o danneggiato."),
                ("c4", "purple", "Sicurezza", "Protezione attiva anti-ransomware", "Rileva e blocca i tentativi di cifratura sospetta dei tuoi file in tempo reale."),
                ("c4", None, "Pianificazione", "Backup automatici", "Imposta backup ricorrenti e dimenticatene: continuano in background."),
                ("c4", None, "Ripristino", "Clona o ripristina in pochi clic", "Recupera singoli file o l'intero sistema, anche su un PC nuovo."),
                ("c4", "dark", "Dispositivi", "1 dispositivo, Windows o Mac", "Licenza per un dispositivo; scegli quello da proteggere in fase di installazione."),
            ],
            "en": [
                ("c8", "blue", "Backup", "Full PC image", "Copy the entire disk — system, apps and files — and restore it after a failure or theft."),
                ("c4", "teal", "Cloud", "Storage space included", "Off-site backup too, safe even if the computer is stolen or damaged."),
                ("c4", "purple", "Security", "Active anti-ransomware protection", "Detects and blocks suspicious file-encryption attempts in real time."),
                ("c4", None, "Scheduling", "Automatic backups", "Set up recurring backups and forget about them — they keep running in the background."),
                ("c4", None, "Recovery", "Clone or restore in a few clicks", "Recover single files or the whole system, even on a new PC."),
                ("c4", "dark", "Devices", "1 device, Windows or Mac", "Licence for one device; choose the one to protect during setup."),
            ],
            "fr": [
                ("c8", "blue", "Sauvegarde", "Image complète du PC", "Copiez tout le disque — système, applications et fichiers — et restaurez-le après une panne ou un vol."),
                ("c4", "teal", "Cloud", "Espace de stockage inclus", "Sauvegarde hors site aussi, en sécurité même si l'ordinateur est volé ou endommagé."),
                ("c4", "purple", "Sécurité", "Protection active anti-rançongiciel", "Détecte et bloque en temps réel les tentatives de chiffrement suspectes de vos fichiers."),
                ("c4", None, "Planification", "Sauvegardes automatiques", "Programmez des sauvegardes récurrentes et n'y pensez plus — elles continuent en arrière-plan."),
                ("c4", None, "Restauration", "Cloner ou restaurer en quelques clics", "Récupérez des fichiers ou tout le système, même sur un nouveau PC."),
                ("c4", "dark", "Appareils", "1 appareil, Windows ou Mac", "Licence pour un appareil ; choisissez celui à protéger lors de l'installation."),
            ],
            "de": [
                ("c8", "blue", "Backup", "Vollständiges PC-Image", "Die gesamte Festplatte — System, Programme und Dateien — sichern und nach Ausfall oder Diebstahl wiederherstellen."),
                ("c4", "teal", "Cloud", "Speicherplatz inklusive", "Auch externe Sicherung, sicher selbst wenn der Computer gestohlen oder beschädigt wird."),
                ("c4", "purple", "Sicherheit", "Aktiver Ransomware-Schutz", "Erkennt und blockiert verdächtige Verschlüsselungsversuche Ihrer Dateien in Echtzeit."),
                ("c4", None, "Zeitplan", "Automatische Backups", "Wiederkehrende Backups einrichten und vergessen — sie laufen im Hintergrund weiter."),
                ("c4", None, "Wiederherstellung", "Klonen oder wiederherstellen in wenigen Klicks", "Einzelne Dateien oder das ganze System wiederherstellen, auch auf neuer Hardware."),
                ("c4", "dark", "Geräte", "1 Gerät, Windows oder Mac", "Lizenz für ein Gerät; wählen Sie es bei der Installation aus."),
            ],
            "es": [
                ("c8", "blue", "Copia de seguridad", "Imagen completa del PC", "Copia todo el disco —sistema, programas y archivos— y restáuralo tras un fallo o robo."),
                ("c4", "teal", "Nube", "Espacio de almacenamiento incluido", "Copia también fuera del equipo, a salvo incluso si el ordenador es robado o dañado."),
                ("c4", "purple", "Seguridad", "Protección activa antirransomware", "Detecta y bloquea en tiempo real los intentos sospechosos de cifrar tus archivos."),
                ("c4", None, "Planificación", "Copias automáticas", "Configura copias recurrentes y olvídate: siguen ejecutándose en segundo plano."),
                ("c4", None, "Recuperación", "Clona o restaura en pocos clics", "Recupera archivos individuales o todo el sistema, incluso en un PC nuevo."),
                ("c4", "dark", "Dispositivos", "1 dispositivo, Windows o Mac", "Licencia para un dispositivo; elige cuál proteger durante la instalación."),
            ],
            "pt": [
                ("c8", "blue", "Backup", "Imagem completa do PC", "Copia o disco inteiro — sistema, programas e ficheiros — e restaura-o em caso de avaria ou roubo."),
                ("c4", "teal", "Cloud", "Espaço de armazenamento incluído", "Backup também fora do local, seguro mesmo que o computador seja roubado ou danificado."),
                ("c4", "purple", "Segurança", "Proteção ativa anti-ransomware", "Deteta e bloqueia em tempo real tentativas suspeitas de encriptação dos teus ficheiros."),
                ("c4", None, "Agendamento", "Backups automáticos", "Configura backups recorrentes e esquece-te deles: continuam a correr em segundo plano."),
                ("c4", None, "Recuperação", "Clona ou restaura em poucos cliques", "Recupera ficheiros individuais ou todo o sistema, mesmo num PC novo."),
                ("c4", "dark", "Dispositivos", "1 dispositivo, Windows ou Mac", "Licença para um dispositivo; escolhe qual proteger durante a instalação."),
            ],
        },
        "steps": {
            "it": [
                ("Ordine e pagamento", "Aggiungi il prodotto al carrello e completa il pagamento con i metodi disponibili."),
                ("Consegna digitale", "Ricevi via email il codice di attivazione e le istruzioni, di norma entro pochi minuti dal pagamento."),
                ("Attivazione", "Crea o accedi al tuo account Acronis, installa il software e attiva la licenza con il codice ricevuto."),
            ],
            "en": [
                ("Order and payment", "Add the product to your cart and complete checkout with the available methods."),
                ("Digital delivery", "You receive the activation code and instructions by email, usually within minutes of payment."),
                ("Activation", "Create or sign in to your Acronis account, install the software and activate the licence with the code received."),
            ],
            "fr": [
                ("Commande et paiement", "Ajoutez le produit au panier et finalisez le paiement avec les méthodes disponibles."),
                ("Livraison numérique", "Vous recevez le code d'activation et les instructions par e-mail, généralement en quelques minutes."),
                ("Activation", "Créez ou connectez-vous à votre compte Acronis, installez le logiciel et activez la licence avec le code reçu."),
            ],
            "de": [
                ("Bestellung und Zahlung", "Produkt in den Warenkorb legen und die Zahlung mit den verfügbaren Methoden abschließen."),
                ("Digitale Lieferung", "Sie erhalten den Aktivierungscode und die Anleitung per E-Mail, meist innerhalb weniger Minuten."),
                ("Aktivierung", "Acronis-Konto erstellen oder anmelden, Software installieren und Lizenz mit dem erhaltenen Code aktivieren."),
            ],
            "es": [
                ("Pedido y pago", "Añade el producto al carrito y completa el pago con los métodos disponibles."),
                ("Entrega digital", "Recibes el código de activación y las instrucciones por email, normalmente en pocos minutos."),
                ("Activación", "Crea o accede a tu cuenta Acronis, instala el software y activa la licencia con el código recibido."),
            ],
            "pt": [
                ("Encomenda e pagamento", "Adiciona o produto ao carrinho e conclui o pagamento com os métodos disponíveis."),
                ("Entrega digital", "Recebes por email o código de ativação e as instruções, normalmente em poucos minutos após o pagamento."),
                ("Ativação", "Cria ou acede à tua conta Acronis, instala o software e ativa a licença com o código recebido."),
            ],
        },
        "specs": {
            "it": [
                ("Sistema operativo", "Windows 10/11 o macOS in versione supportata da Acronis."),
                ("Connessione", "Internet richiesta per l'attivazione e per il backup su cloud."),
                ("Spazio su disco", "Spazio libero sufficiente per l'immagine di backup locale, secondo i dati da salvare."),
                ("Dispositivi coperti", "1 dispositivo per licenza; la durata dell'abbonamento è indicata nella scheda prodotto."),
            ],
            "en": [
                ("Operating system", "Windows 10/11 or a macOS version supported by Acronis."),
                ("Connection", "Internet required for activation and for cloud backup."),
                ("Disk space", "Enough free space for the local backup image, depending on the data being saved."),
                ("Devices covered", "1 device per licence; the subscription term is shown on the product page."),
            ],
            "fr": [
                ("Système d'exploitation", "Windows 10/11 ou une version de macOS prise en charge par Acronis."),
                ("Connexion", "Internet requis pour l'activation et la sauvegarde cloud."),
                ("Espace disque", "Espace libre suffisant pour l'image de sauvegarde locale, selon les données à sauvegarder."),
                ("Appareils couverts", "1 appareil par licence ; la durée de l'abonnement est indiquée sur la fiche produit."),
            ],
            "de": [
                ("Betriebssystem", "Windows 10/11 oder eine von Acronis unterstützte macOS-Version."),
                ("Verbindung", "Internet erforderlich für Aktivierung und Cloud-Backup."),
                ("Speicherplatz", "Ausreichend freier Speicher für das lokale Backup-Image, je nach zu sichernden Daten."),
                ("Abgedeckte Geräte", "1 Gerät pro Lizenz; die Laufzeit des Abos steht auf der Produktseite."),
            ],
            "es": [
                ("Sistema operativo", "Windows 10/11 o una versión de macOS compatible con Acronis."),
                ("Conexión", "Internet necesario para la activación y la copia en la nube."),
                ("Espacio en disco", "Espacio libre suficiente para la imagen de copia local, según los datos a guardar."),
                ("Dispositivos cubiertos", "1 dispositivo por licencia; la duración de la suscripción se indica en la ficha del producto."),
            ],
            "pt": [
                ("Sistema operativo", "Windows 10/11 ou macOS em versão suportada pela Acronis."),
                ("Ligação", "Internet necessária para a ativação e para o backup na cloud."),
                ("Espaço em disco", "Espaço livre suficiente para a imagem de backup local, segundo os dados a guardar."),
                ("Dispositivos cobertos", "1 dispositivo por licença; a duração da subscrição está indicada na ficha do produto."),
            ],
        },
        "faq": {
            "it": [
                ("Quanto spazio cloud è incluso?", "Lo spazio incluso dipende dal piano indicato in questa scheda; puoi verificarlo nei dettagli del tuo account Acronis dopo l'attivazione."),
                ("Protegge davvero dai ransomware?", "Sì, la protezione attiva monitora in tempo reale i tentativi di cifratura sospetta e li blocca."),
                ("Su quanti dispositivi posso usarlo?", "La licenza copre 1 dispositivo; scegli quello da proteggere durante l'installazione."),
                ("Come ricevo e attivo la licenza?", "Ricevi il codice via email: lo usi per attivare l'abbonamento sul tuo account Acronis dopo aver installato il software."),
                ("Funziona anche su Mac?", "Sì, Acronis True Image è disponibile sia per Windows sia per macOS."),
            ],
            "en": [
                ("How much cloud storage is included?", "Included storage depends on the plan shown on this page; check the details in your Acronis account after activation."),
                ("Does it really protect against ransomware?", "Yes, active protection monitors suspicious encryption attempts in real time and blocks them."),
                ("How many devices can I use it on?", "The licence covers 1 device; choose the one to protect during installation."),
                ("How do I receive and activate the licence?", "You receive the code by email and use it to activate the subscription on your Acronis account after installing the software."),
                ("Does it work on Mac too?", "Yes, Acronis True Image is available for both Windows and macOS."),
            ],
            "fr": [
                ("Quel espace cloud est inclus ?", "L'espace inclus dépend du forfait indiqué sur cette fiche ; vérifiez-le dans votre compte Acronis après activation."),
                ("Protège-t-il vraiment contre les rançongiciels ?", "Oui, la protection active surveille en temps réel les tentatives de chiffrement suspectes et les bloque."),
                ("Sur combien d'appareils puis-je l'utiliser ?", "La licence couvre 1 appareil ; choisissez celui à protéger lors de l'installation."),
                ("Comment je reçois et active la licence ?", "Vous recevez le code par e-mail et l'utilisez pour activer l'abonnement sur votre compte Acronis après installation du logiciel."),
                ("Fonctionne-t-il aussi sur Mac ?", "Oui, Acronis True Image est disponible pour Windows et macOS."),
            ],
            "de": [
                ("Wie viel Cloud-Speicher ist enthalten?", "Der enthaltene Speicher hängt vom auf dieser Seite angegebenen Plan ab; prüfen Sie die Details in Ihrem Acronis-Konto nach der Aktivierung."),
                ("Schützt es wirklich vor Ransomware?", "Ja, der aktive Schutz überwacht verdächtige Verschlüsselungsversuche in Echtzeit und blockiert sie."),
                ("Auf wie vielen Geräten kann ich es nutzen?", "Die Lizenz deckt 1 Gerät ab; wählen Sie es bei der Installation aus."),
                ("Wie erhalte und aktiviere ich die Lizenz?", "Sie erhalten den Code per E-Mail und aktivieren damit das Abo in Ihrem Acronis-Konto nach der Installation der Software."),
                ("Funktioniert es auch auf dem Mac?", "Ja, Acronis True Image ist für Windows und macOS verfügbar."),
            ],
            "es": [
                ("¿Cuánto espacio en la nube incluye?", "El espacio incluido depende del plan indicado en esta ficha; compruébalo en los detalles de tu cuenta Acronis tras la activación."),
                ("¿De verdad protege contra el ransomware?", "Sí, la protección activa vigila en tiempo real los intentos sospechosos de cifrado y los bloquea."),
                ("¿En cuántos dispositivos puedo usarlo?", "La licencia cubre 1 dispositivo; elige cuál proteger durante la instalación."),
                ("¿Cómo recibo y activo la licencia?", "Recibes el código por email y lo usas para activar la suscripción en tu cuenta Acronis tras instalar el software."),
                ("¿Funciona también en Mac?", "Sí, Acronis True Image está disponible tanto para Windows como para macOS."),
            ],
            "pt": [
                ("Quanto espaço na nuvem está incluído?", "O espaço incluído depende do plano indicado nesta ficha; podes verificá-lo nos detalhes da tua conta Acronis após a ativação."),
                ("Protege mesmo contra ransomware?", "Sim, a proteção ativa monitoriza em tempo real tentativas suspeitas de encriptação e bloqueia-as."),
                ("Em quantos dispositivos posso usá-lo?", "A licença cobre 1 dispositivo; escolhe qual proteger durante a instalação."),
                ("Como recebo e ativo a licença?", "Recebes o código por email e usa-lo para ativar a subscrição na tua conta Acronis depois de instalar o software."),
                ("Funciona também em Mac?", "Sim, o Acronis True Image está disponível tanto para Windows como para macOS."),
            ],
        },
    },
}

backfill_lang(PRODUCTS)
backfill_lang(PRODUCTS, target="nl", source="en", translate=nl_text)


def get_tools_content(slug):
    return PRODUCTS.get(slug)
