#!/usr/bin/env python3
"""Rich product-page content for Windows client SKUs (excludes preserved windows-11-home)."""

from copy import deepcopy

from product_content_office import UI as OFFICE_UI
from lang_backfill import backfill_lang
from nl_translations import nl_text

LANGS = ("it", "en", "fr", "de", "es", "pt", "nl")


def L(**kwargs):
    # "pt" e' opzionale nelle call site esistenti: se assente, eredita il
    # valore "es" (lingua piu' vicina) invece di far esplodere il generatore.
    # I campi che meritano una vera traduzione portoghese la passano
    # esplicitamente (pt=...) e questo fallback non scatta.
    if "pt" not in kwargs:
        kwargs["pt"] = kwargs.get("es") or kwargs.get("en")
    if "nl" not in kwargs:
        kwargs["nl"] = kwargs.get("en")
    return {k: kwargs[k] for k in LANGS}


# Shared chrome based on Office UI, with Windows-specific steps/specs
UI = deepcopy(OFFICE_UI)
_WIN_OVERRIDES = {
    "it": {
        "apps_eyebrow": "In evidenza",
        "step2_body": "Ti inviamo la <strong>product key</strong> (e le istruzioni) via email, di solito entro pochi minuti dall'approvazione del pagamento. Per edizioni con supporto fisico (DVD/COA) segui anche quanto indicato in email.",
        "step3_body": "Attiva Windows con il codice ricevuto: Impostazioni → Sistema → Attivazione (o la procedura descritta nell'email). Usa i canali ufficiali Microsoft.",
        "spec_cpu_body": "Processore compatibile con i requisiti Microsoft della versione Windows indicata (per Windows 11 tipicamente CPU supportata nell'elenco ufficiale).",
        "spec_os_body": "Questa scheda riguarda la licenza del sistema operativo indicato. Verifica hardware e TPM/Secure Boot dove richiesto (es. Windows 11).",
        "spec_ram_body": "Windows 10: tipicamente almeno 2–4 GB. Windows 11: almeno 4 GB secondo i requisiti Microsoft aggiornati.",
        "spec_disk_body": "Spazio libero sufficiente per l'installazione/upgrade come da documentazione Microsoft (spesso decine di GB per un'installazione completa).",
    },
    "en": {
        "apps_eyebrow": "Highlights",
        "step2_body": "We email the <strong>product key</strong> (and instructions), usually within minutes after payment approval. For editions with physical media (DVD/COA), also follow the email details.",
        "step3_body": "Activate Windows with the received key: Settings → System → Activation (or the steps in the email). Use official Microsoft channels.",
        "spec_cpu_body": "A processor that meets Microsoft’s requirements for the indicated Windows version (for Windows 11, typically a CPU on Microsoft’s supported list).",
        "spec_os_body": "This page covers the indicated OS licence. Check hardware and TPM/Secure Boot where required (e.g. Windows 11).",
        "spec_ram_body": "Windows 10: typically at least 2–4 GB. Windows 11: at least 4 GB per current Microsoft requirements.",
        "spec_disk_body": "Enough free space for install/upgrade per Microsoft docs (often tens of GB for a full install).",
    },
    "fr": {
        "apps_eyebrow": "Points clés",
        "step2_body": "Nous envoyons la <strong>clé produit</strong> (et les instructions) par e-mail, en général quelques minutes après validation du paiement. Pour DVD/COA, suivez aussi l'e-mail.",
        "step3_body": "Activez Windows avec le code reçu : Paramètres → Système → Activation (ou la procédure de l'e-mail). Utilisez les canaux Microsoft officiels.",
        "spec_cpu_body": "Processeur conforme aux exigences Microsoft pour la version Windows indiquée (Windows 11 : CPU sur la liste prise en charge).",
        "spec_os_body": "Cette fiche concerne la licence du système indiqué. Vérifiez le matériel et TPM/Secure Boot si requis (ex. Windows 11).",
        "spec_ram_body": "Windows 10 : en général 2–4 Go. Windows 11 : au moins 4 Go selon Microsoft.",
        "spec_disk_body": "Espace libre suffisant pour l'installation selon la documentation Microsoft.",
    },
    "de": {
        "apps_eyebrow": "Highlights",
        "step2_body": "Wir senden den <strong>Product Key</strong> (und die Anleitung) per E-Mail, in der Regel wenige Minuten nach Zahlungsfreigabe. Bei DVD/COA zusätzlich die E-Mail beachten.",
        "step3_body": "Aktivieren Sie Windows mit dem erhaltenen Key: Einstellungen → System → Aktivierung (oder die Schritte in der E-Mail). Offizielle Microsoft-Kanäle nutzen.",
        "spec_cpu_body": "Prozessor gemäß Microsoft-Anforderungen der angegebenen Windows-Version (Windows 11: typisch CPU auf der Support-Liste).",
        "spec_os_body": "Diese Seite betrifft die genannte OS-Lizenz. Hardware sowie TPM/Secure Boot prüfen, wo erforderlich (z. B. Windows 11).",
        "spec_ram_body": "Windows 10: typisch mindestens 2–4 GB. Windows 11: mindestens 4 GB laut Microsoft.",
        "spec_disk_body": "Ausreichend freier Speicher für Installation laut Microsoft-Dokumentation.",
    },
    "es": {
        "apps_eyebrow": "Destacados",
        "step2_body": "Enviamos la <strong>clave de producto</strong> (e instrucciones) por email, normalmente en minutos tras aprobar el pago. Para DVD/COA sigue también el email.",
        "step3_body": "Activa Windows con la clave recibida: Configuración → Sistema → Activación (o los pasos del email). Usa canales oficiales Microsoft.",
        "spec_cpu_body": "Procesador compatible con los requisitos Microsoft de la versión Windows indicada (Windows 11: CPU en la lista admitida).",
        "spec_os_body": "Esta ficha cubre la licencia del sistema indicado. Comprueba hardware y TPM/Secure Boot si aplica (p. ej. Windows 11).",
        "spec_ram_body": "Windows 10: normalmente al menos 2–4 GB. Windows 11: al menos 4 GB según Microsoft.",
        "spec_disk_body": "Espacio libre suficiente para instalar según la documentación Microsoft.",
    },
    "pt": {
        "apps_eyebrow": "Destaques",
        "step2_body": "Enviamos-te a <strong>chave de produto</strong> (e as instruções) por email, normalmente em poucos minutos após a aprovação do pagamento. Para edições com suporte físico (DVD/COA), segue também as indicações no email.",
        "step3_body": "Ativa o Windows com o código recebido: Definições → Sistema → Ativação (ou o procedimento descrito no email). Usa os canais oficiais da Microsoft.",
        "spec_cpu_body": "Processador compatível com os requisitos Microsoft da versão Windows indicada (para o Windows 11, normalmente CPU na lista oficial suportada).",
        "spec_os_body": "Esta ficha refere-se à licença do sistema operativo indicado. Verifica hardware e TPM/Secure Boot quando necessário (ex. Windows 11).",
        "spec_ram_body": "Windows 10: normalmente pelo menos 2–4 GB. Windows 11: pelo menos 4 GB segundo os requisitos Microsoft atualizados.",
        "spec_disk_body": "Espaço livre suficiente para a instalação/atualização segundo a documentação Microsoft (frequentemente dezenas de GB para uma instalação completa).",
    },
    "nl": {
        "apps_eyebrow": "Hoogtepunten",
        "step2_body": "Wij sturen u de <strong>productsleutel</strong> (en de instructies) per e-mail, meestal binnen enkele minuten na goedkeuring van de betaling. Voor edities met fysieke media (dvd/COA) volgt u ook de aanwijzingen in de e-mail.",
        "step3_body": "Activeer Windows met de ontvangen code: Instellingen → Systeem → Activering (of de procedure in de e-mail). Gebruik de officiële Microsoft-kanalen.",
        "spec_cpu_body": "Een processor die voldoet aan de Microsoft-vereisten voor de aangegeven Windows-versie (voor Windows 11 doorgaans een CPU op de officiële ondersteuningslijst).",
        "spec_os_body": "Deze fiche betreft de licentie van het aangegeven besturingssysteem. Controleer hardware en TPM/Secure Boot waar vereist (bijv. Windows 11).",
        "spec_ram_body": "Windows 10: doorgaans minstens 2–4 GB. Windows 11: minstens 4 GB volgens de actuele Microsoft-vereisten.",
        "spec_disk_body": "Voldoende vrije ruimte voor installatie/upgrade volgens de Microsoft-documentatie (vaak tientallen GB voor een volledige installatie).",
    },
}
backfill_lang(_WIN_OVERRIDES, target="nl", source="en", translate=nl_text)
for lg, ov in _WIN_OVERRIDES.items():
    UI[lg].update(ov)


def _pills_win11():
    return {lg: [(None, "Windows 11"), (None, "Licenza digitale"), (None, "Attivazione Microsoft")] for lg in LANGS}


def _pills_win10():
    return {lg: [(None, "Windows 10"), (None, "Licenza digitale"), (None, "32/64-bit")] for lg in LANGS}


PRODUCTS = {
    "windows-11-pro": {
        "apps": [],
        "title_html": L(
            it='Windows 11 <span>Pro</span>',
            en='Windows 11 <span>Pro</span>',
            fr='Windows 11 <span>Pro</span>',
            de='Windows 11 <span>Pro</span>',
            es='Windows 11 <span>Pro</span>',
            pt='Windows 11 <span>Pro</span>',
            nl='Windows 11 <span>Pro</span>',
        ),
        "eyebrow": L(
            it="Sistema operativo · licenza ESD",
            en="Operating system · ESD licence",
            fr="Système d'exploitation · licence ESD",
            de="Betriebssystem · ESD-Lizenz",
            es="Sistema operativo · licencia ESD",
            pt="Sistema operativo · licença ESD",
            nl="Besturingssysteem · ESD-licentie",
        ),
        "desc": L(
            it="Windows 11 Pro: licenza digitale originale con funzioni professionali (es. BitLocker e Desktop remoto, secondo Microsoft). Codice via email dopo l'acquisto.",
            en="Windows 11 Pro: genuine digital licence with professional features (e.g. BitLocker and Remote Desktop, per Microsoft). Key by email after purchase.",
            fr="Windows 11 Pro : licence numérique originale avec fonctions pro (ex. BitLocker et Bureau à distance, selon Microsoft). Code par e-mail.",
            de="Windows 11 Pro: originale digitale Lizenz mit Pro-Funktionen (z. B. BitLocker und Remotedesktop laut Microsoft). Key per E-Mail.",
            es="Windows 11 Pro: licencia digital original con funciones profesionales (p. ej. BitLocker y Escritorio remoto según Microsoft). Clave por email.",
            pt="Windows 11 Pro: licença digital original com funções profissionais (ex. BitLocker e Área de Trabalho Remota, segundo a Microsoft). Código por email após a compra.",
            nl="Windows 11 Pro: originele digitale licentie met professionele functies (bijv. BitLocker en Extern bureaublad, volgens Microsoft). Code per e-mail na aankoop.",
        ),
        "pills": {
            "it": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
            "en": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
            "fr": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
            "de": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
            "es": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
            "pt": [(None, "Windows 11 Pro"), (None, "ESD"), (None, "BitLocker / RDP")],
        },
        "features_title": L(
            it="Pro per lavoro e produttività",
            en="Pro for work and productivity",
            fr="Pro pour le travail",
            de="Pro für Arbeit und Produktivität",
            es="Pro para trabajo y productividad",
            pt="Pro para trabalho e produtividade",
            nl="Pro voor werk en productiviteit",
        ),
        "features": {
            "it": [
                ("c8", "blue", "Edizione", "Windows 11 Pro", "Licenza Pro con strumenti pensati per professionisti e PMI, secondo le funzionalità Microsoft della edizione."),
                ("c4", "teal", None, "Sicurezza Pro", "Funzioni come BitLocker dove supportate dall'hardware e dall'edizione."),
                ("c4", "purple", "Remoto", "Desktop remoto", "Accesso remoto host secondo le capacità Pro di Windows 11."),
                ("c4", None, "Consegna", "Digitale ESD", "Product key via email dopo il pagamento."),
                ("c4", None, "Attivazione", "Ufficiale Microsoft", "Attivi da Impostazioni Windows con il codice ricevuto."),
                ("c4", "dark", "Requisiti", "Hardware Windows 11", "Verifica CPU, TPM 2.0 e Secure Boot prima dell'upgrade/installazione."),
            ],
            "en": [
                ("c8", "blue", "Edition", "Windows 11 Pro", "Pro licence with tools for professionals and SMBs, per Microsoft’s edition features."),
                ("c4", "teal", None, "Pro security", "Features such as BitLocker where hardware and edition support them."),
                ("c4", "purple", "Remote", "Remote Desktop", "Host remote access per Windows 11 Pro capabilities."),
                ("c4", None, "Delivery", "Digital ESD", "Product key by email after payment."),
                ("c4", None, "Activation", "Official Microsoft", "Activate from Windows Settings with your key."),
                ("c4", "dark", "Requirements", "Windows 11 hardware", "Check CPU, TPM 2.0 and Secure Boot before upgrade/install."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Windows 11 Pro", "Licence Pro avec outils pour pros et TPE, selon les fonctions Microsoft."),
                ("c4", "teal", None, "Sécurité Pro", "Fonctions comme BitLocker si le matériel et l'édition le permettent."),
                ("c4", "purple", "Distant", "Bureau à distance", "Accès distant hôte selon les capacités Pro."),
                ("c4", None, "Livraison", "ESD numérique", "Clé produit par e-mail après paiement."),
                ("c4", None, "Activation", "Microsoft officiel", "Activation depuis les Paramètres Windows."),
                ("c4", "dark", "Exigences", "Matériel Windows 11", "Vérifiez CPU, TPM 2.0 et Secure Boot."),
            ],
            "de": [
                ("c8", "blue", "Edition", "Windows 11 Pro", "Pro-Lizenz mit Tools für Profis und KMU gemäß Microsoft."),
                ("c4", "teal", None, "Pro-Sicherheit", "Funktionen wie BitLocker, sofern Hardware und Edition es zulassen."),
                ("c4", "purple", "Remote", "Remotedesktop", "Host-Zugriff gemäß Windows-11-Pro-Funktionen."),
                ("c4", None, "Lieferung", "Digitale ESD", "Product Key per E-Mail nach der Zahlung."),
                ("c4", None, "Aktivierung", "Offiziell Microsoft", "Aktivierung in den Windows-Einstellungen."),
                ("c4", "dark", "Anforderungen", "Windows-11-Hardware", "CPU, TPM 2.0 und Secure Boot prüfen."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Windows 11 Pro", "Licencia Pro con herramientas para profesionales y pymes según Microsoft."),
                ("c4", "teal", None, "Seguridad Pro", "Funciones como BitLocker si el hardware y la edición lo permiten."),
                ("c4", "purple", "Remoto", "Escritorio remoto", "Acceso remoto host según capacidades Pro."),
                ("c4", None, "Entrega", "ESD digital", "Clave por email tras el pago."),
                ("c4", None, "Activación", "Microsoft oficial", "Activa desde Configuración de Windows."),
                ("c4", "dark", "Requisitos", "Hardware Windows 11", "Comprueba CPU, TPM 2.0 y Secure Boot."),
            ],
            "pt": [
                ("c8", "blue", "Edição", "Windows 11 Pro", "Licença Pro com ferramentas para profissionais e PME, segundo as funcionalidades Microsoft da edição."),
                ("c4", "teal", None, "Segurança Pro", "Funções como o BitLocker onde suportadas pelo hardware e pela edição."),
                ("c4", "purple", "Remoto", "Área de Trabalho Remota", "Acesso remoto como anfitrião segundo as capacidades Pro do Windows 11."),
                ("c4", None, "Entrega", "ESD digital", "Product key por email após o pagamento."),
                ("c4", None, "Ativação", "Microsoft oficial", "Ativa em Definições do Windows com o código recebido."),
                ("c4", "dark", "Requisitos", "Hardware Windows 11", "Verifica CPU, TPM 2.0 e Secure Boot antes da atualização/instalação."),
            ],
        },
        "apps_title": L(it="", en="", fr="", de="", es="", pt="", nl=""),
        "faq": {
            "it": [
                ("Differenza con Windows 11 Home?", "Pro aggiunge funzioni orientate al lavoro (es. BitLocker, Desktop remoto come host) rispetto a Home, secondo Microsoft."),
                ("È una licenza perpetua?", "Sì: licenza digitale ESD descritta in scheda, non un abbonamento."),
                ("Il PC è compatibile con Windows 11?", "Controlla i requisiti Microsoft (CPU, TPM 2.0, Secure Boot, RAM e storage) prima di installare."),
                ("Come si attiva?", "Impostazioni → Sistema → Attivazione con il codice ricevuto via email."),
                ("Serve reinstallare Windows?", "Dipende dal tuo caso (upgrade o installazione pulita). Segui le istruzioni email e la documentazione Microsoft."),
            ],
            "en": [
                ("Difference vs Windows 11 Home?", "Pro adds work-oriented features (e.g. BitLocker, Remote Desktop host) versus Home, per Microsoft."),
                ("Is it perpetual?", "Yes—digital ESD licence as described, not a subscription."),
                ("Is my PC Windows 11 ready?", "Check Microsoft’s requirements (CPU, TPM 2.0, Secure Boot, RAM and storage) first."),
                ("How do I activate?", "Settings → System → Activation with the emailed key."),
                ("Do I need to reinstall?", "Depends on upgrade vs clean install. Follow the email and Microsoft docs."),
            ],
            "fr": [
                ("Différence avec Home ?", "Pro ajoute des fonctions pro (ex. BitLocker, Bureau à distance hôte) par rapport à Home."),
                ("Licence perpétuelle ?", "Oui — licence ESD numérique, pas un abonnement."),
                ("PC compatible Windows 11 ?", "Vérifiez les exigences Microsoft (CPU, TPM 2.0, Secure Boot…)."),
                ("Activation ?", "Paramètres → Système → Activation avec le code reçu."),
                ("Faut-il réinstaller ?", "Selon upgrade ou installation propre ; suivez l'e-mail et Microsoft."),
            ],
            "de": [
                ("Unterschied zu Home?", "Pro ergänzt arbeitsbezogene Funktionen (z. B. BitLocker, Remotedesktop-Host) gegenüber Home."),
                ("Dauerlizenz?", "Ja — digitale ESD-Lizenz, kein Abo."),
                ("PC bereit für Windows 11?", "Microsoft-Anforderungen prüfen (CPU, TPM 2.0, Secure Boot…)."),
                ("Aktivierung?", "Einstellungen → System → Aktivierung mit dem E-Mail-Key."),
                ("Neuinstallation nötig?", "Abhängig von Upgrade oder Clean Install; E-Mail und Microsoft-Doku folgen."),
            ],
            "es": [
                ("¿Diferencia con Home?", "Pro añade funciones orientadas al trabajo (p. ej. BitLocker, Escritorio remoto host) frente a Home."),
                ("¿Es perpetua?", "Sí: licencia ESD digital, no una suscripción."),
                ("¿Mi PC es compatible con Windows 11?", "Comprueba los requisitos Microsoft (CPU, TPM 2.0, Secure Boot…)."),
                ("¿Cómo se activa?", "Configuración → Sistema → Activación con la clave del email."),
                ("¿Hay que reinstalar?", "Depende de actualización o instalación limpia; sigue el email y Microsoft."),
            ],
            "pt": [
                ("Qual a diferença em relação ao Windows 11 Home?", "O Pro adiciona funções orientadas ao trabalho (ex. BitLocker, Área de Trabalho Remota como anfitrião) em relação ao Home, segundo a Microsoft."),
                ("É uma licença perpétua?", "Sim: licença digital ESD conforme descrito na ficha, não uma subscrição."),
                ("O meu PC é compatível com o Windows 11?", "Verifica os requisitos Microsoft (CPU, TPM 2.0, Secure Boot, RAM e armazenamento) antes de instalar."),
                ("Como se ativa?", "Definições → Sistema → Ativação com o código recebido por email."),
                ("É necessário reinstalar o Windows?", "Depende do teu caso (atualização ou instalação limpa). Segue as instruções do email e a documentação Microsoft."),
            ],
        },
    },
    "windows-10-home": {
        "apps": [],
        "title_html": L(
            it='Windows 10 <span>Home</span>',
            en='Windows 10 <span>Home</span>',
            fr='Windows 10 <span>Home</span>',
            de='Windows 10 <span>Home</span>',
            es='Windows 10 <span>Home</span>',
            pt='Windows 10 <span>Home</span>',
            nl='Windows 10 <span>Home</span>',
        ),
        "eyebrow": L(
            it="Sistema operativo · 32/64-bit · ESD",
            en="Operating system · 32/64-bit · ESD",
            fr="Système d'exploitation · 32/64 bits · ESD",
            de="Betriebssystem · 32/64-Bit · ESD",
            es="Sistema operativo · 32/64 bits · ESD",
            pt="Sistema operativo · 32/64-bit · ESD",
            nl="Besturingssysteem · 32/64-bit · ESD",
        ),
        "desc": L(
            it="Windows 10 Home: licenza digitale originale 32/64-bit con consegna del codice via email. Ideale per uso domestico secondo le condizioni Microsoft.",
            en="Windows 10 Home: genuine 32/64-bit digital licence with email key delivery. Suited to home use under Microsoft’s terms.",
            fr="Windows 10 Home : licence numérique originale 32/64 bits, code par e-mail. Usage domestique selon Microsoft.",
            de="Windows 10 Home: originale 32/64-Bit-Lizenz mit Key per E-Mail. Für den Heimgebrauch gemäß Microsoft.",
            es="Windows 10 Home: licencia digital original 32/64 bits con clave por email. Uso doméstico según Microsoft.",
            pt="Windows 10 Home: licença digital original 32/64-bit com entrega do código por email. Ideal para uso doméstico segundo as condições Microsoft.",
            nl="Windows 10 Home: originele digitale 32/64-bit-licentie met levering van de code per e-mail. Geschikt voor thuisgebruik volgens de Microsoft-voorwaarden.",
        ),
        "pills": _pills_win10(),
        "features_title": L(
            it="Windows 10 Home, licenza digitale",
            en="Windows 10 Home, digital licence",
            fr="Windows 10 Home, licence numérique",
            de="Windows 10 Home — digitale Lizenz",
            es="Windows 10 Home, licencia digital",
            pt="Windows 10 Home, licença digital",
            nl="Windows 10 Home, digitale licentie",
        ),
        "features": {
            "it": [
                ("c8", "blue", "Edizione", "Home", "Edizione Home di Windows 10 per uso personale e domestico, con licenza ESD digitale."),
                ("c4", "teal", None, "32/64-bit", "Supporto architetture tipiche del prodotto Windows 10 Home."),
                ("c4", "purple", "Modello", "Senza abbonamento", "Licenza descritta in scheda, non un piano Microsoft 365."),
                ("c4", None, "Consegna", "Email", "Product key dopo il pagamento."),
                ("c4", None, "Attivazione", "Impostazioni Windows", "Attivi con il codice ricevuto sui canali Microsoft."),
                ("c4", "dark", "Nota", "Fine supporto", "Microsoft ha definito la fine del supporto per Windows 10: valuta se ti serve ancora questa versione o Windows 11."),
            ],
            "en": [
                ("c8", "blue", "Edition", "Home", "Windows 10 Home for personal and household use, with a digital ESD licence."),
                ("c4", "teal", None, "32/64-bit", "Typical architectures for the Windows 10 Home product."),
                ("c4", "purple", "Model", "No subscription", "Licence as described—not a Microsoft 365 plan."),
                ("c4", None, "Delivery", "Email", "Product key after payment."),
                ("c4", None, "Activation", "Windows Settings", "Activate with the received key via Microsoft channels."),
                ("c4", "dark", "Note", "End of support", "Microsoft has defined end of support for Windows 10—consider whether you still need this version or Windows 11."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Home", "Windows 10 Home pour usage personnel, licence ESD numérique."),
                ("c4", "teal", None, "32/64 bits", "Architectures typiques du produit Windows 10 Home."),
                ("c4", "purple", "Modèle", "Sans abonnement", "Licence décrite ici — pas Microsoft 365."),
                ("c4", None, "Livraison", "E-mail", "Clé produit après paiement."),
                ("c4", None, "Activation", "Paramètres Windows", "Activation avec le code reçu."),
                ("c4", "dark", "Note", "Fin de support", "Microsoft a fixé la fin du support de Windows 10 — évaluez Windows 11 si besoin."),
            ],
            "de": [
                ("c8", "blue", "Edition", "Home", "Windows 10 Home für den privaten Einsatz als digitale ESD-Lizenz."),
                ("c4", "teal", None, "32/64-Bit", "Typische Architekturen für Windows 10 Home."),
                ("c4", "purple", "Modell", "Ohne Abo", "Lizenz wie beschrieben — kein Microsoft 365."),
                ("c4", None, "Lieferung", "E-Mail", "Product Key nach der Zahlung."),
                ("c4", None, "Aktivierung", "Windows-Einstellungen", "Aktivierung mit dem erhaltenen Key."),
                ("c4", "dark", "Hinweis", "Support-Ende", "Microsoft hat das Support-Ende für Windows 10 definiert — ggf. Windows 11 prüfen."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Home", "Windows 10 Home para uso personal con licencia ESD digital."),
                ("c4", "teal", None, "32/64 bits", "Arquitecturas típicas del producto Windows 10 Home."),
                ("c4", "purple", "Modelo", "Sin suscripción", "Licencia descrita aquí, no Microsoft 365."),
                ("c4", None, "Entrega", "Email", "Clave de producto tras el pago."),
                ("c4", None, "Activación", "Configuración Windows", "Activa con la clave recibida."),
                ("c4", "dark", "Nota", "Fin de soporte", "Microsoft ha definido el fin de soporte de Windows 10: valora si te conviene Windows 11."),
            ],
            "pt": [
                ("c8", "blue", "Edição", "Home", "Edição Home do Windows 10 para uso pessoal e doméstico, com licença ESD digital."),
                ("c4", "teal", None, "32/64-bit", "Suporte às arquiteturas típicas do produto Windows 10 Home."),
                ("c4", "purple", "Modelo", "Sem subscrição", "Licença conforme descrita na ficha, não um plano Microsoft 365."),
                ("c4", None, "Entrega", "Email", "Product key após o pagamento."),
                ("c4", None, "Ativação", "Definições do Windows", "Ativa com o código recebido pelos canais Microsoft."),
                ("c4", "dark", "Nota", "Fim do suporte", "A Microsoft definiu o fim do suporte para o Windows 10: avalia se ainda precisas desta versão ou do Windows 11."),
            ],
        },
        "apps_title": L(it="", en="", fr="", de="", es="", pt="", nl=""),
        "faq": {
            "it": [
                ("È Windows 10 Home o Pro?", "Questa scheda è Home. Per BitLocker/RDP host valuta Windows 10 Pro."),
                ("32 o 64-bit?", "Il prodotto indica 32/64-bit: segui le istruzioni e l'architettura del tuo PC."),
                ("Come si attiva?", "Impostazioni → Aggiornamento e sicurezza / Sistema → Attivazione con il codice email."),
                ("Posso passare a Windows 11 dopo?", "Solo se l'hardware è compatibile e secondo le regole Microsoft di upgrade."),
                ("Fine supporto Microsoft?", "Informati sulle date di fine supporto Windows 10 sul sito Microsoft prima dell'acquisto."),
            ],
            "en": [
                ("Home or Pro?", "This page is Home. For BitLocker/RDP host consider Windows 10 Pro."),
                ("32 or 64-bit?", "The product lists 32/64-bit—follow instructions and your PC architecture."),
                ("How do I activate?", "Settings → Update & Security / System → Activation with the emailed key."),
                ("Can I move to Windows 11 later?", "Only if hardware is compatible and per Microsoft upgrade rules."),
                ("End of support?", "Check Microsoft’s Windows 10 end-of-support dates before buying."),
            ],
            "fr": [
                ("Home ou Pro ?", "Cette fiche est Home. Pour BitLocker/RDP hôte, voyez Windows 10 Pro."),
                ("32 ou 64 bits ?", "Le produit indique 32/64 bits — suivez les instructions et votre PC."),
                ("Activation ?", "Paramètres → Activation avec le code reçu."),
                ("Passer à Windows 11 ?", "Uniquement si le matériel est compatible selon Microsoft."),
                ("Fin de support ?", "Consultez les dates Microsoft avant l'achat."),
            ],
            "de": [
                ("Home oder Pro?", "Diese Seite ist Home. Für BitLocker/RDP-Host eher Windows 10 Pro."),
                ("32 oder 64 Bit?", "Produkt nennt 32/64-Bit — Anleitung und PC-Architektur beachten."),
                ("Aktivierung?", "Einstellungen → Aktivierung mit dem E-Mail-Key."),
                ("Später Windows 11?", "Nur bei kompatibler Hardware laut Microsoft."),
                ("Support-Ende?", "Microsoft-Daten vor dem Kauf prüfen."),
            ],
            "es": [
                ("¿Home o Pro?", "Esta ficha es Home. Para BitLocker/RDP host valora Windows 10 Pro."),
                ("¿32 o 64 bits?", "El producto indica 32/64 bits: sigue instrucciones y la arquitectura de tu PC."),
                ("¿Cómo se activa?", "Configuración → Activación con la clave del email."),
                ("¿Pasar a Windows 11 luego?", "Solo si el hardware es compatible según Microsoft."),
                ("¿Fin de soporte?", "Consulta las fechas Microsoft antes de comprar."),
            ],
            "pt": [
                ("É Windows 10 Home ou Pro?", "Esta ficha é Home. Para BitLocker/RDP anfitrião considera o Windows 10 Pro."),
                ("32 ou 64-bit?", "O produto indica 32/64-bit: segue as instruções e a arquitetura do teu PC."),
                ("Como se ativa?", "Definições → Atualização e segurança / Sistema → Ativação com o código do email."),
                ("Posso passar para o Windows 11 depois?", "Só se o hardware for compatível e segundo as regras de atualização da Microsoft."),
                ("Fim de suporte Microsoft?", "Informa-te sobre as datas de fim de suporte do Windows 10 no site da Microsoft antes de comprar."),
            ],
        },
    },
    "windows-10-pro": {
        "apps": [],
        "title_html": L(
            it='Windows 10 <span>Pro</span>',
            en='Windows 10 <span>Pro</span>',
            fr='Windows 10 <span>Pro</span>',
            de='Windows 10 <span>Pro</span>',
            es='Windows 10 <span>Pro</span>',
            pt='Windows 10 <span>Pro</span>',
            nl='Windows 10 <span>Pro</span>',
        ),
        "eyebrow": L(
            it="Sistema operativo · 32/64-bit · ESD",
            en="Operating system · 32/64-bit · ESD",
            fr="Système d'exploitation · 32/64 bits · ESD",
            de="Betriebssystem · 32/64-Bit · ESD",
            es="Sistema operativo · 32/64 bits · ESD",
            pt="Sistema operativo · 32/64-bit · ESD",
            nl="Besturingssysteem · 32/64-bit · ESD",
        ),
        "desc": L(
            it="Windows 10 Pro: licenza digitale originale 32/64-bit con funzioni professionali (BitLocker, Desktop remoto e altro secondo Microsoft). Codice via email.",
            en="Windows 10 Pro: genuine 32/64-bit digital licence with professional features (BitLocker, Remote Desktop and more per Microsoft). Key by email.",
            fr="Windows 10 Pro : licence numérique 32/64 bits avec fonctions pro (BitLocker, Bureau à distance… selon Microsoft). Code par e-mail.",
            de="Windows 10 Pro: originale 32/64-Bit-Lizenz mit Pro-Funktionen (BitLocker, Remotedesktop u. a. laut Microsoft). Key per E-Mail.",
            es="Windows 10 Pro: licencia digital 32/64 bits con funciones profesionales (BitLocker, Escritorio remoto… según Microsoft). Clave por email.",
            pt="Windows 10 Pro: licença digital 32/64-bit com funções profissionais (BitLocker, Área de Trabalho Remota e mais, segundo a Microsoft). Código por email.",
            nl="Windows 10 Pro: digitale 32/64-bit-licentie met professionele functies (BitLocker, Extern bureaublad en meer, volgens Microsoft). Code per e-mail.",
        ),
        "pills": {
            lg: [(None, "Windows 10 Pro"), (None, "32/64-bit"), (None, "ESD")]
            for lg in LANGS
        },
        "features_title": L(
            it="Windows 10 Pro per lavoro",
            en="Windows 10 Pro for work",
            fr="Windows 10 Pro pour le travail",
            de="Windows 10 Pro für die Arbeit",
            es="Windows 10 Pro para el trabajo",
            pt="Windows 10 Pro para o trabalho",
            nl="Windows 10 Pro voor werk",
        ),
        "features": {
            "it": [
                ("c8", "blue", "Edizione", "Pro", "Licenza Pro con strumenti per professionisti e PMI rispetto a Home, secondo Microsoft."),
                ("c4", "teal", None, "BitLocker", "Crittografia unità dove supportata dall'hardware e dall'edizione."),
                ("c4", "purple", "Remoto", "Desktop remoto", "Host Remote Desktop tipico delle edizioni Pro."),
                ("c4", None, "Consegna", "ESD email", "Product key dopo il pagamento."),
                ("c4", None, "Attivazione", "Ufficiale", "Attivi da Impostazioni Windows."),
                ("c4", "dark", "Nota", "Supporto Windows 10", "Verifica le date di fine supporto Microsoft se pianifichi un uso a lungo termine."),
            ],
            "en": [
                ("c8", "blue", "Edition", "Pro", "Pro licence with tools for professionals and SMBs versus Home, per Microsoft."),
                ("c4", "teal", None, "BitLocker", "Drive encryption where hardware and edition support it."),
                ("c4", "purple", "Remote", "Remote Desktop", "Remote Desktop host typical of Pro editions."),
                ("c4", None, "Delivery", "ESD email", "Product key after payment."),
                ("c4", None, "Activation", "Official", "Activate from Windows Settings."),
                ("c4", "dark", "Note", "Windows 10 support", "Check Microsoft’s end-of-support dates for long-term use."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Pro", "Licence Pro avec outils pour pros/TPE par rapport à Home."),
                ("c4", "teal", None, "BitLocker", "Chiffrement si matériel et édition le permettent."),
                ("c4", "purple", "Distant", "Bureau à distance", "Hôte Remote Desktop typique des éditions Pro."),
                ("c4", None, "Livraison", "ESD e-mail", "Clé après paiement."),
                ("c4", None, "Activation", "Officielle", "Activation dans les Paramètres Windows."),
                ("c4", "dark", "Note", "Support Windows 10", "Vérifiez les dates de fin de support Microsoft."),
            ],
            "de": [
                ("c8", "blue", "Edition", "Pro", "Pro-Lizenz mit Tools für Profis/KMU gegenüber Home."),
                ("c4", "teal", None, "BitLocker", "Laufwerksverschlüsselung bei unterstützter Hardware/Edition."),
                ("c4", "purple", "Remote", "Remotedesktop", "Remotedesktop-Host typisch für Pro."),
                ("c4", None, "Lieferung", "ESD-E-Mail", "Product Key nach der Zahlung."),
                ("c4", None, "Aktivierung", "Offiziell", "Aktivierung in den Windows-Einstellungen."),
                ("c4", "dark", "Hinweis", "Windows-10-Support", "Microsoft-Support-Ende für langfristige Nutzung prüfen."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Pro", "Licencia Pro con herramientas para profesionales/pymes frente a Home."),
                ("c4", "teal", None, "BitLocker", "Cifrado de unidad si el hardware y la edición lo permiten."),
                ("c4", "purple", "Remoto", "Escritorio remoto", "Host Remote Desktop típico de ediciones Pro."),
                ("c4", None, "Entrega", "ESD email", "Clave tras el pago."),
                ("c4", None, "Activación", "Oficial", "Activa desde Configuración de Windows."),
                ("c4", "dark", "Nota", "Soporte Windows 10", "Consulta las fechas de fin de soporte Microsoft."),
            ],
            "pt": [
                ("c8", "blue", "Edição", "Pro", "Licença Pro com ferramentas para profissionais e PME em relação ao Home, segundo a Microsoft."),
                ("c4", "teal", None, "BitLocker", "Encriptação de unidade onde suportada pelo hardware e pela edição."),
                ("c4", "purple", "Remoto", "Área de Trabalho Remota", "Anfitrião de Remote Desktop típico das edições Pro."),
                ("c4", None, "Entrega", "ESD email", "Product key após o pagamento."),
                ("c4", None, "Ativação", "Oficial", "Ativa em Definições do Windows."),
                ("c4", "dark", "Nota", "Suporte Windows 10", "Verifica as datas de fim de suporte Microsoft se planeias um uso a longo prazo."),
            ],
        },
        "apps_title": L(it="", en="", fr="", de="", es="", pt="", nl=""),
        "faq": {
            "it": [
                ("Differenza con Windows 10 Home?", "Pro include funzioni professionali aggiuntive (es. BitLocker, Desktop remoto host) rispetto a Home."),
                ("È perpetua?", "Sì: licenza ESD digitale descritta in scheda."),
                ("Come si attiva?", "Impostazioni Windows → Attivazione con il codice email."),
                ("32/64-bit?", "Segui le istruzioni e l'architettura del PC."),
                ("Passare a Windows 11?", "Solo con hardware compatibile e secondo le regole Microsoft."),
            ],
            "en": [
                ("Difference vs Home?", "Pro adds professional features (e.g. BitLocker, Remote Desktop host) versus Home."),
                ("Is it perpetual?", "Yes—digital ESD licence as described."),
                ("How do I activate?", "Windows Settings → Activation with the emailed key."),
                ("32/64-bit?", "Follow instructions and your PC architecture."),
                ("Move to Windows 11?", "Only with compatible hardware and per Microsoft rules."),
            ],
            "fr": [
                ("Différence avec Home ?", "Pro ajoute des fonctions pro (BitLocker, Bureau à distance hôte)."),
                ("Perpétuelle ?", "Oui — licence ESD numérique."),
                ("Activation ?", "Paramètres Windows → Activation avec le code."),
                ("32/64 bits ?", "Suivez les instructions et l'architecture du PC."),
                ("Passer à Windows 11 ?", "Uniquement si compatible selon Microsoft."),
            ],
            "de": [
                ("Unterschied zu Home?", "Pro ergänzt Profi-Funktionen (BitLocker, Remotedesktop-Host)."),
                ("Dauerhaft?", "Ja — digitale ESD-Lizenz."),
                ("Aktivierung?", "Windows-Einstellungen → Aktivierung mit dem Key."),
                ("32/64-Bit?", "Anleitung und PC-Architektur beachten."),
                ("Zu Windows 11?", "Nur bei kompatibler Hardware laut Microsoft."),
            ],
            "es": [
                ("¿Diferencia con Home?", "Pro añade funciones profesionales (BitLocker, Escritorio remoto host)."),
                ("¿Es perpetua?", "Sí: licencia ESD digital."),
                ("¿Cómo se activa?", "Configuración de Windows → Activación con la clave."),
                ("¿32/64 bits?", "Sigue las instrucciones y la arquitectura del PC."),
                ("¿Pasar a Windows 11?", "Solo con hardware compatible según Microsoft."),
            ],
            "pt": [
                ("Qual a diferença em relação ao Windows 10 Home?", "O Pro inclui funções profissionais adicionais (ex. BitLocker, Área de Trabalho Remota anfitrião) em relação ao Home."),
                ("É perpétua?", "Sim: licença ESD digital conforme descrito na ficha."),
                ("Como se ativa?", "Definições do Windows → Ativação com o código do email."),
                ("32/64-bit?", "Segue as instruções e a arquitetura do PC."),
                ("Posso passar para o Windows 11?", "Só com hardware compatível e segundo as regras da Microsoft."),
            ],
        },
    },
    "windows-11-pro-oem-dvd": {
        "apps": [],
        "name": L(
            it="Windows 11 Pro OEM DVD",
            en="Windows 11 Pro OEM DVD (English)",
            fr="Windows 11 Pro OEM DVD (anglais)",
            de="Windows 11 Pro OEM DVD (Englisch)",
            es="Windows 11 Pro OEM DVD (inglés)",
            pt="Windows 11 Pro OEM DVD (inglês)",
            nl="Windows 11 Pro OEM-dvd (Engels)",
        ),
        "seo_title": L(
            it="Windows 11 Pro OEM DVD Italiano | Licenza Originale",
            en="Windows 11 Pro OEM DVD (English) | Genuine Licence",
            fr="Windows 11 Pro OEM DVD (anglais) | Licence originale",
            de="Windows 11 Pro OEM DVD (Englisch) | Original-Lizenz",
            es="Windows 11 Pro OEM DVD (inglés) | Licencia original",
            pt="Windows 11 Pro OEM DVD (inglês) | Licença original",
            nl="Windows 11 Pro OEM-dvd (Engels) | Originele licentie",
        ),
        "title_html": L(
            it='Windows 11 Pro <span>OEM DVD</span>',
            en='Windows 11 Pro <span>OEM DVD</span>',
            fr='Windows 11 Pro <span>OEM DVD</span>',
            de='Windows 11 Pro <span>OEM DVD</span>',
            es='Windows 11 Pro <span>OEM DVD</span>',
            pt='Windows 11 Pro <span>OEM DVD</span>',
            nl='Windows 11 Pro <span>OEM-dvd</span>',
        ),
        "eyebrow": L(
            it="Licenza OEM · DVD italiano · COA",
            en="OEM licence · English DVD · COA",
            fr="Licence OEM · DVD anglais · COA",
            de="OEM-Lizenz · englische DVD · COA",
            es="Licencia OEM · DVD en inglés · COA",
            pt="Licença OEM · DVD em inglês · COA",
            nl="OEM-licentie · dvd in het Engels · COA",
        ),
        "desc": L(
            it="Microsoft Windows 11 Pro OEM in confezione fisica con supporto DVD in italiano e COA (Certificate of Authenticity) con Product Key. Spedizione gratuita: affidamento al corriere entro 24 ore lavorative. Non è una licenza ESD solo digitale.",
            en="Microsoft Windows 11 Pro OEM in a physical box with an English-language DVD and a COA sticker with the Product Key. Free shipping: handed to the courier within 24 business hours. Not a digital-only ESD licence.",
            fr="Microsoft Windows 11 Pro OEM en boîte physique avec DVD en anglais et sticker COA avec Product Key. Livraison gratuite : remise au transporteur sous 24 heures ouvrées. Ce n'est pas une licence ESD uniquement numérique.",
            de="Microsoft Windows 11 Pro OEM in physischer Verpackung mit englischer DVD und COA-Sticker inkl. Product Key. Kostenloser Versand: Übergabe an den Versanddienst innerhalb von 24 Werktagsstunden. Keine reine ESD-Lizenz.",
            es="Microsoft Windows 11 Pro OEM en caja física con DVD en inglés y sticker COA con Product Key. Envío gratuito: entrega al transportista en 24 horas laborables. No es una licencia ESD solo digital.",
            pt="Microsoft Windows 11 Pro OEM em caixa física com DVD em inglês e sticker COA (Certificate of Authenticity) com Product Key. Envio gratuito: entrega ao transportador em 24 horas úteis. Não é uma licença apenas digital ESD.",
            nl="Microsoft Windows 11 Pro OEM in fysieke verpakking met dvd in het Engels en COA-sticker (Certificate of Authenticity) met productsleutel. Gratis verzending: overdracht aan de koerier binnen 24 werkuren. Dit is geen uitsluitend digitale ESD-licentie.",
        ),
        "pills": {
            "it": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "DVD italiano"), (None, "COA")],
            "en": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "English DVD"), (None, "COA")],
            "fr": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "DVD anglais"), (None, "COA")],
            "de": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "Englische DVD"), (None, "COA")],
            "es": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "DVD en inglés"), (None, "COA")],
            "pt": [(None, "Windows 11 Pro"), (None, "OEM"), (None, "DVD em inglês"), (None, "COA")],
        },
        "features_title": L(
            it="Cosa ricevi e perché sceglierlo",
            en="What’s included and why choose it",
            fr="Contenu et avantages",
            de="Lieferumfang und Vorteile",
            es="Qué recibes y por qué elegirlo",
            pt="O que recebes e porque escolhê-lo",
            nl="Wat u ontvangt en waarom dit product",
        ),
        "features": {
            "it": [
                ("c12", "blue", "Cosa ricevi", "DVD + COA", "Confezione fisica Microsoft Windows 11 Pro OEM: supporto DVD in italiano, COA con Product Key per l'attivazione e documentazione in confezione. Conferma d'ordine via email. Non è una licenza ESD consegnata solo via email."),
                ("c6", "purple", "Spedizione", "Gratuita in 24h lavorative", "Affidamento al corriere entro 24 ore lavorative dopo il pagamento. Poi ricevi via email gli eventuali dati di tracking. I tempi di consegna al domicilio dipendono dal corriere."),
                ("c6", None, "Edizione Pro", "Funzioni professionali", "BitLocker, Desktop remoto, aggiunta a dominio o Microsoft Entra ID, strumenti avanzati di sicurezza e gestione — secondo l'edizione Windows 11 Pro."),
                ("c6", None, "Licenza", "Un dispositivo", "Licenza OEM per installare e usare Windows 11 Pro su un dispositivo alla volta. Trasferimenti o riattivazioni seguono le condizioni Microsoft in confezione e la normativa vigente."),
                ("c6", "dark", "Lingua media", "DVD italiano", "In Italia commercializziamo la versione con DVD in italiano. Per altre lingue del sito, le schede EU usano media in inglese."),
            ],
            "en": [
                ("c12", "blue", "What’s in the box", "DVD + COA", "Physical Microsoft Windows 11 Pro OEM package: English-language DVD, COA sticker with the Product Key, and in-box documentation. Order confirmation by email. Not a digital-only ESD licence."),
                ("c6", "purple", "Shipping", "Free · 24 business hours", "Handed to the courier within 24 business hours after payment. Tracking details follow by email when available. Door-to-door times depend on the carrier."),
                ("c6", None, "Pro edition", "Professional features", "BitLocker, Remote Desktop, domain or Microsoft Entra ID join, and advanced security/management tools — as included in Windows 11 Pro."),
                ("c6", None, "Licence", "One device", "OEM licence to install and use Windows 11 Pro on one device at a time. Transfers or reactivations follow Microsoft licence terms in the box and applicable law."),
                ("c6", "dark", "Media language", "English DVD", "Outside Italy we ship the English DVD edition. The Italian storefront sells the Italian-language DVD."),
            ],
            "fr": [
                ("c12", "blue", "Contenu", "DVD + COA", "Boîte physique Microsoft Windows 11 Pro OEM : DVD en anglais, sticker COA avec Product Key et documentation. Confirmation de commande par e-mail. Pas une licence ESD uniquement numérique."),
                ("c6", "purple", "Livraison", "Gratuite · 24 h ouvrées", "Remise au transporteur sous 24 heures ouvrées après paiement. Suivi par e-mail si disponible. Les délais jusqu'à domicile dépendent du transporteur."),
                ("c6", None, "Édition Pro", "Fonctions pro", "BitLocker, Bureau à distance, domaine ou Microsoft Entra ID, outils de sécurité et gestion — selon Windows 11 Pro."),
                ("c6", None, "Licence", "Un appareil", "Licence OEM pour installer et utiliser Windows 11 Pro sur un appareil à la fois. Transferts ou réactivations selon les conditions Microsoft et la loi applicable."),
                ("c6", "dark", "Langue du support", "DVD anglais", "Hors Italie, nous expédions le DVD en anglais. La boutique italienne commercialise le DVD en italien."),
            ],
            "de": [
                ("c12", "blue", "Lieferumfang", "DVD + COA", "Physische Microsoft Windows 11 Pro OEM-Verpackung: englische DVD, COA-Sticker mit Product Key und Unterlagen. Bestellbestätigung per E-Mail. Keine reine ESD-Lizenz."),
                ("c6", "purple", "Versand", "Kostenlos · 24 Werktagsstunden", "Übergabe an den Versanddienst innerhalb von 24 Werktagsstunden nach Zahlung. Tracking per E-Mail, falls verfügbar. Zustellzeiten hängen vom Versanddienst ab."),
                ("c6", None, "Pro-Edition", "Profi-Funktionen", "BitLocker, Remotedesktop, Domäne oder Microsoft Entra ID sowie erweiterte Sicherheits- und Verwaltungstools — wie in Windows 11 Pro."),
                ("c6", None, "Lizenz", "Ein Gerät", "OEM-Lizenz zur Installation und Nutzung von Windows 11 Pro auf einem Gerät gleichzeitig. Übertragungen/Reaktivierungen gemäß Microsoft-Bedingungen und geltendem Recht."),
                ("c6", "dark", "Medium-Sprache", "Englische DVD", "Außerhalb Italiens versenden wir die englische DVD. Der italienische Shop vertreibt die italienische DVD."),
            ],
            "es": [
                ("c12", "blue", "Qué recibes", "DVD + COA", "Caja física Microsoft Windows 11 Pro OEM: DVD en inglés, sticker COA con Product Key y documentación. Confirmación del pedido por email. No es una licencia ESD solo digital."),
                ("c6", "purple", "Envío", "Gratis · 24 h laborables", "Entrega al transportista en 24 horas laborables tras el pago. Tracking por email cuando esté disponible. Los plazos a domicilio dependen del transportista."),
                ("c6", None, "Edición Pro", "Funciones Pro", "BitLocker, Escritorio remoto, dominio o Microsoft Entra ID y herramientas avanzadas de seguridad y gestión — según Windows 11 Pro."),
                ("c6", None, "Licencia", "Un dispositivo", "Licencia OEM para instalar y usar Windows 11 Pro en un dispositivo a la vez. Transferencias o reactivaciones según condiciones Microsoft y la normativa aplicable."),
                ("c6", "dark", "Idioma del soporte", "DVD en inglés", "Fuera de Italia enviamos el DVD en inglés. La tienda italiana comercializa el DVD en italiano."),
            ],
            "pt": [
                ("c12", "blue", "O que recebes", "DVD + COA", "Embalagem física Microsoft Windows 11 Pro OEM: DVD em inglês, autocolante COA com o Product Key e documentação incluída. Confirmação da encomenda por email. Não é uma licença ESD apenas digital."),
                ("c6", "purple", "Envio", "Grátis · 24h úteis", "Entrega ao transportador dentro de 24 horas úteis após o pagamento. Recebes depois os dados de tracking por email quando disponíveis. Os prazos até casa dependem do transportador."),
                ("c6", None, "Edição Pro", "Funções profissionais", "BitLocker, Área de Trabalho Remota, entrada num domínio ou Microsoft Entra ID, e ferramentas avançadas de segurança e gestão — segundo a edição Windows 11 Pro."),
                ("c6", None, "Licença", "Um dispositivo", "Licença OEM para instalar e usar o Windows 11 Pro num dispositivo de cada vez. Transferências ou reativações seguem as condições Microsoft na embalagem e a lei aplicável."),
                ("c6", "dark", "Idioma do suporte físico", "DVD em inglês", "Fora de Itália enviamos a edição com DVD em inglês. As outras versões linguísticas do site vendem o mesmo media em inglês."),
            ],
        },
        "lifestyle": {
            "image": "windows-11-pro-oem-dvd.webp",
            "width": 800,
            "height": 800,
            "alt": L(
                it="Confezione Windows 11 Pro OEM con DVD e COA.",
                en="Windows 11 Pro OEM packaging with DVD and COA.",
                fr="Boîtier Windows 11 Pro OEM avec DVD et COA.",
                de="Windows 11 Pro OEM-Verpackung mit DVD und COA.",
                es="Packaging Windows 11 Pro OEM con DVD y COA.",
                pt="Embalagem Windows 11 Pro OEM com DVD e COA.",
                nl="Windows 11 Pro OEM-verpakking met dvd en COA.",
            ),
            "kicker": L(
                it="Prodotto fisico",
                en="Physical product",
                fr="Produit physique",
                de="Physisches Produkt",
                es="Producto físico",
                pt="Produto físico",
                nl="Fysiek product",
            ),
            "title": L(
                it="DVD + COA, non solo codice email",
                en="DVD + COA—not email-only",
                fr="DVD + COA, pas seulement un code e-mail",
                de="DVD + COA — nicht nur E-Mail-Key",
                es="DVD + COA, no solo código por email",
                pt="DVD + COA, não só um código por email",
                nl="Dvd + COA, niet alleen een code per e-mail",
            ),
            "body": L(
                it="Ricevi la confezione con DVD italiano e COA (Product Key sull'etichetta COA), più conferma d'ordine via email. Attivazione tramite i servizi Microsoft.",
                en="You receive the box with an English DVD and COA (Product Key on the COA), plus order confirmation by email. Activate through Microsoft services.",
                fr="Vous recevez la boîte avec DVD anglais et COA (Product Key sur le COA), plus confirmation par e-mail. Activation via les services Microsoft.",
                de="Sie erhalten die Box mit englischer DVD und COA (Product Key auf dem COA) sowie Bestellbestätigung per E-Mail. Aktivierung über Microsoft-Dienste.",
                es="Recibes la caja con DVD en inglés y COA (Product Key en el COA), más confirmación por email. Activación vía servicios Microsoft.",
                pt="Recebes a embalagem com DVD em inglês e COA (Product Key na etiqueta COA), mais confirmação de encomenda por email. Ativação através dos serviços Microsoft.",
                nl="U ontvangt de verpakking met dvd in het Engels en COA (productsleutel op het COA-label), plus een orderbevestiging per e-mail. Activering via de Microsoft-diensten.",
            ),
        },
        "steps_title": L(
            it="Installazione e attivazione",
            en="Installation and activation",
            fr="Installation et activation",
            de="Installation und Aktivierung",
            es="Instalación y activación",
            pt="Instalação e ativação",
            nl="Installatie en activering",
        ),
        "steps": {
            "it": [
                ("Verifica la compatibilità", "Prima dell'acquisto assicurati che il PC soddisfi i requisiti hardware di Windows 11 (CPU, RAM, TPM 2.0, UEFI con Avvio protetto)."),
                ("Installa Windows 11 Pro", "Inserisci il DVD e avvia l'installazione. Senza lettore DVD puoi creare gratuitamente un supporto USB con gli strumenti ufficiali Microsoft, poi usare il Product Key sul COA."),
                ("Attiva Windows", "Al termine: Impostazioni → Sistema → Attivazione → Cambia codice Product Key. Inserisci il codice sul COA e completa l'attivazione con i servizi Microsoft."),
            ],
            "en": [
                ("Check compatibility", "Before buying, confirm the PC meets Windows 11 hardware requirements (CPU, RAM, TPM 2.0, UEFI with Secure Boot)."),
                ("Install Windows 11 Pro", "Insert the English DVD and start setup. Without a DVD drive, create a USB install media with official Microsoft tools, then use the Product Key on the COA."),
                ("Activate Windows", "Then: Settings → System → Activation → Change product key. Enter the key on the COA and complete activation via Microsoft services."),
            ],
            "fr": [
                ("Vérifier la compatibilité", "Avant l'achat, vérifiez que le PC répond aux exigences Windows 11 (CPU, RAM, TPM 2.0, UEFI avec Secure Boot)."),
                ("Installer Windows 11 Pro", "Insérez le DVD anglais et lancez l'installation. Sans lecteur DVD, créez une clé USB avec les outils officiels Microsoft, puis utilisez le Product Key du COA."),
                ("Activer Windows", "Ensuite : Paramètres → Système → Activation → Modifier la clé de produit. Saisissez la clé du COA et terminez via Microsoft."),
            ],
            "de": [
                ("Kompatibilität prüfen", "Prüfen Sie vor dem Kauf, ob der PC die Windows-11-Anforderungen erfüllt (CPU, RAM, TPM 2.0, UEFI mit Secure Boot)."),
                ("Windows 11 Pro installieren", "Legen Sie die englische DVD ein und starten Sie Setup. Ohne DVD-Laufwerk erstellen Sie ein USB-Medium mit offiziellen Microsoft-Tools und nutzen den Product Key auf dem COA."),
                ("Windows aktivieren", "Danach: Einstellungen → System → Aktivierung → Product Key ändern. Key vom COA eingeben und über Microsoft abschließen."),
            ],
            "es": [
                ("Comprobar compatibilidad", "Antes de comprar, confirma que el PC cumple los requisitos de Windows 11 (CPU, RAM, TPM 2.0, UEFI con Arranque seguro)."),
                ("Instalar Windows 11 Pro", "Inserta el DVD en inglés e inicia la instalación. Sin unidad DVD, crea un USB con las herramientas oficiales Microsoft y usa el Product Key del COA."),
                ("Activar Windows", "Después: Configuración → Sistema → Activación → Cambiar clave de producto. Introduce la clave del COA y completa la activación con Microsoft."),
            ],
            "pt": [
                ("Verifica a compatibilidade", "Antes de comprar, confirma que o PC cumpre os requisitos de hardware do Windows 11 (CPU, RAM, TPM 2.0, UEFI com Arranque seguro)."),
                ("Instala o Windows 11 Pro", "Insere o DVD em inglês e inicia a instalação. Sem unidade de DVD, cria um suporte USB gratuitamente com as ferramentas oficiais Microsoft e usa depois o Product Key do COA."),
                ("Ativa o Windows", "No final: Definições → Sistema → Ativação → Alterar chave de produto. Introduz o código do COA e conclui a ativação com os serviços Microsoft."),
            ],
        },
        "specs_note": L(
            it="Requisiti minimi indicativi da documentazione Microsoft. Possono essere aggiornati: verifica sempre la compatibilità del dispositivo prima dell'acquisto.",
            en="Indicative minimum requirements from Microsoft documentation. They may change—always verify device compatibility before purchase.",
            fr="Exigences minimales indicatives (documentation Microsoft). Elles peuvent évoluer — vérifiez toujours la compatibilité avant l'achat.",
            de="Orientierende Mindestanforderungen laut Microsoft-Dokumentation. Änderungen möglich — Kompatibilität vor dem Kauf prüfen.",
            es="Requisitos mínimos orientativos de la documentación Microsoft. Pueden actualizarse: verifica siempre la compatibilidad antes de comprar.",
            pt="Requisitos mínimos indicativos da documentação Microsoft. Podem ser atualizados: verifica sempre a compatibilidade do dispositivo antes da compra.",
            nl="Indicatieve minimumvereisten uit de Microsoft-documentatie. Ze kunnen worden bijgewerkt: controleer altijd de compatibiliteit van het apparaat vóór aankoop.",
        ),
        "specs": {
            "it": [
                ("Processore", "Almeno 1 GHz, 2 o più core, compatibile a 64 bit."),
                ("Memoria e archiviazione", "Almeno 4 GB di RAM e 64 GB di spazio di archiviazione."),
                ("Firmware e sicurezza", "UEFI con Avvio protetto; TPM versione 2.0."),
                ("Grafica e display", "Scheda DirectX 12 con driver WDDM 2.0; schermo almeno 9\" HD 720p. Connessione Internet richiesta per alcune fasi di setup e aggiornamenti."),
            ],
            "en": [
                ("Processor", "At least 1 GHz with 2 or more cores, 64-bit compatible."),
                ("Memory and storage", "At least 4 GB RAM and 64 GB storage."),
                ("Firmware and security", "UEFI with Secure Boot; TPM version 2.0."),
                ("Graphics and display", "DirectX 12 GPU with WDDM 2.0 driver; display at least 9\" HD 720p. Internet required for some setup steps and updates."),
            ],
            "fr": [
                ("Processeur", "Au moins 1 GHz, 2 cœurs ou plus, compatible 64 bits."),
                ("Mémoire et stockage", "Au moins 4 Go de RAM et 64 Go de stockage."),
                ("Firmware et sécurité", "UEFI avec Secure Boot ; TPM version 2.0."),
                ("Graphismes et écran", "GPU DirectX 12 avec pilote WDDM 2.0 ; écran au moins 9\" HD 720p. Internet requis pour certaines étapes et les mises à jour."),
            ],
            "de": [
                ("Prozessor", "Mindestens 1 GHz, 2 oder mehr Kerne, 64-Bit-kompatibel."),
                ("Arbeitsspeicher und Speicher", "Mindestens 4 GB RAM und 64 GB Speicherplatz."),
                ("Firmware und Sicherheit", "UEFI mit Secure Boot; TPM Version 2.0."),
                ("Grafik und Display", "DirectX-12-GPU mit WDDM-2.0-Treiber; Display mindestens 9\" HD 720p. Internet für Teile der Einrichtung und Updates erforderlich."),
            ],
            "es": [
                ("Procesador", "Al menos 1 GHz, 2 o más núcleos, compatible con 64 bits."),
                ("Memoria y almacenamiento", "Al menos 4 GB de RAM y 64 GB de almacenamiento."),
                ("Firmware y seguridad", "UEFI con Arranque seguro; TPM versión 2.0."),
                ("Gráficos y pantalla", "GPU DirectX 12 con controlador WDDM 2.0; pantalla al menos 9\" HD 720p. Internet necesario para algunos pasos y actualizaciones."),
            ],
            "pt": [
                ("Processador", "Pelo menos 1 GHz, 2 ou mais núcleos, compatível com 64 bits."),
                ("Memória e armazenamento", "Pelo menos 4 GB de RAM e 64 GB de armazenamento."),
                ("Firmware e segurança", "UEFI com Arranque Seguro; TPM versão 2.0."),
                ("Gráficos e ecrã", "GPU DirectX 12 com controlador WDDM 2.0; ecrã de pelo menos 9\" HD 720p. Ligação à Internet necessária para algumas fases da configuração e atualizações."),
            ],
        },
        "apps_title": L(it="", en="", fr="", de="", es="", pt="", nl=""),
        "faq": {
            "it": [
                ("Il prodotto viene consegnato via email?", "No. È un prodotto fisico con DVD e COA, spedito all'indirizzo indicato. Ricevi via email la conferma d'ordine e le comunicazioni di spedizione/tracking."),
                ("Qual è la differenza rispetto alla versione ESD?", "L'ESD è solo digitale via email. Questa scheda include DVD fisico (italiano) e COA con Product Key, spediti con il corriere."),
                ("Posso installarlo su più computer?", "No. Serve una licenza distinta per ogni dispositivo su cui installi e usi Windows."),
                ("Posso installarlo senza lettore DVD?", "Sì. Puoi creare un USB di installazione con gli strumenti ufficiali Microsoft e attivare con il Product Key sul COA."),
                ("Posso usarlo per aggiornare Windows 11 Home?", "Dipende dalla configurazione del PC. Verifica compatibilità e che venga installata l'edizione Windows 11 Pro."),
                ("L'attivazione è garantita?", "Il codice va usato secondo le condizioni di licenza e sull'edizione corretta. Per difficoltà in installazione o attivazione, contatta l'assistenza Eurolicenze."),
            ],
            "en": [
                ("Is this delivered by email?", "No. It is a physical product with DVD and COA, shipped to your address. You receive order confirmation and shipping/tracking emails."),
                ("How does it differ from ESD?", "ESD is digital-only by email. This page includes a physical English DVD and COA with Product Key, shipped by courier."),
                ("Can I install it on multiple PCs?", "No. You need a separate licence for each device where Windows is installed and used."),
                ("Can I install without a DVD drive?", "Yes. Create USB install media with official Microsoft tools and activate with the Product Key on the COA."),
                ("Can I upgrade from Windows 11 Home?", "It depends on the PC configuration. Check compatibility and that Windows 11 Pro is installed."),
                ("Is activation guaranteed?", "The key must be used under licence terms on the correct edition. For install or activation issues, contact Eurolicenze support."),
            ],
            "fr": [
                ("Livraison par e-mail ?", "Non. Produit physique avec DVD et COA, expédié à votre adresse. Confirmation de commande et e-mails d'expédition/suivi."),
                ("Différence avec l'ESD ?", "L'ESD est uniquement numérique. Cette fiche inclut un DVD anglais et un COA avec Product Key, expédiés par transporteur."),
                ("Plusieurs PC ?", "Non. Une licence distincte est requise pour chaque appareil."),
                ("Sans lecteur DVD ?", "Oui. Créez une clé USB avec les outils Microsoft officiels et activez avec la clé du COA."),
                ("Passer de Windows 11 Famille à Pro ?", "Selon la configuration du PC. Vérifiez la compatibilité et l'installation de Windows 11 Pro."),
                ("Activation garantie ?", "La clé doit être utilisée selon la licence et la bonne édition. En cas de difficulté, contactez l'assistance Eurolicenze."),
            ],
            "de": [
                ("Lieferung per E-Mail?", "Nein. Physisches Produkt mit DVD und COA an Ihre Adresse. Bestellbestätigung und Versand-/Tracking-E-Mails."),
                ("Unterschied zu ESD?", "ESD ist rein digital. Diese Seite umfasst eine englische DVD und COA mit Product Key, versendet per Versanddienst."),
                ("Mehrere PCs?", "Nein. Pro Gerät ist eine eigene Lizenz nötig."),
                ("Ohne DVD-Laufwerk?", "Ja. USB-Installationsmedium mit offiziellen Microsoft-Tools erstellen und mit dem Key auf dem COA aktivieren."),
                ("Von Windows 11 Home upgraden?", "Abhängig von der PC-Konfiguration. Kompatibilität prüfen und Windows 11 Pro installieren."),
                ("Aktivierung garantiert?", "Der Key muss gemäß Lizenzbedingungen und korrekter Edition genutzt werden. Bei Problemen: Aml-Store-Support."),
            ],
            "es": [
                ("¿Se entrega por email?", "No. Es un producto físico con DVD y COA enviado a tu dirección. Recibes confirmación del pedido y emails de envío/tracking."),
                ("¿Diferencia con ESD?", "ESD es solo digital. Esta ficha incluye DVD en inglés y COA con Product Key, enviados por mensajería."),
                ("¿Varios PC?", "No. Se necesita una licencia distinta por cada dispositivo."),
                ("¿Sin unidad DVD?", "Sí. Crea un USB con las herramientas oficiales Microsoft y activa con la clave del COA."),
                ("¿Actualizar desde Windows 11 Home?", "Depende de la configuración del PC. Verifica compatibilidad e instala Windows 11 Pro."),
                ("¿Activación garantizada?", "La clave debe usarse según la licencia y la edición correcta. Ante problemas, contacta con el soporte de Eurolicenze."),
            ],
            "pt": [
                ("O produto é entregue por email?", "Não. É um produto físico com DVD e COA, enviado para o endereço indicado. Recebes por email a confirmação do pedido e as comunicações de envio/tracking."),
                ("Qual a diferença em relação à versão ESD?", "A ESD é apenas digital por email. Esta ficha inclui DVD físico (em inglês) e COA com Product Key, enviados por transportadora."),
                ("Posso instalar em vários computadores?", "Não. É necessária uma licença distinta para cada dispositivo onde instales e uses o Windows."),
                ("Posso instalar sem leitor de DVD?", "Sim. Podes criar um USB de instalação com as ferramentas oficiais da Microsoft e ativar com o Product Key no COA."),
                ("Posso usar para atualizar do Windows 11 Home?", "Depende da configuração do PC. Verifica a compatibilidade e que seja instalada a edição Windows 11 Pro."),
                ("A ativação é garantida?", "O código deve ser usado segundo as condições de licença e na edição correta. Em caso de dificuldades na instalação ou ativação, contacta o apoio da Eurolicenze."),
            ],
        },
    },
    "windows-11-pro-coa": {
        "apps": [],
        "title_html": L(
            it='Windows 11 Pro <span>COA</span>',
            en='Windows 11 Pro <span>COA</span>',
            fr='Windows 11 Pro <span>COA</span>',
            de='Windows 11 Pro <span>COA</span>',
            es='Windows 11 Pro <span>COA</span>',
            pt='Windows 11 Pro <span>COA</span>',
            nl='Windows 11 Pro <span>COA</span>',
        ),
        "eyebrow": L(
            it="Licenza OEM · sticker COA",
            en="OEM licence · COA sticker",
            fr="Licence OEM · sticker COA",
            de="OEM-Lizenz · COA-Sticker",
            es="Licencia OEM · pegatina COA",
            pt="Licença OEM · autocolante COA",
            nl="OEM-licentie · COA-sticker",
        ),
        "desc": L(
            it="Windows 11 Pro COA: licenza OEM con sticker Certificate of Authenticity. Dopo l'ordine ricevi le istruzioni via email e segui le indicazioni Microsoft.",
            en="Windows 11 Pro COA: OEM licence with Certificate of Authenticity sticker. After ordering you receive email instructions and follow Microsoft’s guidance.",
            fr="Windows 11 Pro COA : licence OEM avec sticker Certificate of Authenticity. Instructions par e-mail après commande.",
            de="Windows 11 Pro COA: OEM-Lizenz mit Certificate-of-Authenticity-Sticker. Anleitung per E-Mail nach der Bestellung.",
            es="Windows 11 Pro COA: licencia OEM con pegatina Certificate of Authenticity. Instrucciones por email tras el pedido.",
            pt="Windows 11 Pro COA: licença OEM com autocolante Certificate of Authenticity. Após o pedido recebes as instruções por email e segues as indicações da Microsoft.",
            nl="Windows 11 Pro COA: OEM-licentie met Certificate of Authenticity-sticker. Na de bestelling ontvangt u de instructies per e-mail en volgt u de aanwijzingen van Microsoft.",
        ),
        "pills": {
            lg: [(None, "Windows 11 Pro"), (None, "OEM"), (None, "COA")]
            for lg in LANGS
        },
        "features_title": L(
            it="Pro OEM con sticker COA",
            en="Pro OEM with COA sticker",
            fr="Pro OEM avec sticker COA",
            de="Pro OEM mit COA-Sticker",
            es="Pro OEM con pegatina COA",
            pt="Pro OEM com autocolante COA",
            nl="Pro OEM met COA-sticker",
        ),
        "features": {
            "it": [
                ("c12", "blue", "Formato", "COA OEM", "Windows 11 Pro OEM con sticker Certificate of Authenticity — non è la variante solo ESD digitale."),
                ("c6", "purple", "Consegna", "Spedizione gratuita", "Articolo fisico: affidamento al corriere entro 24 ore lavorative dopo il pagamento. Conferma ordine via email."),
                ("c6", None, "Attivazione", "Codice COA", "Usa il codice sullo sticker e/o le istruzioni ricevute sui canali Microsoft."),
                ("c6", None, "Hardware", "Requisiti Win11", "Verifica CPU, TPM e Secure Boot prima dell'installazione."),
                ("c6", "dark", "Nota OEM", "Vincoli dispositivo", "Le OEM sono spesso legate al dispositivo: leggi termini e email d'ordine."),
            ],
            "en": [
                ("c12", "blue", "Format", "OEM COA", "Windows 11 Pro OEM with Certificate of Authenticity sticker—not digital-only ESD."),
                ("c6", "purple", "Delivery", "Free shipping", "Physical item: handed to the courier within 24 business hours after payment. Order confirmation by email."),
                ("c6", None, "Activation", "COA key", "Use the sticker key and/or received instructions on Microsoft channels."),
                ("c6", None, "Hardware", "Win11 requirements", "Check CPU, TPM and Secure Boot before installing."),
                ("c6", "dark", "OEM note", "Device binding", "OEM is often device-bound—read terms and order email."),
            ],
            "fr": [
                ("c12", "blue", "Format", "OEM COA", "Windows 11 Pro OEM avec sticker Certificate of Authenticity — pas une licence ESD uniquement numérique."),
                ("c6", "purple", "Livraison", "Livraison gratuite", "Article physique : remise au transporteur sous 24 heures ouvrées après paiement. Confirmation de commande par e-mail."),
                ("c6", None, "Activation", "Clé COA", "Utilisez la clé du sticker et/ou les instructions reçues."),
                ("c6", None, "Matériel", "Exigences Win11", "Vérifiez CPU, TPM et Secure Boot."),
                ("c6", "dark", "Note OEM", "Appareil", "OEM souvent liée à l'appareil — lisez conditions et e-mail."),
            ],
            "de": [
                ("c12", "blue", "Format", "OEM COA", "Windows 11 Pro OEM mit Certificate-of-Authenticity-Sticker — keine reine ESD-Lizenz."),
                ("c6", "purple", "Lieferung", "Kostenloser Versand", "Physischer Artikel: Übergabe an den Versanddienst innerhalb von 24 Werktagsstunden nach Zahlung. Bestellbestätigung per E-Mail."),
                ("c6", None, "Aktivierung", "COA-Key", "Sticker-Key und/oder erhaltene Anleitung nutzen."),
                ("c6", None, "Hardware", "Win11-Anforderungen", "CPU, TPM und Secure Boot prüfen."),
                ("c6", "dark", "OEM-Hinweis", "Gerät", "OEM oft gerätegebunden — AGB und E-Mail lesen."),
            ],
            "es": [
                ("c12", "blue", "Formato", "OEM COA", "Windows 11 Pro OEM con pegatina Certificate of Authenticity — no es solo ESD digital."),
                ("c6", "purple", "Entrega", "Envío gratuito", "Artículo físico: entrega al transportista en 24 horas laborables tras el pago. Confirmación del pedido por email."),
                ("c6", None, "Activación", "Clave COA", "Usa la clave de la pegatina y/o las instrucciones recibidas."),
                ("c6", None, "Hardware", "Requisitos Win11", "Comprueba CPU, TPM y Secure Boot."),
                ("c6", "dark", "Nota OEM", "Dispositivo", "Las OEM suelen ir ligadas al dispositivo: lee términos y email."),
            ],
            "pt": [
                ("c12", "blue", "Formato", "OEM COA", "Windows 11 Pro OEM com autocolante Certificate of Authenticity — não é a variante apenas ESD digital."),
                ("c6", "purple", "Entrega", "Envio gratuito", "Artigo físico: entregue ao transportador dentro de 24 horas úteis após o pagamento. Confirmação da encomenda por email."),
                ("c6", None, "Ativação", "Código COA", "Usa o código no autocolante e/ou as instruções recebidas nos canais Microsoft."),
                ("c6", None, "Hardware", "Requisitos Win11", "Verifica CPU, TPM e Secure Boot antes da instalação."),
                ("c6", "dark", "Nota OEM", "Vínculo ao dispositivo", "As OEM ficam muitas vezes vinculadas ao dispositivo: lê os termos e o email da encomenda."),
            ],
        },
        "lifestyle": {
            "image": "windows-11-pro-coa.webp",
            "image_640": "windows-11-pro-coa.webp",
            "width": 400,
            "height": 400,
            "alt": L(
                it="Sticker COA Windows 11 Pro OEM.",
                en="Windows 11 Pro OEM COA sticker.",
                fr="Sticker COA Windows 11 Pro OEM.",
                de="Windows 11 Pro OEM COA-Sticker.",
                es="Pegatina COA Windows 11 Pro OEM.",
                pt="Autocolante COA Windows 11 Pro OEM.",
                nl="Windows 11 Pro OEM COA-sticker.",
            ),
            "kicker": L(
                it="Certificate of Authenticity",
                en="Certificate of Authenticity",
                fr="Certificate of Authenticity",
                de="Certificate of Authenticity",
                es="Certificate of Authenticity",
                pt="Certificate of Authenticity",
                nl="Certificate of Authenticity",
            ),
            "title": L(
                it="Sticker COA fisico, regole OEM",
                en="Physical COA sticker, OEM rules",
                fr="Sticker COA physique, règles OEM",
                de="Physischer COA-Sticker, OEM-Regeln",
                es="Pegatina COA física, reglas OEM",
                pt="Autocolante COA físico, regras OEM",
                nl="Fysieke COA-sticker, OEM-regels",
            ),
            "body": L(
                it="Istruzioni via email e spedizione dello sticker secondo il checkout. Attivazione con codice COA sui canali Microsoft.",
                en="Email instructions and sticker shipping as shown at checkout. Activate with the COA key via Microsoft channels.",
                fr="Instructions par e-mail et expédition du sticker selon le checkout. Activation avec la clé COA via Microsoft.",
                de="Anleitung per E-Mail und Sticker-Versand laut Checkout. Aktivierung mit COA-Key über Microsoft.",
                es="Instrucciones por email y envío de la pegatina según el checkout. Activación con clave COA vía Microsoft.",
                pt="Instruções por email e envio do autocolante conforme o checkout. Ativação com o código COA nos canais Microsoft.",
                nl="Instructies per e-mail en verzending van de sticker volgens de checkout. Activering met de COA-code via de Microsoft-kanalen.",
            ),
        },
        "apps_title": L(it="", en="", fr="", de="", es="", pt="", nl=""),
        "faq": {
            "it": [
                ("Cos'è il COA?", "Certificate of Authenticity: sticker fisico OEM spedito a domicilio (spedizione gratuita, affidamento al corriere entro 24 ore lavorative), con conferma ordine via email."),
                ("Differenza con Pro ESD?", "COA/OEM è articolo fisico con sticker; la Pro ESD è solo digitale via email."),
                ("Come si attiva?", "Con il codice sullo sticker, nei canali Microsoft."),
                ("Serve il DVD?", "Questa scheda è COA sticker, non la variante DVD OEM."),
                ("Trasferimento?", "Le OEM hanno limiti: consulta Microsoft e i termini dell'ordine."),
            ],
            "en": [
                ("What is the COA?", "Certificate of Authenticity—physical OEM sticker with free shipping (handed to the courier within 24 business hours), plus order confirmation by email."),
                ("Difference vs Pro ESD?", "COA/OEM is a physical sticker; Pro ESD is digital-only by email."),
                ("How do I activate?", "With the sticker key via Microsoft channels."),
                ("Do I need a DVD?", "This page is the COA sticker, not the OEM DVD variant."),
                ("Transfer?", "OEM has limits—see Microsoft and order terms."),
            ],
            "fr": [
                ("Qu'est-ce que le COA ?", "Certificate of Authenticity — sticker OEM physique en livraison gratuite (remise au transporteur sous 24 heures ouvrées), plus confirmation de commande par e-mail."),
                ("Différence avec Pro ESD ?", "COA/OEM = sticker physique ; Pro ESD = numérique uniquement."),
                ("Activation ?", "Avec la clé du sticker via Microsoft."),
                ("Faut-il un DVD ?", "Cette fiche est le sticker COA, pas le DVD OEM."),
                ("Transfert ?", "Limites OEM — Microsoft et conditions de commande."),
            ],
            "de": [
                ("Was ist COA?", "Certificate of Authenticity — physischer OEM-Sticker mit kostenlosem Versand (Übergabe innerhalb von 24 Werktagsstunden) sowie Bestellbestätigung per E-Mail."),
                ("Unterschied zu Pro ESD?", "COA/OEM ist physischer Sticker; Pro ESD rein digital."),
                ("Aktivierung?", "Mit dem Sticker-Key über Microsoft."),
                ("DVD nötig?", "Diese Seite ist COA-Sticker, nicht OEM-DVD."),
                ("Übertragung?", "OEM-Grenzen — Microsoft und Bestellbedingungen."),
            ],
            "es": [
                ("¿Qué es el COA?", "Certificate of Authenticity: pegatina OEM física con envío gratuito (entrega al transportista en 24 horas laborables), más confirmación del pedido por email."),
                ("¿Diferencia con Pro ESD?", "COA/OEM es artículo físico con pegatina; Pro ESD es solo digital."),
                ("¿Cómo se activa?", "Con la clave de la pegatina, vía Microsoft."),
                ("¿Necesito DVD?", "Esta ficha es pegatina COA, no la variante DVD OEM."),
                ("¿Transferencia?", "Las OEM tienen límites: consulta Microsoft y los términos del pedido."),
            ],
            "pt": [
                ("O que é o COA?", "Certificate of Authenticity: autocolante OEM físico enviado ao domicílio (envio gratuito, entrega ao transportador em 24 horas úteis), com confirmação do pedido por email."),
                ("Diferença em relação à Pro ESD?", "COA/OEM é um artigo físico com autocolante; a Pro ESD é apenas digital por email."),
                ("Como se ativa?", "Com o código no autocolante, nos canais Microsoft."),
                ("É preciso o DVD?", "Esta ficha é o autocolante COA, não a variante DVD OEM."),
                ("Transferência?", "As OEM têm limites: consulta a Microsoft e os termos do pedido."),
            ],
        },
    },
}

backfill_lang(PRODUCTS)
backfill_lang(PRODUCTS, target="nl", source="en", translate=nl_text)


def get_windows_content(slug):
    return PRODUCTS.get(slug)
