#!/usr/bin/env python3
"""Rich product-page content for Office 2024 and Office 2019 (perpetual ESD)."""

# Icon filenames under /asset/icon/
ICON = {
    "word": "img-aml-store_Word-Icon-FY26.svg",
    "excel": "img-aml-store_Excel-Icon-FY26.svg",
    "powerpoint": "img-aml-store_PowerPoint-Icon-FY26.svg",
    "outlook": "img-aml-store_Outlook-Icon-FY26.svg",
    "onenote": "img-aml-store_OneNote-Icon-FY26.svg",
}

APPS_HOME = ["word", "excel", "powerpoint"]
APPS_HOME_BUSINESS = ["word", "excel", "powerpoint", "outlook", "onenote"]
APPS_STANDARD = ["word", "excel", "powerpoint", "outlook", "onenote"]
APPS_PRO_PLUS = ["word", "excel", "powerpoint", "outlook", "onenote"]

# Shared UI chrome (not product-specific)
UI = {
    "it": {
        "breadcrumb_nav": "Percorso navigazione",
        "hero_aria": "Prodotto e acquisto",
        "prices_aria": "Prezzi",
        "payments_aria": "Metodi di pagamento accettati",
        "save_prefix": "Risparmi",
        "save_vs": "rispetto al prezzo di listino",
        "features_eyebrow": "Perché sceglierlo",
        "apps_eyebrow": "App incluse",
        "how_eyebrow": "Come funziona",
        "how_title": "Tre passi per iniziare",
        "specs_eyebrow": "Requisiti di sistema",
        "specs_title": "Specifiche indicative",
        "specs_note": "Valori orientativi da documentazione Microsoft; verifica sempre i requisiti aggiornati prima dell'installazione.",
        "faq_eyebrow": "FAQ",
        "faq_title": "Domande frequenti",
        "cart_added": "Prodotto aggiunto al carrello.",
        "sticky_add": "Aggiungi",
        "step1_title": "Ordine e pagamento",
        "step1_body": "Aggiungi il prodotto al carrello e completa il pagamento sicuro con i metodi disponibili. Ricevi la conferma d'ordine come da condizioni mostrate in checkout.",
        "step2_title": "Consegna digitale",
        "step2_body": "Ti inviamo la <strong>product key</strong> e le istruzioni via email, di solito entro pochi minuti dall'approvazione del pagamento.",
        "step3_title": "Attivazione",
        "step3_body": 'Riscatta il codice su <a href="https://setup.office.com/Home" target="_blank" rel="noopener noreferrer">setup.office.com</a>, associa la licenza al tuo account Microsoft e installa le app da <a href="https://www.office.com" target="_blank" rel="noopener noreferrer">office.com</a>.',
        "spec_cpu": "Processore",
        "spec_cpu_body": "Windows: almeno 1,6 GHz dual‑core. Mac: Intel o Apple Silicon compatibili con macOS supportato (dove la scheda indica PC/Mac).",
        "spec_os": "Sistema operativo",
        "spec_os_body": "Windows 10/11; macOS nelle versioni supportate da Microsoft per la suite indicata.",
        "spec_ram": "Memoria (RAM)",
        "spec_ram_body": "Almeno 4 GB consigliati per le app desktop; esigenze maggiori per file grandi o funzioni avanzate.",
        "spec_disk": "Spazio su disco",
        "spec_disk_body": "Almeno 4 GB liberi tipici per l'installazione desktop; controlla la scheda ufficiale Microsoft.",
    },
    "en": {
        "breadcrumb_nav": "Breadcrumb",
        "hero_aria": "Product and purchase",
        "prices_aria": "Prices",
        "payments_aria": "Accepted payment methods",
        "save_prefix": "You save",
        "save_vs": "versus the list price",
        "features_eyebrow": "Why choose it",
        "apps_eyebrow": "Apps included",
        "how_eyebrow": "How it works",
        "how_title": "Three steps to get started",
        "specs_eyebrow": "System requirements",
        "specs_title": "Indicative specifications",
        "specs_note": "Approximate values from Microsoft documentation; always check the latest requirements before installing.",
        "faq_eyebrow": "FAQ",
        "faq_title": "Frequently asked questions",
        "cart_added": "Product added to cart.",
        "sticky_add": "Add",
        "step1_title": "Order and payment",
        "step1_body": "Add the product to your cart and complete secure checkout with the available methods. You receive an order confirmation as shown at checkout.",
        "step2_title": "Digital delivery",
        "step2_body": "We email the <strong>product key</strong> and instructions, usually within minutes after payment approval.",
        "step3_title": "Activation",
        "step3_body": 'Redeem the code at <a href="https://setup.office.com/Home" target="_blank" rel="noopener noreferrer">setup.office.com</a>, link the licence to your Microsoft account and install the apps from <a href="https://www.office.com" target="_blank" rel="noopener noreferrer">office.com</a>.',
        "spec_cpu": "Processor",
        "spec_cpu_body": "Windows: at least 1.6 GHz dual-core. Mac: Intel or Apple Silicon compatible with a supported macOS (where the SKU is PC/Mac).",
        "spec_os": "Operating system",
        "spec_os_body": "Windows 10/11; macOS versions supported by Microsoft for the indicated suite.",
        "spec_ram": "Memory (RAM)",
        "spec_ram_body": "At least 4 GB recommended for desktop apps; more for large files or advanced features.",
        "spec_disk": "Disk space",
        "spec_disk_body": "Typically at least 4 GB free for a desktop install; check Microsoft’s official requirements.",
    },
    "fr": {
        "breadcrumb_nav": "Fil d'Ariane",
        "hero_aria": "Produit et achat",
        "prices_aria": "Prix",
        "payments_aria": "Moyens de paiement acceptés",
        "save_prefix": "Vous économisez",
        "save_vs": "par rapport au prix catalogue",
        "features_eyebrow": "Pourquoi le choisir",
        "apps_eyebrow": "Applications incluses",
        "how_eyebrow": "Comment ça marche",
        "how_title": "Trois étapes pour commencer",
        "specs_eyebrow": "Configuration requise",
        "specs_title": "Spécifications indicatives",
        "specs_note": "Valeurs indicatives d'après la documentation Microsoft ; vérifiez toujours les exigences à jour avant l'installation.",
        "faq_eyebrow": "FAQ",
        "faq_title": "Questions fréquentes",
        "cart_added": "Produit ajouté au panier.",
        "sticky_add": "Ajouter",
        "step1_title": "Commande et paiement",
        "step1_body": "Ajoutez le produit au panier et finalisez le paiement sécurisé avec les moyens proposés. Vous recevez une confirmation selon les conditions affichées au checkout.",
        "step2_title": "Livraison numérique",
        "step2_body": "Nous envoyons la <strong>clé produit</strong> et les instructions par e-mail, en général quelques minutes après validation du paiement.",
        "step3_title": "Activation",
        "step3_body": 'Activez le code sur <a href="https://setup.office.com/Home" target="_blank" rel="noopener noreferrer">setup.office.com</a>, associez la licence à votre compte Microsoft et installez les apps depuis <a href="https://www.office.com" target="_blank" rel="noopener noreferrer">office.com</a>.',
        "spec_cpu": "Processeur",
        "spec_cpu_body": "Windows : au moins 1,6 GHz dual-core. Mac : Intel ou Apple Silicon compatibles avec un macOS pris en charge (si la fiche indique PC/Mac).",
        "spec_os": "Système d'exploitation",
        "spec_os_body": "Windows 10/11 ; versions macOS prises en charge par Microsoft pour la suite indiquée.",
        "spec_ram": "Mémoire (RAM)",
        "spec_ram_body": "Au moins 4 Go recommandés pour les apps de bureau ; davantage pour les gros fichiers.",
        "spec_disk": "Espace disque",
        "spec_disk_body": "En général au moins 4 Go libres pour l'installation ; consultez la fiche Microsoft officielle.",
    },
    "de": {
        "breadcrumb_nav": "Brotkrumen-Navigation",
        "hero_aria": "Produkt und Kauf",
        "prices_aria": "Preise",
        "payments_aria": "Akzeptierte Zahlungsmethoden",
        "save_prefix": "Sie sparen",
        "save_vs": "gegenüber dem Listenpreis",
        "features_eyebrow": "Warum dieses Produkt",
        "apps_eyebrow": "Enthaltene Apps",
        "how_eyebrow": "So funktioniert's",
        "how_title": "Drei Schritte zum Start",
        "specs_eyebrow": "Systemanforderungen",
        "specs_title": "Richtwerte",
        "specs_note": "Orientierungswerte aus der Microsoft-Dokumentation; prüfen Sie vor der Installation stets die aktuellen Anforderungen.",
        "faq_eyebrow": "FAQ",
        "faq_title": "Häufige Fragen",
        "cart_added": "Produkt zum Warenkorb hinzugefügt.",
        "sticky_add": "Hinzufügen",
        "step1_title": "Bestellung und Zahlung",
        "step1_body": "Legen Sie das Produkt in den Warenkorb und schließen Sie die sichere Zahlung mit den verfügbaren Methoden ab. Die Auftragsbestätigung folgt wie im Checkout angezeigt.",
        "step2_title": "Digitale Lieferung",
        "step2_body": "Wir senden den <strong>Product Key</strong> und die Anleitung per E-Mail, in der Regel wenige Minuten nach Zahlungsfreigabe.",
        "step3_title": "Aktivierung",
        "step3_body": 'Lösen Sie den Code unter <a href="https://setup.office.com/Home" target="_blank" rel="noopener noreferrer">setup.office.com</a> ein, verknüpfen Sie die Lizenz mit Ihrem Microsoft-Konto und installieren Sie die Apps über <a href="https://www.office.com" target="_blank" rel="noopener noreferrer">office.com</a>.',
        "spec_cpu": "Prozessor",
        "spec_cpu_body": "Windows: mindestens 1,6 GHz Dual-Core. Mac: Intel oder Apple Silicon mit unterstütztem macOS (wo PC/Mac angegeben).",
        "spec_os": "Betriebssystem",
        "spec_os_body": "Windows 10/11; von Microsoft für die genannte Suite unterstützte macOS-Versionen.",
        "spec_ram": "Arbeitsspeicher (RAM)",
        "spec_ram_body": "Mindestens 4 GB für Desktop-Apps empfohlen; mehr bei großen Dateien.",
        "spec_disk": "Festplattenspeicher",
        "spec_disk_body": "Typischerweise mindestens 4 GB frei für die Desktop-Installation; siehe Microsoft-Dokumentation.",
    },
    "es": {
        "breadcrumb_nav": "Ruta de navegación",
        "hero_aria": "Producto y compra",
        "prices_aria": "Precios",
        "payments_aria": "Métodos de pago aceptados",
        "save_prefix": "Ahorras",
        "save_vs": "respecto al precio de lista",
        "features_eyebrow": "Por qué elegirlo",
        "apps_eyebrow": "Apps incluidas",
        "how_eyebrow": "Cómo funciona",
        "how_title": "Tres pasos para empezar",
        "specs_eyebrow": "Requisitos del sistema",
        "specs_title": "Especificaciones orientativas",
        "specs_note": "Valores orientativos según documentación Microsoft; comprueba siempre los requisitos actualizados antes de instalar.",
        "faq_eyebrow": "FAQ",
        "faq_title": "Preguntas frecuentes",
        "cart_added": "Producto añadido al carrito.",
        "sticky_add": "Añadir",
        "step1_title": "Pedido y pago",
        "step1_body": "Añade el producto al carrito y completa el pago seguro con los métodos disponibles. Recibes la confirmación según las condiciones del checkout.",
        "step2_title": "Entrega digital",
        "step2_body": "Te enviamos la <strong>clave de producto</strong> e instrucciones por email, normalmente en minutos tras aprobar el pago.",
        "step3_title": "Activación",
        "step3_body": 'Canjea el código en <a href="https://setup.office.com/Home" target="_blank" rel="noopener noreferrer">setup.office.com</a>, asocia la licencia a tu cuenta Microsoft e instala las apps desde <a href="https://www.office.com" target="_blank" rel="noopener noreferrer">office.com</a>.',
        "spec_cpu": "Procesador",
        "spec_cpu_body": "Windows: al menos 1,6 GHz dual-core. Mac: Intel o Apple Silicon con macOS compatible (si la ficha indica PC/Mac).",
        "spec_os": "Sistema operativo",
        "spec_os_body": "Windows 10/11; versiones de macOS admitidas por Microsoft para la suite indicada.",
        "spec_ram": "Memoria (RAM)",
        "spec_ram_body": "Al menos 4 GB recomendados para apps de escritorio; más para archivos grandes.",
        "spec_disk": "Espacio en disco",
        "spec_disk_body": "Normalmente al menos 4 GB libres para la instalación; consulta la ficha oficial de Microsoft.",
    },
}

# Per-product rich copy. Keys: slug → fields with lang maps or shared lists.
PRODUCTS = {
    "office-2024-home": {
        "apps": APPS_HOME,
        "title_html": {
            "it": 'Office 2024 <span>Home</span>',
            "en": 'Office 2024 <span>Home</span>',
            "fr": 'Office 2024 <span>Home</span>',
            "de": 'Office 2024 <span>Home</span>',
            "es": 'Office 2024 <span>Home</span>',
        },
        "eyebrow": {
            "it": "Licenza perpetua · PC o Mac",
            "en": "Perpetual licence · PC or Mac",
            "fr": "Licence perpétuelle · PC ou Mac",
            "de": "Dauerlizenz · PC oder Mac",
            "es": "Licencia perpetua · PC o Mac",
        },
        "desc": {
            "it": "Suite Office 2024 per uso domestico: Word, Excel e PowerPoint su PC o Mac, licenza digitale originale e consegna del codice via email in pochi minuti.",
            "en": "Office 2024 suite for home use: Word, Excel and PowerPoint on PC or Mac, genuine digital licence and email delivery of the key within minutes.",
            "fr": "Suite Office 2024 pour un usage domestique : Word, Excel et PowerPoint sur PC ou Mac, licence numérique originale et livraison du code par e-mail en quelques minutes.",
            "de": "Office-2024-Suite für den Heimgebrauch: Word, Excel und PowerPoint auf PC oder Mac, originale digitale Lizenz und Key-Zustellung per E-Mail in wenigen Minuten.",
            "es": "Suite Office 2024 para uso doméstico: Word, Excel y PowerPoint en PC o Mac, licencia digital original y entrega de la clave por email en minutos.",
        },
        "pills": {
            "it": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "en": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "fr": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "de": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "es": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
        },
        "features_title": {
            "it": "Produttività essenziale, senza abbonamento",
            "en": "Essential productivity, no subscription",
            "fr": "Productivité essentielle, sans abonnement",
            "de": "Wesentliche Produktivität ohne Abo",
            "es": "Productividad esencial, sin suscripción",
        },
        "features": {
            "it": [
                ("c8", "blue", "Licenza", "Acquisto una tantum", "Licenza perpetua ESD: paghi una volta e usi le app desktop secondo le condizioni Microsoft della edizione Home 2024."),
                ("c4", "teal", None, "3 app desktop", "Word, Excel e PowerPoint per documenti, fogli e presentazioni sul tuo PC o Mac."),
                ("c4", "purple", "Piattaforma", "PC o Mac", "Edizione pensata per Windows e macOS, nei limiti e requisiti aggiornati da Microsoft."),
                ("c4", None, "Consegna", "Digitale via email", "Ricevi codice e istruzioni dopo il pagamento, senza spedizione fisica."),
                ("c4", None, "Attivazione", "setup.office.com", "Attivi sul portale ufficiale Microsoft e installi le app dal sito Office."),
                ("c4", "dark", "Ideale per", "Casa e studio", "Adatta a uso personale e domestico; per Outlook e scenari business valuta Home & Business."),
            ],
            "en": [
                ("c8", "blue", "Licence", "One-time purchase", "Perpetual ESD licence: pay once and use the desktop apps under Microsoft’s Home 2024 terms."),
                ("c4", "teal", None, "3 desktop apps", "Word, Excel and PowerPoint for documents, sheets and presentations on your PC or Mac."),
                ("c4", "purple", "Platform", "PC or Mac", "Edition designed for Windows and macOS, within Microsoft’s current limits and requirements."),
                ("c4", None, "Delivery", "Digital by email", "Receive the key and instructions after payment—no physical shipment."),
                ("c4", None, "Activation", "setup.office.com", "Activate on Microsoft’s official portal and install apps from the Office site."),
                ("c4", "dark", "Best for", "Home and study", "Suited to personal and household use; for Outlook and business scenarios consider Home & Business."),
            ],
            "fr": [
                ("c8", "blue", "Licence", "Achat unique", "Licence ESD perpétuelle : un paiement, apps de bureau selon les conditions Microsoft Home 2024."),
                ("c4", "teal", None, "3 apps de bureau", "Word, Excel et PowerPoint pour documents, tableurs et présentations sur PC ou Mac."),
                ("c4", "purple", "Plateforme", "PC ou Mac", "Édition conçue pour Windows et macOS, dans les limites et exigences Microsoft."),
                ("c4", None, "Livraison", "Numérique par e-mail", "Code et instructions après paiement, sans envoi physique."),
                ("c4", None, "Activation", "setup.office.com", "Activation sur le portail Microsoft officiel et installation depuis le site Office."),
                ("c4", "dark", "Idéal pour", "Maison et études", "Usage personnel et domestique ; pour Outlook et le business, voyez Home & Business."),
            ],
            "de": [
                ("c8", "blue", "Lizenz", "Einmalkauf", "ESD-Dauerlizenz: einmal zahlen und Desktop-Apps gemäß den Microsoft-Bedingungen für Home 2024 nutzen."),
                ("c4", "teal", None, "3 Desktop-Apps", "Word, Excel und PowerPoint für Dokumente, Tabellen und Präsentationen auf PC oder Mac."),
                ("c4", "purple", "Plattform", "PC oder Mac", "Für Windows und macOS ausgelegt, im Rahmen der aktuellen Microsoft-Anforderungen."),
                ("c4", None, "Lieferung", "Digital per E-Mail", "Key und Anleitung nach der Zahlung—ohne physischen Versand."),
                ("c4", None, "Aktivierung", "setup.office.com", "Aktivierung im offiziellen Microsoft-Portal, Installation über die Office-Website."),
                ("c4", "dark", "Ideal für", "Zuhause und Studium", "Für privaten Einsatz; für Outlook und Business eher Home & Business wählen."),
            ],
            "es": [
                ("c8", "blue", "Licencia", "Compra única", "Licencia ESD perpetua: pagas una vez y usas las apps de escritorio según las condiciones Microsoft Home 2024."),
                ("c4", "teal", None, "3 apps de escritorio", "Word, Excel y PowerPoint para documentos, hojas y presentaciones en PC o Mac."),
                ("c4", "purple", "Plataforma", "PC o Mac", "Edición pensada para Windows y macOS, dentro de los límites y requisitos de Microsoft."),
                ("c4", None, "Entrega", "Digital por email", "Clave e instrucciones tras el pago, sin envío físico."),
                ("c4", None, "Activación", "setup.office.com", "Activas en el portal oficial Microsoft e instalas desde el sitio de Office."),
                ("c4", "dark", "Ideal para", "Hogar y estudio", "Uso personal; para Outlook y negocio valora Home & Business."),
            ],
        },
        "apps_title": {
            "it": "App nella edizione Home",
            "en": "Apps in the Home edition",
            "fr": "Apps de l'édition Home",
            "de": "Apps in der Home-Edition",
            "es": "Apps de la edición Home",
        },
        "faq": {
            "it": [
                ("È un abbonamento o una licenza perpetua?", "È una licenza perpetua (acquisto una tantum) per l'edizione Office 2024 Home, non un abbonamento Microsoft 365. Restano valide le condizioni Microsoft su attivazione, dispositivi e aggiornamenti."),
                ("Quali app sono incluse?", "Word, Excel e PowerPoint per PC o Mac, secondo l'offerta Microsoft per Home 2024. Outlook e altre app business non fanno parte di questa edizione."),
                ("Posso usarlo offline?", "Sì, con le app desktop installate puoi lavorare offline; possono servire connessione e verifiche periodiche della licenza come da regole Microsoft."),
                ("Come si attiva dopo l'acquisto?", "Apri setup.office.com, accedi con l'account Microsoft, inserisci il codice ricevuto via email e segui la procedura. Poi installa le app da office.com."),
                ("Per chi è pensato Office 2024 Home?", "Per uso domestico e personale. Se ti serve Outlook o un uso più professionale, valuta Office 2024 Home & Business."),
            ],
            "en": [
                ("Is this a subscription or a perpetual licence?", "It is a perpetual (one-time) licence for Office 2024 Home, not a Microsoft 365 subscription. Microsoft’s terms on activation, devices and updates still apply."),
                ("Which apps are included?", "Word, Excel and PowerPoint for PC or Mac, per Microsoft’s Home 2024 offer. Outlook and other business apps are not part of this edition."),
                ("Can I use it offline?", "Yes—with desktop apps installed you can work offline; periodic connectivity and licence checks may still apply under Microsoft’s rules."),
                ("How do I activate after purchase?", "Go to setup.office.com, sign in with your Microsoft account, enter the email key and follow the wizard. Then install apps from office.com."),
                ("Who is Office 2024 Home for?", "Home and personal use. If you need Outlook or more professional scenarios, consider Office 2024 Home & Business."),
            ],
            "fr": [
                ("Abonnement ou licence perpétuelle ?", "Licence perpétuelle (achat unique) pour Office 2024 Home, pas un abonnement Microsoft 365. Les conditions Microsoft restent applicables."),
                ("Quelles apps sont incluses ?", "Word, Excel et PowerPoint pour PC ou Mac selon l'offre Microsoft Home 2024. Outlook et apps métier ne font pas partie de cette édition."),
                ("Puis-je l'utiliser hors ligne ?", "Oui, avec les apps de bureau installées ; des vérifications périodiques de licence peuvent s'appliquer selon Microsoft."),
                ("Comment activer après l'achat ?", "Allez sur setup.office.com, connectez-vous, saisissez le code reçu par e-mail, puis installez depuis office.com."),
                ("Pour qui est Office 2024 Home ?", "Usage domestique et personnel. Pour Outlook ou un usage pro, voyez Home & Business."),
            ],
            "de": [
                ("Abo oder Dauerlizenz?", "Dauerlizenz (Einmalkauf) für Office 2024 Home, kein Microsoft-365-Abo. Microsoft-Bedingungen zu Aktivierung und Geräten gelten weiter."),
                ("Welche Apps sind enthalten?", "Word, Excel und PowerPoint für PC oder Mac gemäß Microsoft Home 2024. Outlook und Business-Apps gehören nicht dazu."),
                ("Offline nutzbar?", "Ja, mit installierten Desktop-Apps; periodische Lizenzprüfungen können laut Microsoft gelten."),
                ("Wie aktiviere ich nach dem Kauf?", "setup.office.com öffnen, Microsoft-Konto anmelden, Key aus der E-Mail eingeben, Apps über office.com installieren."),
                ("Für wen ist Office 2024 Home?", "Privat und Zuhause. Für Outlook oder professionellere Nutzung eher Home & Business."),
            ],
            "es": [
                ("¿Suscripción o licencia perpetua?", "Licencia perpetua (compra única) de Office 2024 Home, no una suscripción Microsoft 365. Siguen aplicando las condiciones Microsoft."),
                ("¿Qué apps incluye?", "Word, Excel y PowerPoint para PC o Mac según la oferta Home 2024. Outlook y apps de negocio no forman parte de esta edición."),
                ("¿Se puede usar sin conexión?", "Sí, con las apps de escritorio instaladas; pueden aplicarse comprobaciones periódicas de licencia según Microsoft."),
                ("¿Cómo se activa tras la compra?", "Ve a setup.office.com, inicia sesión, introduce la clave del email e instala desde office.com."),
                ("¿Para quién es Office 2024 Home?", "Uso doméstico y personal. Si necesitas Outlook o un uso más profesional, valora Home & Business."),
            ],
        },
    },
    "office-2024-home-business": {
        "apps": APPS_HOME_BUSINESS,
        "name": {
            "it": "Office 2024 Home & Business",
            "en": "Office 2024 Home & Business",
            "fr": "Office 2024 Home & Business",
            "de": "Office 2024 Home & Business",
            "es": "Office 2024 Home & Business",
        },
        "title_html": {
            "it": 'Office Home &amp;<br><span>Business 2024</span>',
            "en": 'Office Home &amp;<br><span>Business 2024</span>',
            "fr": 'Office Home &amp;<br><span>Business 2024</span>',
            "de": 'Office Home &amp;<br><span>Business 2024</span>',
            "es": 'Office Home &amp;<br><span>Business 2024</span>',
        },
        "eyebrow": {
            "it": "Acquisto unico · 1 PC o Mac · nessun abbonamento",
            "en": "One-time purchase · 1 PC or Mac · no subscription",
            "fr": "Achat unique · 1 PC ou Mac · sans abonnement",
            "de": "Einmalkauf · 1 PC oder Mac · kein Abo",
            "es": "Compra única · 1 PC o Mac · sin suscripción",
        },
        "desc": {
            "it": "Le app Office classiche per casa e lavoro: Word, Excel, PowerPoint, Outlook e OneNote su 1 PC o Mac. Licenza digitale ESD perpetua, codice via email.",
            "en": "Classic Office apps for home and work: Word, Excel, PowerPoint, Outlook and OneNote on 1 PC or Mac. Perpetual ESD licence, key by email.",
            "fr": "Apps Office classiques maison/travail : Word, Excel, PowerPoint, Outlook et OneNote sur 1 PC ou Mac. Licence ESD perpétuelle, code par e-mail.",
            "de": "Klassische Office-Apps für Zuhause und Arbeit: Word, Excel, PowerPoint, Outlook und OneNote auf 1 PC oder Mac. ESD-Dauerlizenz, Key per E-Mail.",
            "es": "Apps Office clásicas para hogar y trabajo: Word, Excel, PowerPoint, Outlook y OneNote en 1 PC o Mac. Licencia ESD perpetua, clave por email.",
        },
        "pills": {
            "it": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook"), ("onenote", "OneNote")],
            "en": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook"), ("onenote", "OneNote")],
            "fr": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook"), ("onenote", "OneNote")],
            "de": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook"), ("onenote", "OneNote")],
            "es": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook"), ("onenote", "OneNote")],
        },
        "features_title": {
            "it": "Perché scegliere Home & Business",
            "en": "Why choose Home & Business",
            "fr": "Pourquoi choisir Home & Business",
            "de": "Warum Home & Business",
            "es": "Por qué elegir Home & Business",
        },
        "features": {
            "it": [
                ("c8", "blue", "Licenza", "Paghi una volta · perpetua", "Licenza ESD permanente per 1 PC o Mac secondo le condizioni Microsoft Home & Business 2024: niente rinnovo annuale obbligatorio."),
                ("c4", "teal", None, "5 app incluse", "Word, Excel, PowerPoint, Outlook e OneNote — le versioni classiche 2024 per casa e lavoro."),
                ("c4", "purple", "Piattaforma", "Windows o Mac", "Compatibile con Windows 10/11 e macOS supportati (incluso Apple Silicon dove previsto da Microsoft)."),
                ("c4", None, "Consegna", "Email in pochi minuti", "Chiave originale e istruzioni digitali dopo il pagamento approvato."),
                ("c4", None, "Attivazione", "setup.office.com", "Riscatta il codice, associa l'account Microsoft e installa da office.com."),
                ("c4", "dark", "Ideale per", "Professionisti e PMI", "Quando ti servono le app desktop più Outlook, senza passare all'abbonamento Microsoft 365."),
            ],
            "en": [
                ("c8", "blue", "Licence", "Pay once · perpetual", "Permanent ESD licence for 1 PC or Mac under Microsoft Home & Business 2024 terms—no mandatory yearly renewal."),
                ("c4", "teal", None, "5 apps included", "Word, Excel, PowerPoint, Outlook and OneNote — classic 2024 apps for home and work."),
                ("c4", "purple", "Platform", "Windows or Mac", "For Windows 10/11 and supported macOS (including Apple Silicon where Microsoft provides it)."),
                ("c4", None, "Delivery", "Email in minutes", "Genuine key and digital instructions after approved payment."),
                ("c4", None, "Activation", "setup.office.com", "Redeem the key, link your Microsoft account and install from office.com."),
                ("c4", "dark", "Best for", "Pros and small business", "Desktop apps plus Outlook without moving to a Microsoft 365 subscription."),
            ],
            "fr": [
                ("c8", "blue", "Licence", "Paiement unique · perpétuelle", "Licence ESD permanente pour 1 PC ou Mac selon Home & Business 2024 — sans renouvellement annuel obligatoire."),
                ("c4", "teal", None, "5 apps incluses", "Word, Excel, PowerPoint, Outlook et OneNote — versions classiques 2024 pour la maison et le travail."),
                ("c4", "purple", "Plateforme", "Windows ou Mac", "Windows 10/11 et macOS pris en charge (Apple Silicon selon Microsoft)."),
                ("c4", None, "Livraison", "E-mail rapide", "Clé originale et instructions après validation du paiement."),
                ("c4", None, "Activation", "setup.office.com", "Code, compte Microsoft, installation via office.com."),
                ("c4", "dark", "Idéal pour", "Pros et TPE", "Apps de bureau plus Outlook sans abonnement Microsoft 365."),
            ],
            "de": [
                ("c8", "blue", "Lizenz", "Einmal zahlen · dauerhaft", "Permanente ESD-Lizenz für 1 PC oder Mac gemäß Home & Business 2024—ohne Pflicht-Jahresabo."),
                ("c4", "teal", None, "5 Apps inklusive", "Word, Excel, PowerPoint, Outlook und OneNote — klassische 2024-Apps für Zuhause und Arbeit."),
                ("c4", "purple", "Plattform", "Windows oder Mac", "Windows 10/11 und unterstütztes macOS (Apple Silicon laut Microsoft)."),
                ("c4", None, "Lieferung", "E-Mail in Minuten", "Original-Key und Anleitung nach Zahlungsfreigabe."),
                ("c4", None, "Aktivierung", "setup.office.com", "Key einlösen, Microsoft-Konto, Installation über office.com."),
                ("c4", "dark", "Ideal für", "Selbstständige & KMU", "Desktop-Apps plus Outlook ohne Microsoft-365-Abo."),
            ],
            "es": [
                ("c8", "blue", "Licencia", "Pagas una vez · perpetua", "Licencia ESD permanente para 1 PC o Mac según Home & Business 2024, sin renovación anual obligatoria."),
                ("c4", "teal", None, "5 apps incluidas", "Word, Excel, PowerPoint, Outlook y OneNote — versiones clásicas 2024 para hogar y trabajo."),
                ("c4", "purple", "Plataforma", "Windows o Mac", "Windows 10/11 y macOS admitidos (Apple Silicon según Microsoft)."),
                ("c4", None, "Entrega", "Email en minutos", "Clave original e instrucciones tras el pago aprobado."),
                ("c4", None, "Activación", "setup.office.com", "Canjea la clave, cuenta Microsoft e instalación desde office.com."),
                ("c4", "dark", "Ideal para", "Autónomos y pymes", "Apps de escritorio más Outlook sin suscripción a Microsoft 365."),
            ],
        },
        "apps_title": {
            "it": "App incluse nel pacchetto",
            "en": "Apps included in the pack",
            "fr": "Apps incluses dans le pack",
            "de": "Apps im Paket",
            "es": "Apps incluidas en el pack",
        },
        # Full-bleed lifestyle band (after bento, before apps). Reuses Win11 gallery CWV pattern.
        "lifestyle": {
            "image": "office-2024-home-business-lifestyle.webp",
            "image_640": "office-2024-home-business-lifestyle-640.webp",
            "width": 1024,
            "height": 640,
            "alt": {
                "it": "Scrivania con laptop per lavoro e uso domestico con Office.",
                "en": "Home-office desk with a laptop for work and everyday Office use.",
                "fr": "Bureau à domicile avec ordinateur portable pour le travail et Office au quotidien.",
                "de": "Home-Office-Schreibtisch mit Laptop für Arbeit und Office im Alltag.",
                "es": "Escritorio de casa con portátil para trabajo y uso diario de Office.",
            },
            "kicker": {
                "it": "Casa e lavoro",
                "en": "Home and work",
                "fr": "Maison et travail",
                "de": "Zuhause und Arbeit",
                "es": "Hogar y trabajo",
            },
            "title": {
                "it": "Outlook incluso, senza abbonamento",
                "en": "Outlook included, no subscription",
                "fr": "Outlook inclus, sans abonnement",
                "de": "Outlook inklusive — ohne Abo",
                "es": "Outlook incluido, sin suscripción",
            },
            "body": {
                "it": "Word, Excel, PowerPoint, Outlook e OneNote su 1 PC o Mac: produttività quotidiana con licenza perpetua ESD.",
                "en": "Word, Excel, PowerPoint, Outlook and OneNote on 1 PC or Mac—everyday productivity with a perpetual ESD licence.",
                "fr": "Word, Excel, PowerPoint, Outlook et OneNote sur 1 PC ou Mac : productivité quotidienne en licence ESD perpétuelle.",
                "de": "Word, Excel, PowerPoint, Outlook und OneNote auf 1 PC oder Mac — Alltag produktiv mit ESD-Dauerlizenz.",
                "es": "Word, Excel, PowerPoint, Outlook y OneNote en 1 PC o Mac: productividad diaria con licencia ESD perpetua.",
            },
        },
        "faq": {
            "it": [
                ("Qual è la differenza tra Office 2024 e Microsoft 365?", "Office 2024 Home & Business è un acquisto unico con licenza permanente per 1 PC o Mac, senza rinnovi. Non include OneDrive 1 TB, Copilot AI o Defender tipici di Microsoft 365, che è un abbonamento con app aggiornate, cloud e AI."),
                ("La licenza di Office 2024 scade?", "No. È una licenza perpetua ESD: paghi una volta e le app restano sul dispositivo su cui le hai installate, secondo le condizioni Microsoft."),
                ("Posso installarla su più dispositivi?", "No: in genere è valida per 1 solo PC o Mac. Per più dispositivi valuta Microsoft 365 Personal o Family."),
                ("Che differenza c'è rispetto a Office 2024 Home?", "Home & Business aggiunge Outlook (e OneNote) alle app di produttività ed è pensata anche per uso professionale leggero, sempre come licenza perpetua."),
                ("Come si attiva?", "Usa setup.office.com con il codice ricevuto via email, associa l'account Microsoft e installa da office.com."),
            ],
            "en": [
                ("What’s the difference between Office 2024 and Microsoft 365?", "Office 2024 Home & Business is a one-time perpetual licence for 1 PC or Mac. It does not include typical Microsoft 365 extras (1 TB OneDrive, Copilot, Defender). Microsoft 365 is a subscription with ongoing updates, cloud and AI."),
                ("Does the Office 2024 licence expire?", "No—perpetual ESD licence. You pay once and keep the apps on the device where you installed them, under Microsoft’s terms."),
                ("Can I install it on multiple devices?", "No—typically 1 PC or Mac only. For more devices, consider Microsoft 365 Personal or Family."),
                ("How does it differ from Office 2024 Home?", "Home & Business adds Outlook (and OneNote) for light professional use, still as a perpetual licence."),
                ("How do I activate?", "Use setup.office.com with the emailed key, link your Microsoft account and install from office.com."),
            ],
            "fr": [
                ("Différence entre Office 2024 et Microsoft 365 ?", "Home & Business 2024 est un achat unique, licence permanente pour 1 PC ou Mac. Pas les services cloud/AI typiques de Microsoft 365 (abonnement)."),
                ("La licence expire-t-elle ?", "Non — licence ESD perpétuelle selon Microsoft."),
                ("Plusieurs appareils ?", "En général 1 PC ou Mac. Pour plus d'appareils, voyez Microsoft 365 Personal ou Family."),
                ("Différence avec Office 2024 Home ?", "Home & Business ajoute Outlook (et OneNote) pour un usage pro léger."),
                ("Comment activer ?", "setup.office.com avec le code reçu, compte Microsoft, installation via office.com."),
            ],
            "de": [
                ("Unterschied Office 2024 vs. Microsoft 365?", "Home & Business 2024 ist Einmalkauf mit Dauerlizenz für 1 PC oder Mac. Typische Microsoft-365-Cloud/AI-Dienste sind nicht enthalten."),
                ("Läuft die Lizenz ab?", "Nein — ESD-Dauerlizenz gemäß Microsoft."),
                ("Mehrere Geräte?", "Typisch 1 PC oder Mac. Für mehr Geräte Microsoft 365 Personal oder Family prüfen."),
                ("Unterschied zu Office 2024 Home?", "Home & Business ergänzt Outlook (und OneNote) für leichten Business-Einsatz."),
                ("Wie aktivieren?", "setup.office.com mit E-Mail-Key, Microsoft-Konto, Installation über office.com."),
            ],
            "es": [
                ("¿Diferencia entre Office 2024 y Microsoft 365?", "Home & Business 2024 es compra única con licencia permanente para 1 PC o Mac. No incluye los extras cloud/IA típicos de Microsoft 365 (suscripción)."),
                ("¿Caduca la licencia?", "No: licencia ESD perpetua según Microsoft."),
                ("¿Varios dispositivos?", "Normalmente 1 PC o Mac. Para más dispositivos, valora Microsoft 365 Personal o Family."),
                ("¿Diferencia con Office 2024 Home?", "Home & Business añade Outlook (y OneNote) para uso profesional ligero."),
                ("¿Cómo se activa?", "setup.office.com con la clave del email, cuenta Microsoft e instalación desde office.com."),
            ],
        },
    },
    "office-2019-home-student": {
        "apps": APPS_HOME,
        "title_html": {
            "it": 'Office 2019 <span>Home &amp; Student</span>',
            "en": 'Office 2019 <span>Home &amp; Student</span>',
            "fr": 'Office 2019 <span>Home &amp; Student</span>',
            "de": 'Office 2019 <span>Home &amp; Student</span>',
            "es": 'Office 2019 <span>Home &amp; Student</span>',
        },
        "eyebrow": {
            "it": "Licenza perpetua · PC o Mac",
            "en": "Perpetual licence · PC or Mac",
            "fr": "Licence perpétuelle · PC ou Mac",
            "de": "Dauerlizenz · PC oder Mac",
            "es": "Licencia perpetua · PC o Mac",
        },
        "desc": {
            "it": "Office 2019 Home & Student: Word, Excel e PowerPoint per casa e studio su PC o Mac. Licenza digitale originale con consegna via email.",
            "en": "Office 2019 Home & Student: Word, Excel and PowerPoint for home and study on PC or Mac. Genuine digital licence with email delivery.",
            "fr": "Office 2019 Home & Student : Word, Excel et PowerPoint pour la maison et les études sur PC ou Mac. Licence numérique originale, livraison par e-mail.",
            "de": "Office 2019 Home & Student: Word, Excel und PowerPoint für Zuhause und Studium auf PC oder Mac. Originale digitale Lizenz mit E-Mail-Zustellung.",
            "es": "Office 2019 Home & Student: Word, Excel y PowerPoint para hogar y estudio en PC o Mac. Licencia digital original con entrega por email.",
        },
        "pills": {
            "it": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "en": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "fr": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "de": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
            "es": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), (None, "PC / Mac")],
        },
        "features_title": {
            "it": "Office essenziale 2019, senza abbonamento",
            "en": "Essential Office 2019, no subscription",
            "fr": "Office 2019 essentiel, sans abonnement",
            "de": "Office 2019 Essential — ohne Abo",
            "es": "Office 2019 esencial, sin suscripción",
        },
        "features": {
            "it": [
                ("c8", "blue", "Licenza", "Home & Student 2019", "Licenza perpetua ESD per uso domestico e scolastico: Word, Excel e PowerPoint secondo le condizioni Microsoft 2019."),
                ("c4", "teal", None, "3 app classiche", "Le app fondamentali per documenti, fogli di calcolo e presentazioni."),
                ("c4", "purple", "Piattaforma", "PC o Mac", "Edizione disponibile per Windows e macOS supportati per Office 2019."),
                ("c4", None, "Consegna", "Email digitale", "Codice e istruzioni dopo il pagamento, senza spedizione fisica."),
                ("c4", None, "Attivazione", "setup.office.com", "Attivi sul portale Microsoft e installi le app della suite 2019."),
                ("c4", "dark", "Nota", "Versione 2019", "Non include gli aggiornamenti di funzionalità tipici di Microsoft 365; è la suite perpetua 2019."),
            ],
            "en": [
                ("c8", "blue", "Licence", "Home & Student 2019", "Perpetual ESD licence for home and study: Word, Excel and PowerPoint under Microsoft 2019 terms."),
                ("c4", "teal", None, "3 classic apps", "The core apps for documents, spreadsheets and presentations."),
                ("c4", "purple", "Platform", "PC or Mac", "Edition for Windows and macOS supported for Office 2019."),
                ("c4", None, "Delivery", "Digital email", "Key and instructions after payment—no physical shipment."),
                ("c4", None, "Activation", "setup.office.com", "Activate on Microsoft’s portal and install the 2019 suite apps."),
                ("c4", "dark", "Note", "2019 release", "Does not include Microsoft 365-style feature updates; it is the perpetual 2019 suite."),
            ],
            "fr": [
                ("c8", "blue", "Licence", "Home & Student 2019", "Licence ESD perpétuelle pour la maison et les études : Word, Excel et PowerPoint selon Microsoft 2019."),
                ("c4", "teal", None, "3 apps classiques", "Les apps essentielles pour documents, tableurs et présentations."),
                ("c4", "purple", "Plateforme", "PC ou Mac", "Édition pour Windows et macOS pris en charge pour Office 2019."),
                ("c4", None, "Livraison", "E-mail", "Code et instructions après paiement."),
                ("c4", None, "Activation", "setup.office.com", "Activation sur le portail Microsoft et installation de la suite 2019."),
                ("c4", "dark", "Note", "Version 2019", "Pas les mises à jour fonctionnelles type Microsoft 365 : suite perpétuelle 2019."),
            ],
            "de": [
                ("c8", "blue", "Lizenz", "Home & Student 2019", "ESD-Dauerlizenz für Zuhause und Studium: Word, Excel und PowerPoint gemäß Microsoft 2019."),
                ("c4", "teal", None, "3 klassische Apps", "Die Kern-Apps für Dokumente, Tabellen und Präsentationen."),
                ("c4", "purple", "Plattform", "PC oder Mac", "Für Windows und macOS, die Office 2019 unterstützen."),
                ("c4", None, "Lieferung", "E-Mail", "Key und Anleitung nach der Zahlung."),
                ("c4", None, "Aktivierung", "setup.office.com", "Aktivierung im Microsoft-Portal und Installation der 2019-Suite."),
                ("c4", "dark", "Hinweis", "Version 2019", "Keine Microsoft-365-Feature-Updates; es ist die Dauerlizenz-Suite 2019."),
            ],
            "es": [
                ("c8", "blue", "Licencia", "Home & Student 2019", "Licencia ESD perpetua para hogar y estudio: Word, Excel y PowerPoint según Microsoft 2019."),
                ("c4", "teal", None, "3 apps clásicas", "Las apps esenciales para documentos, hojas y presentaciones."),
                ("c4", "purple", "Plataforma", "PC o Mac", "Edición para Windows y macOS admitidos en Office 2019."),
                ("c4", None, "Entrega", "Email digital", "Clave e instrucciones tras el pago."),
                ("c4", None, "Activación", "setup.office.com", "Activa en el portal Microsoft e instala la suite 2019."),
                ("c4", "dark", "Nota", "Versión 2019", "No incluye actualizaciones de funciones tipo Microsoft 365; es la suite perpetua 2019."),
            ],
        },
        "apps_title": {
            "it": "App in Home & Student 2019",
            "en": "Apps in Home & Student 2019",
            "fr": "Apps Home & Student 2019",
            "de": "Apps in Home & Student 2019",
            "es": "Apps en Home & Student 2019",
        },
        "faq": {
            "it": [
                ("Quali app include?", "Word, Excel e PowerPoint. Outlook non fa parte di Home & Student."),
                ("È un abbonamento?", "No: licenza perpetua 2019. Non ricevi gli aggiornamenti di funzionalità continui di Microsoft 365."),
                ("PC e Mac?", "Sì, dove la scheda indica PC/Mac; segui requisiti e procedura Microsoft per la piattaforma scelta."),
                ("Come si attiva?", "Con il codice via email su setup.office.com e installazione da office.com / canali Microsoft."),
                ("Meglio 2019 o 2024?", "2024 è più recente. Scegli 2019 se ti serve specificamente quella generazione o il prezzo/condizioni di questa scheda."),
            ],
            "en": [
                ("Which apps are included?", "Word, Excel and PowerPoint. Outlook is not part of Home & Student."),
                ("Is it a subscription?", "No—perpetual 2019 licence. You do not get Microsoft 365’s ongoing feature updates."),
                ("PC and Mac?", "Yes where the page says PC/Mac; follow Microsoft’s requirements for your platform."),
                ("How do I activate?", "With the emailed key at setup.office.com and install via office.com / Microsoft channels."),
                ("2019 or 2024?", "2024 is newer. Choose 2019 if you specifically need that generation or this page’s offer."),
            ],
            "fr": [
                ("Quelles apps ?", "Word, Excel et PowerPoint. Outlook n'est pas inclus dans Home & Student."),
                ("Abonnement ?", "Non — licence perpétuelle 2019. Pas les mises à jour continues de Microsoft 365."),
                ("PC et Mac ?", "Oui si la fiche indique PC/Mac ; suivez les exigences Microsoft."),
                ("Activation ?", "Code reçu par e-mail sur setup.office.com, installation via office.com."),
                ("2019 ou 2024 ?", "2024 est plus récent. Choisissez 2019 si vous visez cette génération ou cette offre."),
            ],
            "de": [
                ("Welche Apps?", "Word, Excel und PowerPoint. Outlook gehört nicht zu Home & Student."),
                ("Abo?", "Nein — Dauerlizenz 2019. Keine laufenden Microsoft-365-Feature-Updates."),
                ("PC und Mac?", "Ja, wenn die Seite PC/Mac angibt; Microsoft-Anforderungen beachten."),
                ("Aktivierung?", "E-Mail-Key unter setup.office.com, Installation über office.com."),
                ("2019 oder 2024?", "2024 ist neuer. 2019 wählen, wenn Sie genau diese Generation oder dieses Angebot brauchen."),
            ],
            "es": [
                ("¿Qué apps incluye?", "Word, Excel y PowerPoint. Outlook no forma parte de Home & Student."),
                ("¿Es suscripción?", "No: licencia perpetua 2019. No recibes las actualizaciones continuas de Microsoft 365."),
                ("¿PC y Mac?", "Sí donde la ficha indique PC/Mac; sigue los requisitos Microsoft."),
                ("¿Cómo se activa?", "Con la clave del email en setup.office.com e instalación desde office.com."),
                ("¿2019 o 2024?", "2024 es más reciente. Elige 2019 si necesitas esa generación o esta oferta."),
            ],
        },
    },
    "office-2019-professional-plus": {
        "apps": APPS_PRO_PLUS,
        "title_html": {
            "it": 'Office 2019 <span>Professional Plus</span>',
            "en": 'Office 2019 <span>Professional Plus</span>',
            "fr": 'Office 2019 <span>Professional Plus</span>',
            "de": 'Office 2019 <span>Professional Plus</span>',
            "es": 'Office 2019 <span>Professional Plus</span>',
        },
        "eyebrow": {
            "it": "Licenza perpetua · Professional Plus",
            "en": "Perpetual licence · Professional Plus",
            "fr": "Licence perpétuelle · Professional Plus",
            "de": "Dauerlizenz · Professional Plus",
            "es": "Licencia perpetua · Professional Plus",
        },
        "desc": {
            "it": "Office 2019 Professional Plus: suite desktop completa per uso professionale con licenza digitale ESD. Consegna del codice via email dopo l'acquisto.",
            "en": "Office 2019 Professional Plus: full desktop suite for professional use with a genuine ESD licence. Key delivered by email after purchase.",
            "fr": "Office 2019 Professional Plus : suite de bureau complète pour usage pro, licence ESD originale. Code livré par e-mail après l'achat.",
            "de": "Office 2019 Professional Plus: vollständige Desktop-Suite für den professionellen Einsatz als ESD-Lizenz. Key per E-Mail nach dem Kauf.",
            "es": "Office 2019 Professional Plus: suite de escritorio completa para uso profesional con licencia ESD. Clave por email tras la compra.",
        },
        "pills": {
            "it": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook")],
            "en": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook")],
            "fr": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook")],
            "de": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook")],
            "es": [("word", "Word"), ("excel", "Excel"), ("powerpoint", "PowerPoint"), ("outlook", "Outlook")],
        },
        "features_title": {
            "it": "Professional Plus 2019, senza abbonamento",
            "en": "Professional Plus 2019, no subscription",
            "fr": "Professional Plus 2019, sans abonnement",
            "de": "Professional Plus 2019 — ohne Abo",
            "es": "Professional Plus 2019, sin suscripción",
        },
        "features": {
            "it": [
                ("c8", "blue", "Edizione", "Professional Plus", "Edizione Professional Plus di Office 2019 con licenza perpetua ESD, pensata per scenari professionali secondo Microsoft."),
                ("c4", "teal", None, "Suite ampia", "Word, Excel, PowerPoint, Outlook e OneNote tra le app tipiche della linea Pro Plus."),
                ("c4", "purple", "Modello", "Acquisto una tantum", "Licenza descritta in scheda, senza rinnovo annuale tipico di Microsoft 365."),
                ("c4", None, "Consegna", "Digitale", "Chiave e istruzioni via email dopo il pagamento."),
                ("c4", None, "Attivazione", "Canali Microsoft", "Attivazione e installazione tramite i portali ufficiali Microsoft."),
                ("c4", "dark", "Nota", "Generazione 2019", "Suite perpetua 2019: non include gli aggiornamenti continui di Microsoft 365."),
            ],
            "en": [
                ("c8", "blue", "Edition", "Professional Plus", "Office 2019 Professional Plus with a perpetual ESD licence for professional scenarios under Microsoft’s terms."),
                ("c4", "teal", None, "Broad suite", "Word, Excel, PowerPoint, Outlook and OneNote among typical Pro Plus apps."),
                ("c4", "purple", "Model", "One-time purchase", "Licence as described on this page—no Microsoft 365-style yearly renewal."),
                ("c4", None, "Delivery", "Digital", "Key and instructions by email after payment."),
                ("c4", None, "Activation", "Microsoft channels", "Activate and install via official Microsoft portals."),
                ("c4", "dark", "Note", "2019 generation", "Perpetual 2019 suite—not Microsoft 365 continuous feature updates."),
            ],
            "fr": [
                ("c8", "blue", "Édition", "Professional Plus", "Office 2019 Professional Plus en licence ESD perpétuelle pour usages pro selon Microsoft."),
                ("c4", "teal", None, "Suite large", "Word, Excel, PowerPoint, Outlook et OneNote parmi les apps typiques Pro Plus."),
                ("c4", "purple", "Modèle", "Achat unique", "Licence décrite ici — pas de renouvellement annuel type Microsoft 365."),
                ("c4", None, "Livraison", "Numérique", "Clé et instructions par e-mail après paiement."),
                ("c4", None, "Activation", "Canaux Microsoft", "Activation et installation via les portails officiels Microsoft."),
                ("c4", "dark", "Note", "Génération 2019", "Suite perpétuelle 2019 — pas les mises à jour continues Microsoft 365."),
            ],
            "de": [
                ("c8", "blue", "Edition", "Professional Plus", "Office 2019 Professional Plus als ESD-Dauerlizenz für professionelle Szenarien gemäß Microsoft."),
                ("c4", "teal", None, "Breite Suite", "Word, Excel, PowerPoint, Outlook und OneNote u. a. typische Pro-Plus-Apps."),
                ("c4", "purple", "Modell", "Einmalkauf", "Lizenz wie auf dieser Seite—kein Microsoft-365-Jahresabo."),
                ("c4", None, "Lieferung", "Digital", "Key und Anleitung per E-Mail nach der Zahlung."),
                ("c4", None, "Aktivierung", "Microsoft-Kanäle", "Aktivierung und Installation über offizielle Microsoft-Portale."),
                ("c4", "dark", "Hinweis", "Generation 2019", "Dauerlizenz-Suite 2019—keine laufenden Microsoft-365-Updates."),
            ],
            "es": [
                ("c8", "blue", "Edición", "Professional Plus", "Office 2019 Professional Plus con licencia ESD perpetua para escenarios profesionales según Microsoft."),
                ("c4", "teal", None, "Suite amplia", "Word, Excel, PowerPoint, Outlook y OneNote entre las apps típicas Pro Plus."),
                ("c4", "purple", "Modelo", "Compra única", "Licencia descrita en esta ficha, sin renovación anual tipo Microsoft 365."),
                ("c4", None, "Entrega", "Digital", "Clave e instrucciones por email tras el pago."),
                ("c4", None, "Activación", "Canales Microsoft", "Activación e instalación por portales oficiales Microsoft."),
                ("c4", "dark", "Nota", "Generación 2019", "Suite perpetua 2019: no incluye actualizaciones continuas de Microsoft 365."),
            ],
        },
        "apps_title": {
            "it": "App in Professional Plus 2019",
            "en": "Apps in Professional Plus 2019",
            "fr": "Apps Professional Plus 2019",
            "de": "Apps in Professional Plus 2019",
            "es": "Apps en Professional Plus 2019",
        },
        "faq": {
            "it": [
                ("Cosa significa Professional Plus?", "È l'edizione professionale completa della linea Office 2019, tipicamente con Outlook e altre app desktop rispetto a Home & Student."),
                ("È un abbonamento?", "No: licenza perpetua ESD 2019."),
                ("Include Access o Publisher?", "Dipende dall'offerta Microsoft della licenza specifica. In scheda indichiamo le app principali; verifica email e documentazione ufficiale."),
                ("Come si attiva?", "Con il codice ricevuto via email sui portali Microsoft (es. setup.office.com)."),
                ("Perché scegliere 2019?", "Se ti serve specificamente la generazione 2019 o le condizioni di questa scheda. Per funzionalità più recenti valuta Office 2024 o Microsoft 365."),
            ],
            "en": [
                ("What does Professional Plus mean?", "It is the full professional edition of the Office 2019 line, typically with Outlook and more desktop apps than Home & Student."),
                ("Is it a subscription?", "No—perpetual ESD 2019 licence."),
                ("Does it include Access or Publisher?", "Depends on Microsoft’s offer for the specific licence. We list the main apps here; check email and official docs."),
                ("How do I activate?", "With the emailed key on Microsoft portals (e.g. setup.office.com)."),
                ("Why choose 2019?", "If you specifically need the 2019 generation or this page’s offer. For newer features consider Office 2024 or Microsoft 365."),
            ],
            "fr": [
                ("Que signifie Professional Plus ?", "Édition professionnelle complète d'Office 2019, typiquement avec Outlook et plus d'apps que Home & Student."),
                ("Abonnement ?", "Non — licence ESD perpétuelle 2019."),
                ("Access ou Publisher ?", "Selon l'offre Microsoft de la licence. Nous listons les apps principales ; vérifiez e-mail et doc officielle."),
                ("Activation ?", "Avec le code reçu sur les portails Microsoft (ex. setup.office.com)."),
                ("Pourquoi 2019 ?", "Si vous visez la génération 2019 ou cette offre. Pour plus récent : Office 2024 ou Microsoft 365."),
            ],
            "de": [
                ("Was heißt Professional Plus?", "Vollständige Professional-Edition der Office-2019-Linie, typisch mit Outlook und mehr Apps als Home & Student."),
                ("Abo?", "Nein — ESD-Dauerlizenz 2019."),
                ("Access oder Publisher?", "Abhängig vom Microsoft-Angebot. Hier die Haupt-Apps; E-Mail und offizielle Doku prüfen."),
                ("Aktivierung?", "Mit dem E-Mail-Key über Microsoft-Portale (z. B. setup.office.com)."),
                ("Warum 2019?", "Wenn Sie genau die Generation 2019 oder dieses Angebot brauchen. Für Neueres: Office 2024 oder Microsoft 365."),
            ],
            "es": [
                ("¿Qué es Professional Plus?", "La edición profesional completa de Office 2019, normalmente con Outlook y más apps que Home & Student."),
                ("¿Es suscripción?", "No: licencia ESD perpetua 2019."),
                ("¿Incluye Access o Publisher?", "Depende de la oferta Microsoft de la licencia. Aquí listamos las apps principales; revisa email y documentación oficial."),
                ("¿Cómo se activa?", "Con la clave del email en los portales Microsoft (p. ej. setup.office.com)."),
                ("¿Por qué 2019?", "Si necesitas esa generación o esta oferta. Para funciones más nuevas, valora Office 2024 o Microsoft 365."),
            ],
        },
    },
}


def get_office_content(slug):
    return PRODUCTS.get(slug)
